#!/bin/bash
# RailDock Installer
# One-command production installation
# Usage: curl -sSL https://raw.githubusercontent.com/yourname/raildock/main/install.sh | bash
# Usage: DOCKER_HOST=unix://$HOME/.colima/default/docker.sock bash install.sh

set -e

# ── Config ────────────────────────────────────
RAILDOCK_VERSION="${RAILDOCK_VERSION:-latest}"
INSTALL_DIR="${INSTALL_DIR:-$(pwd)}"
COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"
NETWORK_NAME="raildock-network"
NETWORK_BRIDGE_NAME="raildock-bridge"
SSH_KEY_DIR="$INSTALL_DIR/data/dokku-ssh"
ENV_FILE="$INSTALL_DIR/.env"

# ── Colors ────────────────────────────────────
B="\033[0;34m"
G="\033[0;32m"
Y="\033[1;33m"
R="\033[0;31m"
C="\033[0;36m"
N="\033[0m"

# ── Helpers ───────────────────────────────────
log_info()  { printf "${B}●${N} %s\n" "$1"; }
log_ok()    { printf "${G}✓${N} %s\n" "$1"; }
log_warn()  { printf "${Y}⚠${N} %s\n" "$1"; }
log_error() { printf "${R}✗${N} %s\n" "$1"; }
log_step()  { printf "\n${C}▶${N} %s\n" "$1"; }

print_banner() {
  printf "\n${B}╔══════════════════════════════════════════════════════════════╗${N}\n"
  printf "${B}║${N}                                                              ${B}║${N}\n"
  printf "${B}║${N}          ${G}⚡ RailDock Installation${N}                            ${B}║${N}\n"
  printf "${B}║${N}                                                              ${B}║${N}\n"
  printf "${B}╚══════════════════════════════════════════════════════════════╝${N}\n\n"
}

print_success() {
  local url="$1"
  printf "\n${G}╔══════════════════════════════════════════════════════════════╗${N}\n"
  printf "${G}║${N}                                                              ${G}║${N}\n"
  printf "${G}║${N}          ${G}🎉 RailDock is installed!${N}                           ${G}║${N}\n"
  printf "${G}║${N}                                                              ${G}║${N}\n"
  printf "${G}╚══════════════════════════════════════════════════════════════╝${N}\n\n"
  printf "  ${B}Dashboard:${N}     %s\n" "$url"
  printf "  ${B}Dokku SSH:${N}     ssh -p 3022 dokku@%s\n" "$url"
  printf "  ${B}First run:${N}     Open the dashboard and create your admin account\n"
  printf "  ${B}View logs:${N}     docker compose -f %s logs -f\n\n" "$COMPOSE_FILE"
}

detect_version() {
  local version="${RAILDOCK_VERSION}"
  if [ -z "$version" ] || [ "$version" = "latest" ]; then
    log_info "Detecting latest version from GitHub..."
    version=$(curl -fsSL -o /dev/null -w '%{url_effective}\n' \
      https://github.com/raildock/raildock/releases/latest 2>/dev/null | sed 's#.*/tag/##')
    if [ -z "$version" ]; then
      log_warn "Could not detect latest version, using 'latest'"
      version="latest"
    else
      log_ok "Latest version: $version"
    fi
  fi
  echo "$version"
}

generate_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
  elif [ -r /dev/urandom ]; then
    tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
  else
    date +%s%N | sha256sum | base64 | head -c 32
  fi
}

generate_master_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    tr -dc 'a-f0-9' < /dev/urandom | head -c 32
  fi
}

create_env() {
  if [ -f "$ENV_FILE" ] && [ -s "$ENV_FILE" ]; then
    log_warn ".env already exists — keeping existing credentials"
    return 0
  fi

  local pg_pass master_key jwt_secret
  pg_pass=$(generate_password)
  master_key=$(generate_master_key)
  jwt_secret=$(generate_jwt_secret)

  cat > "$ENV_FILE" <<EOF
# RailDock Environment — generated by install.sh on $(date)
RAILDOCK_DOMAIN=${RAILDOCK_DOMAIN:-localhost}
POSTGRES_PASSWORD=${pg_pass}
RAILS_MASTER_KEY=${master_key}
JWT_SECRET_KEY=${jwt_secret}
EOF

  chmod 600 "$ENV_FILE"
  log_ok "Created .env with secure credentials"
}

generate_jwt_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 64 | tr -d "=+/"| head -c 64
  elif [ -r /dev/urandom ]; then
    tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 64
  else
    date +s%N | sha256sum | base64 | head -c 64
  fi
}

generate_ssh_key() {
  mkdir -p "$SSH_KEY_DIR"
  chmod 700 "$SSH_KEY_DIR"
  if [ ! -f "$SSH_KEY_DIR/id_ed25519" ]; then
    ssh-keygen -t ed25519 -f "$SSH_KEY_DIR/id_ed25519" -N "" -C "raildock-$(date +%s)" >/dev/null 2>&1
    log_ok "Generated Ed25519 SSH key pair for Dokku"
  fi
}

inject_dokku_ssh_key() {
  local pub_key="$SSH_KEY_DIR/id_ed25519.pub"
  local dokku_container="raildock-dokku-1"

  if [ ! -f "$pub_key" ]; then
    log_warn "SSH public key not found, skipping Dokku key injection"
    return 0
  fi

  log_step "Configuring Dokku SSH access..."

  # Wait for Dokku container to be ready
  for i in $(seq 1 15); do
    if docker exec "$dokku_container" dokku version >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done

  # Check if key is already added
  if docker exec "$dokku_container" dokku ssh-keys:list 2>/dev/null | grep -q "raildock"; then
    log_ok "SSH key already registered with Dokku"
    return 0
  fi

  docker cp "$pub_key" "$dokku_container:/tmp/raildock.pub"
  docker exec "$dokku_container" dokku ssh-keys:add raildock /tmp/raildock.pub
  docker exec "$dokku_container" rm -f /tmp/raildock.pub

  log_ok "SSH key registered with Dokku"
}

check_os() {
  local os
  os=$(uname -s)
  if [ "$os" = "Darwin" ]; then
    log_warn "macOS detected — using Colima/Docker Desktop mode"
    log_info "Ensure Colima is running: colima start --cpu 4 --memory 8 --disk 60"
  elif [ "$os" != "Linux" ]; then
    log_error "Unsupported OS: $os"
    exit 1
  fi
}

check_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    log_error "Docker is not installed"
    log_info "Install: https://docs.docker.com/get-docker/"
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    log_error "Docker daemon is not running"
    if [ "$(uname)" = "Darwin" ]; then
      log_info "Start Colima:  colima start --cpu 4 --memory 8 --disk 60"
      log_info "Or start Docker Desktop"
    else
      log_info "Start Docker:  sudo systemctl start docker"
    fi
    exit 1
  fi

  log_ok "Docker is ready ($(docker version --format '{{.Server.Version}}'))"
}

check_ports() {
  local ports=("80" "443" "3022")
  local failed=0
  for port in "${ports[@]}"; do
    if command -v ss >/dev/null 2>&1 && ss -tulnp 2>/dev/null | grep -q ":${port} "; then
      log_error "Port ${port} is already in use"
      failed=1
    elif command -v lsof >/dev/null 2>&1 && lsof -Pi :"${port}" -sTCP:LISTEN >/dev/null 2>&1; then
      log_error "Port ${port} is already in use"
      failed=1
    elif command -v netstat >/dev/null 2>&1 && netstat -tulnp 2>/dev/null | grep -q ":${port} "; then
      log_error "Port ${port} is already in use"
      failed=1
    fi
  done
  if [ "$failed" -eq 1 ]; then
    exit 1
  fi
  log_ok "Required ports are available"
}

get_public_ip() {
  local ip=""
  ip=$(curl -4s --connect-timeout 5 https://ifconfig.io 2>/dev/null)
  [ -z "$ip" ] && ip=$(curl -4s --connect-timeout 5 https://icanhazip.com 2>/dev/null)
  [ -z "$ip" ] && ip=$(curl -4s --connect-timeout 5 https://ipecho.net/plain 2>/dev/null)
  if [ -z "$ip" ]; then
    ip=$(hostname -I 2>/dev/null | awk '{print $1}')
  fi
  [ -z "$ip" ] && ip="127.0.0.1"
  echo "$ip"
}

get_private_ip() {
  local ip
  ip=$(ip addr show 2>/dev/null | grep -E "inet (192\.168\.|10\.|172\.1[6-9]\.|172\.2[0-9]\.|172\.3[0-1]\.)" | head -n1 | awk '{print $2}' | cut -d/ -f1)
  [ -z "$ip" ] && ip=$(ifconfig 2>/dev/null | grep -E "inet (192\.168\.|10\.|172\.1[6-9]\.)" | head -n1 | awk '{print $2}' | sed 's/addr://')
  echo "$ip"
}

wait_for_backend() {
  log_step "Waiting for backend to be healthy..."
  for i in $(seq 1 30); do
    if docker exec raildock-backend-1 curl -sf http://localhost:3000/api/health >/dev/null 2>&1; then
      log_ok "Backend is healthy"
      return 0
    fi
    sleep 2
  done
  log_error "Backend failed to become healthy"
  log_info "Check logs: docker compose -f $COMPOSE_FILE logs backend"
  return 1
}

run_migrations() {
  log_step "Running database migrations..."
  docker exec raildock-backend-1 bin/rails db:prepare >/dev/null 2>&1 || {
    log_error "Database preparation failed"
    log_info "Check logs: docker compose -f $COMPOSE_FILE logs backend"
    exit 1
  }
  log_ok "Database is ready"
}

# ── Main Install ──────────────────────────────
install_raildock() {
  print_banner

  log_step "Checking prerequisites..."
  check_os
  check_docker
  check_ports

  log_step "Generating credentials..."
  create_env
  generate_ssh_key

  log_step "Creating Docker network..."
  docker network rm -f "$NETWORK_NAME" 2>/dev/null || true
  docker network rm -f "$NETWORK_BRIDGE_NAME" 2>/dev/null || true
  docker network create "$NETWORK_NAME" 2>/dev/null || true
  docker network create "$NETWORK_BRIDGE_NAME" 2>/dev/null || true
  log_ok "Networks ready"

  log_step "Starting RailDock stack..."
  docker compose -f "$COMPOSE_FILE" up -d --build

  wait_for_backend
  run_migrations
  inject_dokku_ssh_key

  local public_ip
  public_ip=$(get_public_ip)

  print_success "$public_ip"
}

# ── Update ────────────────────────────────────
update_raildock() {
  log_step "Updating RailDock..."
  docker compose -f "$COMPOSE_FILE" pull
  docker compose -f "$COMPOSE_FILE" up -d
  log_ok "RailDock updated"
}

# ── Entrypoint ────────────────────────────────
if [ "$1" = "update" ]; then
  update_raildock
else
  install_raildock
fi
