# frozen_string_literal: true

# Reports how a project's manifest has drifted from its live configuration and
# proposes a merged manifest that folds accepted live values back in — the
# mirror image of applying a manifest.
#
# Merge is review-first: nothing is persisted here. The caller returns the
# proposed content and the operator saves it through the normal manifest update
# path, which validates it and re-runs the preview. That keeps drift merge
# composing with the apply flow instead of opening a second write path.
#
# Safety rules:
# * A service the manifest declares but that no longer exists is never merged
#   away — dropping it goes through the removal confirmation flow (`apply`).
# * Merge only edits the manifest file; it never touches running infrastructure.
# * Foreign formats (railway.toml, app.json) map lossily onto the canonical
#   form, so merge is reported as unsupported for them.
class ManifestDrift
  MAX_SERVICES = 200

  # Reconciler field → generator key, for the fields the two disagree on.
  GENERATOR_KEY = { maintenance_mode: :maintenance }.freeze

  # The generator does not emit these; the reconciler's live value is already in
  # manifest shape.
  SCRIPT_PHASES = %w[build predeploy postdeploy].freeze

  def initialize(project, desired:)
    @project = project
    @desired = desired
    @reconciler = ManifestReconciler.new(project, desired)
  end

  def format
    (@project.manifest_format.presence || "raildock.toml").to_s
  end

  def supported?
    ManifestSerializer::NATIVE_FORMATS.include?(format)
  end

  # Read-only view of the drift, grouped by service.
  def report
    changes = @reconciler.diff(preserve_removed_services: true)
    field_changes = changes.reject { |change| change.field == :link }
    live_only = services_only_live

    services = (field_changes.group_by(&:service_name)).map do |name, service_changes|
      service_report(name, service_changes)
    end
    live_only.each { |name| services << missing_from_manifest_report(name) }

    {
      drift_detected: services.any? { |service| service[:status] != "in_sync" },
      merge_supported: supported?,
      format: format,
      services: services,
      summary: {
        drifted_services: services.count { |service| service[:status] == "drifted" },
        drifted_fields: field_changes.size,
        missing_from_manifest: live_only.size,
        missing_from_host: services.count { |service| service[:status] == "missing_from_host" },
        mergeable_services: services.count { |service| service[:mergeable] }
      }
    }
  end

  # Proposed manifest with the accepted services' drifted fields rewritten from
  # live state. Returns nil when merge is not possible for this project.
  def merged(names, accept_all: false)
    return nil unless supported?

    requested = accept_all ? mergeable_service_names : Array(names).map(&:to_s).uniq.first(MAX_SERVICES)
    accepted = requested & mergeable_service_names

    services = @desired.services.map(&:deep_dup)
    index = services.index_by { |service| service[:name] }

    adopted = []
    accepted.each do |name|
      generated = live_state(name)
      next unless generated

      if index.key?(name)
        changes_for(name).each { |change| adopt(index[name], change, generated) }
      else
        index[name] = generated
        services << generated
      end
      adopted << name
    end

    content = ManifestSerializer.dump(
      { services: services, links: merged_links(adopted, index) },
      format: format,
      header: [ "Merged from live state", "Generated by RailDock — comments and formatting were regenerated" ]
    )

    { content: content, format: format, adopted: adopted, skipped: requested - adopted }
  end

  private

  # The links the manifest already declares plus the live links of every
  # adopted service whose endpoints are both in the merged manifest. Without
  # this, applying the merged manifest would delete a newly adopted service's
  # links: it would now be manifest-managed and the links would look undeclared.
  def merged_links(adopted, index)
    links = @desired.links.map { |link| link.deep_dup }
    seen = links.map { |link| [ link[:from].to_s, link[:to].to_s ] }.to_set
    names = index.keys.map(&:to_s).to_set

    adopted.each do |name|
      next unless names.include?(name.to_s)

      Array(@reconciler.actual.dig(name, :links)).each do |target|
        target = target.to_s
        pair = [ name.to_s, target ]
        next unless names.include?(target) && !seen.include?(pair)

        seen << pair
        links << { from: name.to_s, to: target }
      end
    end

    links
  end

  def mergeable_service_names
    changes = @reconciler.diff(preserve_removed_services: true)
    names = changes.reject { |change| change.field == :link || change.field == :service && change.change_type == :added }
      .map(&:service_name).uniq
    live_only = services_only_live
    (names + live_only).uniq
  end

  def changes_for(name)
    @changes_by_service ||= @reconciler.diff(preserve_removed_services: true).group_by(&:service_name)
    @changes_by_service[name] || []
  end

  def live_state(name)
    generated = ManifestGenerator.new(@project).service_state(name)
    return nil unless generated

    actual = @reconciler.actual[name] || {}
    # The generator is a manifest-writing tool, not a full projection: fill in
    # the fields it does not emit from the live state the reconciler collected.
    %i[framework restart_policy restart_max_retries auto_deploy depends_on].each do |field|
      value = actual[field]
      generated[GENERATOR_KEY[field] || field] = value unless blank_value?(value)
    end
    generated[:scripts] = normalized_scripts(actual[:scripts]) if normalized_scripts(actual[:scripts])
    generated
  end

  # Write one drifted field's live value into the manifest service. Fields the
  # reconciler knows but the generator never emits fall back to the live value,
  # which is already in manifest shape.
  def adopt(service, change, generated)
    case change.field
    when :static_site
      static = change.old_value.is_a?(Hash) ? change.old_value : {}
      assign(service, :publish_directory, static["publishDirectory"])
      assign(service, :spa_fallback, static["spaFallback"])
      assign(service, :node_version, static["nodeVersion"])
      assign(service, :plain_static, static["plainStatic"] ? true : nil)
    when :scripts
      assign(service, :scripts, normalized_scripts(change.old_value))
    when :git_repo, :branch
      source = (service[:source] || {}).dup
      source[change.field == :git_repo ? :repo : :branch] = change.old_value
      assign(service, :source, source.compact.presence)
    else
      key = GENERATOR_KEY[change.field] || change.field
      assign(service, key, generated.key?(key) ? generated[key] : change.old_value)
    end
  end

  def assign(service, key, value)
    if blank_value?(value)
      service.delete(key)
    else
      service[key] = value
    end
  end

  def blank_value?(value)
    value.nil? || value == {} || value == []
  end

  def normalized_scripts(value)
    return nil unless value.is_a?(Hash)

    phases = SCRIPT_PHASES.each_with_object({}) do |phase, result|
      command = value[phase] || value[phase.to_sym]
      result[phase.to_sym] = command if command.present?
    end
    phases.presence
  end

  def service_report(name, service_changes)
    service = @project.services.find_by(name: name)
    only_in_manifest = service_changes.any? { |change| change.field == :service && change.change_type == :added }

    {
      name: name,
      managed_by: service&.managed_by,
      status: only_in_manifest ? "missing_from_host" : "drifted",
      mergeable: !only_in_manifest,
      reason: only_in_manifest ? "Declared in the manifest but not deployed — apply the manifest to create it." : nil,
      changes: service_changes.map { |change| change_json(change) }
    }
  end

  def missing_from_manifest_report(name)
    service = @project.services.find_by(name: name)
    {
      name: name,
      managed_by: service&.managed_by,
      status: "missing_from_manifest",
      mergeable: true,
      reason: "Running but not declared in the manifest — merging adds it.",
      changes: [ { field: "service", change_type: "added_to_manifest", severity: "redeploy" } ]
    }
  end

  def change_json(change)
    {
      field: change.field.to_s,
      change_type: change.change_type.to_s,
      severity: change.severity.to_s,
      manifest_value: change.field == :service ? nil : change.new_value,
      live_value: change.old_value
    }
  end

  # Services running on the host that the manifest does not declare. UI-managed
  # services are excluded: the manifest does not own them, so adopting them
  # would silently pull them under manifest control.
  def services_only_live
    (@reconciler.actual.keys - @desired.service_names).select do |name|
      @reconciler.actual.dig(name, :managed_by) != "ui"
    end
  end
end
