[supervisord]
nodaemon=true
user=rails
logfile=/dev/null
pidfile=/dev/null

[program:nginx]
command=/usr/sbin/nginx -g "daemon off; error_log /dev/stderr warn;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=10

[program:puma]
command=bash -c "cd /rails && exec bundle exec rails server"
environment=RAILS_ENV=production,LD_PRELOAD=/usr/local/lib/libjemalloc.so
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=20
autostartretries=3

[program:worker]
command=bash -c "cd /rails && exec bundle exec rake solid_queue:start"
environment=RAILS_ENV=production,LD_PRELOAD=/usr/local/lib/libjemalloc.so
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=20
