require "rails_helper"
require "openssl"

RSpec.describe SshKeyValidator, type: :service do
  let(:valid_key) { OpenSSL::PKey::EC.generate("prime256v1").to_pem }
  let(:valid_openssh_key) do
    # Generated by ssh-keygen in PEM-like OpenSSH format
    <<~KEY
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACBmrhj1RAgqaBgR3lOgxHyn4gbrCi5F6p2bC27p4rD0JQAAAJB7YqcWe2Kn
      FgAAAAtzc2gtZWQyNTUxOQAAACBmrhj1RAgqaBgR3lOgxHyn4gbrCi5F6p2bC27p4rD0JQ
      AAAEBCgly6WIM3JZBlxD9l5FPxGtSC6Jlx/SCJm9tcv2A0rZq4Y9UQIKmgYEd5ToMR8p+I
      G6wouReq6Gwu6eKw9CUAAAAAAQID
      -----END OPENSSH PRIVATE KEY-----
    KEY
  end

  describe ".validate" do
    it "returns valid for a real PEM key" do
      expect(described_class.validate(valid_key)).to eq({ valid: true })
    end

    it "returns invalid for a malformed key" do
      result = described_class.validate("not-a-key")
      expect(result[:valid]).to be false
      expect(result[:error]).to include("Could not parse")
    end

    it "returns invalid for a blank key" do
      result = described_class.validate("")
      expect(result[:valid]).to be false
      expect(result[:error]).to eq("SSH key is blank")
    end
  end
end
