name = "Activepieces"
description = "Open source no-code business automation."
category = "stack"
logo = "svgs/activepieces.png"

[[services]]
name = "activepieces"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/activepieces/activepieces:0.75.0"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    AP_API_KEY = "${{ secret() }}"
    AP_ENCRYPTION_KEY = "${{ secret() }}"
    AP_ENGINE_EXECUTABLE_PATH = "dist/packages/engine/main.js"
    AP_ENVIRONMENT = "prod"
    AP_EXECUTION_MODE = "UNSANDBOXED"
    AP_FRONTEND_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    AP_JWT_SECRET = "${{ secret() }}"
    AP_POSTGRES_DATABASE = "activepieces"
    AP_POSTGRES_HOST = "postgres"
    AP_POSTGRES_PASSWORD = "${{ linked.postgres.POSTGRES_PASSWORD }}"
    AP_POSTGRES_PORT = "5432"
    AP_POSTGRES_USERNAME = "${{ linked.postgres.POSTGRES_USER }}"
    AP_REDIS_HOST = "redis"
    AP_REDIS_PORT = "6379"
    AP_SANDBOX_RUN_TIME_SECONDS = "600"
    AP_TELEMETRY_ENABLED = "false"
    AP_TEMPLATES_SOURCE_URL = "https://cloud.activepieces.com/api/v1/flow-templates"
    AP_TRIGGER_DEFAULT_POLL_INTERVAL = "5"
    AP_SIGN_UP_ENABLED = "true"
    AP_WEBHOOK_TIMEOUT_SECONDS = "30"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_DB = "activepieces"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PORT = "5432"
    [[services.storage]]
      host = "pg-data"
      container = "/var/lib/postgresql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "activepieces"
to = "postgres"

[[links]]
from = "activepieces"
to = "redis"