name = "Actualbudget"
description = "A local-first personal finance app."
category = "stack"
logo = "svgs/actualbudget.png"

[[services]]
name = "actual_server"
category = "app"
subtype = "docker"
docker_image = "actualbudget/actual-server:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    ACTUAL_LOGIN_METHOD = "password"
    [[services.storage]]
      host = "actual_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
