name = "Alexandrie"
description = "A powerful Markdown workspace designed for speed, clarity, and creativity."
category = "stack"
logo = "svgs/alexandrie.svg"

[[services]]
name = "frontend"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/smaug6739/alexandrie-frontend:v8.7.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PORT = "8200"
    NUXT_PUBLIC_CONFIG_DISABLE_SIGNUP_PAGE = "false"
    NUXT_PUBLIC_CONFIG_DISABLE_LANDING_PAGE = "false"
    NUXT_PUBLIC_BASE_API = "https://example.com"
    NUXT_PUBLIC_BASE_CDN = "https://example.com"
    NUXT_PUBLIC_CDN_ENDPOINT = "/alexandrie/"
    NUXT_PUBLIC_BASE_URL = "https://example.com"

[[services]]
name = "backend"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/smaug6739/alexandrie-backend:v8.7.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    BACKEND_PORT = "8201"
    GIN_MODE = "release"
    JWT_SECRET = "CHANGE_ME"
    COOKIE_DOMAIN = "https://example.com"
    FRONTEND_URL = "https://example.com"
    ALLOW_UNSECURE = "false"
    DATABASE_HOST = "mysql"
    DATABASE_PORT = "3306"
    DATABASE_NAME = "alexandrie-db"
    DATABASE_USER = "user"
    DATABASE_PASSWORD = "CHANGE_ME"
    MINIO_ENDPOINT = "rustfs:9000"
    MINIO_PUBLIC_URL = "https://example.com"
    MINIO_SECURE = "false"
    MINIO_ACCESSKEY = "user"
    MINIO_SECRETKEY = "CHANGE_ME"
    MINIO_BUCKET = "alexandrie"

[[services]]
name = "mysql"
category = "database"
subtype = "mysql"
docker_image = "mysql:8.0"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "CHANGE_ME"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "CHANGE_ME"
    MYSQL_DATABASE = "alexandrie-db"
    [[services.storage]]
      host = "mysql-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "rustfs"
category = "app"
subtype = "docker"
docker_image = "rustfs/rustfs:1.0.0-alpha.90"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    RUSTFS_ACCESS_KEY = "user"
    RUSTFS_SECRET_KEY = "CHANGE_ME"
    RUSTFS_CONSOLE_ENABLE = "false"
    RUSTFS_LOG_LEVEL = "info"
    [[services.storage]]
      host = "rustfs-data"
      container = "/data"
    [[services.storage]]
      host = "rustfs-logs"
      container = "/logs"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "frontend"
to = "backend"

[[links]]
from = "backend"
to = "mysql"

[[links]]
from = "backend"
to = "rustfs"

[[links]]
from = "frontend"
to = "mysql"

[[links]]
from = "rustfs"
to = "mysql"
