name = "Anythingllm"
description = "AnythingLLM is the easiest to use, all-in-one AI application that can do RAG, AI Agents, and much more with no code or infrastructure headaches."
category = "stack"
logo = "svgs/anythingllm.svg"

[[services]]
name = "anything-llm"
category = "app"
subtype = "docker"
docker_image = "mintplexlabs/anythingllm"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    STORAGE_DIR = "/app/server/storage"
    DISABLE_TELEMETRY = "true"
    PASSWORDLOWERCASE = "1"
    PASSWORDMAXCHAR = "250"
    PASSWORDMINCHAR = "6"
    PASSWORDNUMERIC = "1"
    PASSWORDREQUIREMENTS = "1"
    PASSWORDSYMBOL = "1"
    PASSWORDUPPERCASE = "1"
    SIG_KEY = "${{ secret() }}"
    SIG_SALT = "${{ secret() }}"
    JWT_SECRET = "${{ secret() }}"
    AUTH_TOKEN = "${{ secret() }}"
    SERVER_PORT = "3001"
    VECTOR_DB = "lancedb"
    [[services.storage]]
      host = "anythingllm-storage"
      container = "/app/server/storage"
    [[services.storage]]
      host = "anythingllm-hot"
      container = "/app/collector/hotdir"
    [[services.storage]]
      host = "anythingllm-outputs"
      container = "/app/collector/outputs"
