name = "Appflowy"
description = "AppFlowy is the AI collaborative workspace where you achieve more without losing control of your data."
category = "stack"
logo = "svgs/appflowy.svg"

[[services]]
name = "nginx"
category = "app"
subtype = "docker"
docker_image = "nginx:1.29.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "appflowy_web"
category = "app"
subtype = "docker"
docker_image = "appflowyinc/appflowy_web:0.9.132"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APPFLOWY_BASE_URL = "https://example.com"
    APPFLOWY_GOTRUE_BASE_URL = "https://example.com/gotrue"
    APPFLOWY_WS_BASE_URL = "https://example.com/ws/v2"

[[services]]
name = "appflowy_cloud"
category = "app"
subtype = "docker"
docker_image = "appflowyinc/appflowy_cloud:0.9.149"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    RUST_LOG = "info"
    APPFLOWY_BASE_URL = "https://example.com"
    APPFLOWY_ENVIRONMENT = "production"
    APPFLOWY_DATABASE_URL = "postgres://user:CHANGE_ME@postgres:5432/appflowy"
    APPFLOWY_REDIS_URI = "redis://redis:6379"
    APPFLOWY_GOTRUE_JWT_SECRET = "CHANGE_ME"
    APPFLOWY_GOTRUE_BASE_URL = "http://gotrue:9999"
    APPFLOWY_S3_CREATE_BUCKET = "true"
    APPFLOWY_S3_USE_MINIO = "true"
    APPFLOWY_S3_MINIO_URL = "http://minio:9000"
    APPFLOWY_S3_ACCESS_KEY = "user"
    APPFLOWY_S3_SECRET_KEY = "CHANGE_ME"
    APPFLOWY_S3_BUCKET = "appflowy"
    APPFLOWY_S3_REGION = "us-east-1"
    APPFLOWY_MAILER_SMTP_HOST = "smtp.gmail.com"
    APPFLOWY_MAILER_SMTP_PORT = "587"
    APPFLOWY_MAILER_SMTP_USERNAME = "notify@appflowy.io"
    APPFLOWY_MAILER_SMTP_EMAIL = "notify@appflowy.io"
    APPFLOWY_MAILER_SMTP_PASSWORD = "email_sender_password"
    APPFLOWY_MAILER_SMTP_TLS_KIND = "none"
    APPFLOWY_ACCESS_CONTROL = "true"
    APPFLOWY_DATABASE_MAX_CONNECTIONS = "40"
    AI_SERVER_HOST = "ai"
    AI_SERVER_PORT = "5001"
    APPFLOWY_WEB_URL = "https://example.com"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "gotrue"
category = "app"
subtype = "docker"
docker_image = "appflowyinc/gotrue:0.9.149"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    GOTRUE_API_HOST = "0.0.0.0"
    GOTRUE_API_PORT = "9999"
    PORT = "9999"
    GOTRUE_ADMIN_EMAIL = "admin@example.com"
    GOTRUE_ADMIN_PASSWORD = "CHANGE_ME"
    GOTRUE_DISABLE_SIGNUP = "false"
    GOTRUE_SITE_URL = "appflowy-flutter://"
    GOTRUE_URI_ALLOW_LIST = "**"
    GOTRUE_JWT_SECRET = "CHANGE_ME"
    GOTRUE_JWT_EXP = "7200"
    GOTRUE_DB_DRIVER = "postgres"
    API_EXTERNAL_URL = "https://example.com/gotrue"
    DATABASE_URL = "postgres://user:CHANGE_ME@postgres:5432/appflowy?search_path=auth"
    GOTRUE_SMTP_HOST = "https://example.com"
    GOTRUE_SMTP_PORT = "587"
    GOTRUE_SMTP_USER = "GOTRUE_SMTP_USER_VALUE"
    GOTRUE_SMTP_PASS = "GOTRUE_SMTP_PASS_VALUE"
    GOTRUE_MAILER_URLPATHS_CONFIRMATION = "/verify"
    GOTRUE_MAILER_URLPATHS_INVITE = "/verify"
    GOTRUE_MAILER_URLPATHS_RECOVERY = "/verify"
    GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE = "/verify"
    GOTRUE_SMTP_ADMIN_EMAIL = "admin@example.com"
    GOTRUE_SMTP_MAX_FREQUENCY = "1ns"
    GOTRUE_RATE_LIMIT_EMAIL_SENT = "100"
    GOTRUE_MAILER_AUTOCONFIRM = "true"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "admin_frontend"
category = "app"
subtype = "docker"
docker_image = "appflowyinc/admin_frontend:0.9.149"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APPFLOWY_GOTRUE_BASE_URL = "https://example.com/gotrue"
    APPFLOWY_BASE_URL = "https://example.com"

[[services]]
name = "ai"
category = "app"
subtype = "docker"
docker_image = "appflowyinc/appflowy_ai:0.9.149"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    AI_SERVER_PORT = "5001"
    DEFAULT_AI_MODEL = "gpt-4.1-mini"
    DEFAULT_AI_COMPLETION_MODEL = "gpt-4.1-mini"
    AI_APPFLOWY_HOST = "https://example.com"
    APPFLOWY_GOTRUE_JWT_SECRET = "CHANGE_ME"
    AZURE_OPENAI_API_KEY = "CHANGE_ME"
    AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT_VALUE"
    AZURE_OPENAI_API_VERSION = "AZURE_OPENAI_API_VERSION_VALUE"
    APPFLOWY_S3_ACCESS_KEY = "user"
    APPFLOWY_S3_SECRET_KEY = "CHANGE_ME"
    APPFLOWY_S3_BUCKET = "appflowy"
    APPFLOWY_S3_REGION = "us-east-1"
    AI_DATABASE_URL = "postgres://user:CHANGE_ME@postgres:5432/appflowy"
    AI_REDIS_URL = "redis://redis:6379"
    AI_USE_MINIO = "true"
    AI_MINIO_URL = "http://minio:9000"

[[services]]
name = "appflowy_worker"
category = "app"
subtype = "docker"
docker_image = "appflowyinc/appflowy_worker:0.9.149"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    RUST_LOG = "info"
    APPFLOWY_ENVIRONMENT = "production"
    APPFLOWY_WORKER_ENVIRONMENT = "production"
    APPFLOWY_WORKER_REDIS_URL = "redis://redis:6379"
    APPFLOWY_WORKER_DATABASE_URL = "postgres://user:CHANGE_ME@postgres:5432/appflowy"
    APPFLOWY_WORKER_DATABASE_NAME = "appflowy"
    APPFLOWY_WORKER_IMPORT_TICK_INTERVAL = "30"
    APPFLOWY_S3_USE_MINIO = "true"
    APPFLOWY_S3_MINIO_URL = "http://minio:9000"
    APPFLOWY_S3_ACCESS_KEY = "user"
    APPFLOWY_S3_SECRET_KEY = "CHANGE_ME"
    APPFLOWY_S3_BUCKET = "appflowy"
    APPFLOWY_S3_REGION = "us-east-1"
    APPFLOWY_MAILER_SMTP_HOST = "smtp.gmail.com"
    APPFLOWY_MAILER_SMTP_PORT = "587"
    APPFLOWY_MAILER_SMTP_USERNAME = "notify@appflowy.io"
    APPFLOWY_MAILER_SMTP_EMAIL = "notify@appflowy.io"
    APPFLOWY_MAILER_SMTP_PASSWORD = "email_sender_password"
    APPFLOWY_MAILER_SMTP_TLS_KIND = "none"

[[services]]
name = "minio"
category = "service"
subtype = "s3"
docker_image = "minio/minio:RELEASE.2025-09-07T16-13-09Z"
start_command = "server /data --console-address \":9001\""
source = { type = "docker"  }
  [services.env]
    MINIO_ROOT_USER = "user"
    MINIO_ROOT_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "minio_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 20

[[services]]
name = "postgres"
category = "app"
subtype = "docker"
docker_image = "pgvector/pgvector:pg16"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_DB = "appflowy"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_HOST = "postgres"
    [[services.storage]]
      host = "postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:8.2.2-alpine3.22"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "nginx"
to = "appflowy_cloud"

[[links]]
from = "nginx"
to = "gotrue"

[[links]]
from = "nginx"
to = "admin_frontend"

[[links]]
from = "appflowy_web"
to = "appflowy_cloud"

[[links]]
from = "appflowy_cloud"
to = "gotrue"

[[links]]
from = "appflowy_cloud"
to = "postgres"

[[links]]
from = "appflowy_cloud"
to = "redis"

[[links]]
from = "gotrue"
to = "postgres"

[[links]]
from = "admin_frontend"
to = "gotrue"

[[links]]
from = "admin_frontend"
to = "appflowy_cloud"

[[links]]
from = "ai"
to = "postgres"

[[links]]
from = "appflowy_worker"
to = "postgres"

[[links]]
from = "appflowy_worker"
to = "redis"
