name = "Argilla is a collaboration tool for AI engineers and domain experts who need to build high-quality datasets for their projects."
description = "Argilla is a collaboration tool for AI engineers and domain experts who need to build high-quality datasets for their projects."
category = "stack"
logo = "svgs/argilla.png"
[[services]]
name = "argilla"
category = "app"
subtype = "docker"
docker_image = "argilla/argilla-server:v2.2.0"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_ARGILLA_6900 = ""
    ARGILLA_HOME_PATH = "/var/lib/argilla"
    ARGILLA_ELASTICSEARCH = "http://elasticsearch:9200"
    ARGILLA_DATABASE_URL = "postgresql+asyncpg://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB}"
    ARGILLA_REDIS_URL = "redis://redis:6379/0"
    ARGILLA_AUTH_SECRET_KEY = "${SERVICE_PASSWORD_AUTHSECRET}"
    ARGILLA_ENABLE_TELEMETRY = "${ARGILLA_ENABLE_TELEMETRY:-0}"
    HF_HUB_DISABLE_TELEMETRY = "${HF_HUB_DISABLE_TELEMETRY:-1}"
    REINDEX_DATASETS = "${REINDEX_DATASETS:-1}"
    DEFAULT_USER_ENABLED = "${DEFAULT_USER_ENABLED:-true}"
    USERNAME = "${ARGILLA_USERNAME:-argilla}"
    PASSWORD = "${SERVICE_PASSWORD_ARGILLA}"
    API_KEY = "${SERVICE_PASSWORD_APIKEY}"
    DEFAULT_USER_PASSWORD = "${SERVICE_PASSWORD_ARGILLA}"
    DEFAULT_USER_API_KEY = "${SERVICE_PASSWORD_APIKEY}"
    WORKSPACE = "${WORKSPACE:-default}"
    [[services.storage]]
      host = "argilla-data"
      container = "/var/lib/argilla"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 10

[[services]]
name = "worker"
category = "app"
subtype = "docker"
docker_image = "argilla/argilla-server:v2.2.0"
start_command = "sh -c 'python -m argilla_server worker --num-workers $${BACKGROUND_NUM_WORKERS}'"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    ARGILLA_HOME_PATH = "/var/lib/argilla"
    ARGILLA_ELASTICSEARCH = "http://elasticsearch:9200"
    ARGILLA_DATABASE_URL = "postgresql+asyncpg://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB}"
    ARGILLA_REDIS_URL = "redis://redis:6379/0"
    ARGILLA_AUTH_SECRET_KEY = "${SERVICE_PASSWORD_AUTHSECRET}"
    ARGILLA_ENABLE_TELEMETRY = "${ARGILLA_ENABLE_TELEMETRY:-0}"
    HF_HUB_DISABLE_TELEMETRY = "${HF_HUB_DISABLE_TELEMETRY:-1}"
    REINDEX_DATASETS = "${REINDEX_DATASETS:-1}"
    DEFAULT_USER_ENABLED = "${DEFAULT_USER_ENABLED:-true}"
    USERNAME = "${ARGILLA_USERNAME:-argilla}"
    PASSWORD = "${SERVICE_PASSWORD_ARGILLA}"
    API_KEY = "${SERVICE_PASSWORD_APIKEY}"
    DEFAULT_USER_PASSWORD = "${SERVICE_PASSWORD_ARGILLA}"
    DEFAULT_USER_API_KEY = "${SERVICE_PASSWORD_APIKEY}"
    BACKGROUND_NUM_WORKERS = "${BACKGROUND_NUM_WORKERS:-1}"
    WORKSPACE = "${WORKSPACE:-default}"
    [[services.storage]]
      host = "argilla-data"
      container = "/var/lib/argilla"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 10

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:14"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "${SERVICE_USER_POSTGRES}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    POSTGRES_DB = "${POSTGRES_DB:-argilla}"
    [[services.storage]]
      host = "pg-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "elasticsearch"
category = "search"
subtype = "elasticsearch"
docker_image = "docker.elastic.co/elasticsearch/elasticsearch:8.12.2"
source = { type = "docker"  }
  [services.env]
    node.name = "${NODE_NAME:-elasticsearch}"
    cluster.name = "${CLUSTER_NAME:-es-argilla-local}"
    discovery.type = "${DISCOVERY_TYPE:-single-node}"
    ES_JAVA_OPTS = "${ES_JAVA_OPTS:-\"-Xms512m -Xmx512m\"}"
    cluster.routing.allocation.disk.threshold_enabled = "${CLUSTER_ROUTING_ALLOCATION_DISK_THRESHOLD_ENABLED:-false}"
    xpack.security.enabled = "${XPACK_SECURITY_ENABLED:-false}"
    [[services.storage]]
      host = "elasticsearch-data"
      container = "/usr/share/elasticsearch/data/"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 10

[[links]]
from = "argilla"
to = "elasticsearch"

[[links]]
from = "argilla"
to = "redis"

[[links]]
from = "argilla"
to = "postgres"

[[links]]
from = "worker"
to = "elasticsearch"

[[links]]
from = "worker"
to = "redis"

[[links]]
from = "worker"
to = "postgres"
