name = "Autobase"
description = "Autobase for PostgreSQL® is an open-source alternative to cloud-managed databases (self-hosted DBaaS)."
category = "stack"
logo = "svgs/autobase.svg"

[[services]]
name = "autobase"
category = "app"
subtype = "docker"
docker_image = "autobase/console_ui:2.5.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PG_CONSOLE_AUTHORIZATION_TOKEN = "CHANGE_ME"
    PG_CONSOLE_API_HOST = "autobase-api"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "autobase-db"
category = "app"
subtype = "docker"
docker_image = "autobase/console_db:2.5.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "autobase-db-data"
      container = "/var/lib/postgresql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "autobase-api"
category = "app"
subtype = "docker"
docker_image = "autobase/console_api:2.5.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PG_CONSOLE_DB_HOST = "autobase-db"
    PG_CONSOLE_DB_PASSWORD = "CHANGE_ME"
    PG_CONSOLE_AUTHORIZATION_TOKEN = "CHANGE_ME"
    PG_CONSOLE_ENCRYPTIONKEY = "BASE64_GENERATED"
    PG_CONSOLE_LOGGER_LEVEL = "info"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "autobase"
to = "autobase-api"

[[links]]
from = "autobase-api"
to = "autobase-db"
