name = "Bitcoin Core"
description = "A self-hosted Bitcoin Core full node."
category = "stack"
logo = "svgs/bitcoin.svg"

[[services]]
name = "bitcoin-core"
category = "app"
subtype = "docker"
docker_image = "ruimarinho/bitcoin-core:latest"
start_command = "-datadir=/home/bitcoin/.bitcoin -rpcbind=127.0.0.1 -rpcallowip=127.0.0.1 -rpcuser=${BITCOIN_RPCUSER} -rpcpassword=${SERVICE_PASSWORD_PASSWORD64} -printtoconsole=${BITCOIN_PRINTTOCONSOLE} -txindex=${BITCOIN_TXINDEX} -server=${BITCOIN_SERVER}"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    BITCOIN_RPCUSER = "bitcoinuser"
    BITCOIN_RPCPASSWORD = "${{ secret() }}"
    BITCOIN_PRINTTOCONSOLE = "1"
    BITCOIN_TXINDEX = "1"
    BITCOIN_SERVER = "1"
    [[services.storage]]
      host = "blockchain-data"
      container = "/home/bitcoin/.bitcoin"
