name = "Bluesky Pds"
description = "Bluesky PDS (Personal Data Server)"
category = "stack"
logo = "svgs/bluesky.svg"

[[services]]
name = "pds"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/bluesky-social/pds:0.4.182"
start_command = "sh -c '\n  set -euo pipefail\n  echo \"Installing required packages and pdsadmin...\"\n  apk add --no-cache openssl curl bash jq coreutils gnupg util-linux-misc >/dev/null\n  curl -o /usr/local/bin/pdsadmin.sh https://raw.githubusercontent.com/bluesky-social/pds/main/pdsadmin.sh\n  chmod 700 /usr/local/bin/pdsadmin.sh\n  ln -sf /usr/local/bin/pdsadmin.sh /usr/local/bin/pdsadmin\n  echo \"Creating an empty pds.env file so pdsadmin works...\"\n  touch ${PDS_DATA_DIRECTORY}/pds.env\n  echo \"Launching PDS, enjoy!...\"\n  exec node --enable-source-maps index.js\n'\n"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PDS_HOSTNAME = "${{ RAILDOCK_PUBLIC_DOMAIN }}"
    PDS_JWT_SECRET = "${{ secret() }}"
    PDS_ADMIN_PASSWORD = "${{ secret() }}"
    PDS_ADMIN_EMAIL = "admin@example.com"
    PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX = "${{ secret() }}"
    PDS_DATA_DIRECTORY = "/pds"
    PDS_BLOBSTORE_DISK_LOCATION = "/pds/blocks"
    PDS_BLOB_UPLOAD_LIMIT = "104857600"
    PDS_DID_PLC_URL = "https://plc.directory"
    PDS_EMAIL_FROM_ADDRESS = "admin@example.com"
    PDS_EMAIL_SMTP_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    PDS_BSKY_APP_VIEW_URL = "https://api.bsky.app"
    PDS_BSKY_APP_VIEW_DID = "did:web:api.bsky.app"
    PDS_REPORT_SERVICE_URL = "https://mod.bsky.app/xrpc/com.atproto.moderation.createReport"
    PDS_REPORT_SERVICE_DID = "did:plc:ar7c4by46qjdydhdevvrndac"
    PDS_CRAWLERS = "https://bsky.network"
    LOG_ENABLED = "true"
    [[services.storage]]
      host = "pds-data"
      container = "/pds"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10
