name = "Booklore"
description = "Booklore is an open-source library management system for your digital book collection."
category = "stack"
logo = "svgs/booklore.svg"

[[services]]
name = "booklore"
category = "app"
subtype = "docker"
docker_image = "booklore/booklore:v1.16.5"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    USER_ID = "0"
    GROUP_ID = "0"
    TZ = "UTC"
    DATABASE_USERNAME = "user"
    DATABASE_PASSWORD = "${{ linked.mariadb.MYSQL_PASSWORD }}"
    BOOKLORE_PORT = "80"
    [[services.storage]]
      host = "booklore-data"
      container = "/app/data"
    [[services.storage]]
      host = "booklore-books"
      container = "/books"
    [[services.storage]]
      host = "~/booklore"
      container = "/bookdrop"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
  [services.env]
    MARIADB_USER = "${{ secret() }}"
    MARIADB_PASSWORD = "${{ secret() }}"
    MARIADB_ROOT_PASSWORD = "${{ secret() }}"
    MARIADB_DATABASE = "booklore-db"
    [[services.storage]]
      host = "mariadb-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "booklore"
to = "mariadb"