name = "Bookstack"
description = "BookStack is a simple, self-hosted, easy-to-use platform for organising and storing information"
category = "stack"
logo = "svgs/bookstack.png"

[[services]]
name = "bookstack"
category = "app"
subtype = "docker"
docker_image = "lscr.io/linuxserver/bookstack:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_URL = "https://example.com"
    APP_KEY = "${{ secret() }}"
    PUID = "1000"
    PGID = "1000"
    TZ = "Europe/Berlin"
    DB_HOST = "mariadb"
    DB_PORT = "3306"
    DB_USERNAME = "user"
    DB_PASSWORD = "${{ secret() }}"
    DB_DATABASE = "bookstackapp"
    QUEUE_CONNECTION = "QUEUE_CONNECTION_VALUE"
    GITHUB_APP_ID = "GITHUB_APP_ID_VALUE"
    GITHUB_APP_SECRET = "${{ secret() }}"
    MAIL_DRIVER = "smtp"
    MAIL_HOST = "https://example.com"
    MAIL_PORT = "587"
    MAIL_ENCRYPTION = "tls"
    MAIL_USERNAME = "MAIL_USERNAME_VALUE"
    MAIL_PASSWORD = "${{ secret() }}"
    MAIL_FROM = "MAIL_FROM_VALUE"
    MAIL_FROM_NAME = "BookStack"
    [[services.storage]]
      host = "bookstack-data"
      container = "/config"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "lscr.io/linuxserver/mariadb:latest"
source = { type = "docker"  }
  [services.env]
    PUID = "1000"
    PGID = "1000"
    TZ = "Europe/Berlin"
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "bookstack"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "bookstack-mariadb-data"
      container = "/config"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "bookstack"
to = "mariadb"
