name = "Budge"
description = "A budgeting personal finance app."
category = "stack"
logo = "svgs/budge.png"

[[services]]
name = "budge"
category = "app"
subtype = "docker"
docker_image = "lscr.io/linuxserver/budge:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PUID = "1000"
    PGID = "1000"
    TZ = "Europe/Madrid"
    [[services.storage]]
      host = "budge-config"
      container = "/config"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
