name = "Bugsink"
description = "Self-hosted Error Tracking."
category = "stack"
logo = "svgs/bugsink.svg"

[[services]]
name = "mysql"
category = "database"
subtype = "mysql"
docker_image = "mysql:latest"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "CHANGE_ME"
    MYSQL_DATABASE = "bugsink"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "my-datavolume"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "web"
category = "app"
subtype = "docker"
docker_image = "bugsink/bugsink"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY = "$SERVICE_PASSWORD_64_BUGSINK"
    CREATE_SUPERUSER = "admin:$SERVICE_PASSWORD_BUGSINK"
    BASE_URL = "$SERVICE_URL_BUGSINK"
    DATABASE_URL = "mysql://user:$SERVICE_PASSWORD_BUGSINK@mysql:3306/bugsink"
    BEHIND_HTTPS_PROXY = "True"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "web"
to = "mysql"
