name = "Self-hosted Error Tracking."
description = "Self-hosted Error Tracking."
category = "stack"
logo = "svgs/bugsink.svg"
[[services]]
name = "mysql"
category = "database"
subtype = "mysql"
docker_image = "mysql:latest"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "${SERVICE_PASSWORD_ROOT}"
    MYSQL_DATABASE = "${MYSQL_DATABASE:-bugsink}"
    MYSQL_USER = "${SERVICE_USER_BUGSINK}"
    MYSQL_PASSWORD = "${SERVICE_PASSWORD_BUGSINK}"
    [[services.storage]]
      host = "my-datavolume"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "web"
category = "app"
subtype = "docker"
docker_image = "bugsink/bugsink"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY = "$SERVICE_PASSWORD_64_BUGSINK"
    CREATE_SUPERUSER = "admin:$SERVICE_PASSWORD_BUGSINK"
    SERVICE_URL_BUGSINK_8000 = ""
    BASE_URL = "$SERVICE_URL_BUGSINK"
    DATABASE_URL = "mysql://${SERVICE_USER_BUGSINK}:$SERVICE_PASSWORD_BUGSINK@mysql:3306/${MYSQL_DATABASE:-bugsink}"
    BEHIND_HTTPS_PROXY = "True"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "web"
to = "mysql"
