name = "Bugsink"
description = "Self-hosted Error Tracking."
category = "stack"
logo = "svgs/bugsink.svg"

[[services]]
name = "mysql"
category = "database"
subtype = "mysql"
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "bugsink"
    MYSQL_USER = "${{ secret() }}"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "my-datavolume"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "web"
category = "app"
subtype = "docker"
docker_image = "bugsink/bugsink"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY = "${{ secret() }}"
    CREATE_SUPERUSER = "admin:${{ secret() }}"
    BASE_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    BEHIND_HTTPS_PROXY = "True"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "web"
to = "mysql"