name = "Calcom"
description = "Scheduling infrastructure for everyone."
category = "stack"
logo = "svgs/calcom.svg"

[[services]]
name = "calcom"
category = "app"
subtype = "docker"
docker_image = "calcom.docker.scarf.sh/calcom/cal.com"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NEXT_PUBLIC_LICENSE_CONSENT = "agree"
    NODE_ENV = "production"
    NEXT_PUBLIC_WEBAPP_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    NEXT_PUBLIC_API_V2_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    NEXTAUTH_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    NEXTAUTH_SECRET = "BASE64_GENERATED"
    CALENDSO_ENCRYPTION_KEY = "BASE64_GENERATED"
    DATABASE_HOST = "postgresql"
    DATABASE_DIRECT_URL = "postgresql://user:${{ secret() }}@postgresql/calendso"
    CALCOM_TELEMETRY_DISABLED = "1"
    EMAIL_FROM = "admin@example.com"
    EMAIL_FROM_NAME = "admin@example.com"
    EMAIL_SERVER_HOST = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    EMAIL_SERVER_PORT = "3000"
    EMAIL_SERVER_USER = "admin@example.com"
    EMAIL_SERVER_PASSWORD = "${{ secret() }}"
    NEXT_PUBLIC_APP_NAME = "\"Cal.com\""
    ALLOWED_HOSTNAMES = "[\"https://${{ RAILDOCK_PUBLIC_DOMAIN }}"]"

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "calendso"
    [[services.storage]]
      host = "calcom-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "calcom"
to = "postgresql"