name = "Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks."
description = "Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks."
category = "stack"
logo = "svgs/calibre-web.svg"
[[services]]
name = "calibre-web"
category = "app"
subtype = "docker"
docker_image = "lscr.io/linuxserver/calibre-web:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_CALIBRE_8083 = ""
    PUID = "1000"
    PGID = "1000"
    TZ = "${TZ:-Etc/UTC}"
    DOCKER_MODS = "${DOCKER_MODS:-linuxserver/mods:universal-calibre}"
    [[services.storage]]
      host = "calibre_web_data"
      container = "/config"
    [[services.storage]]
      host = "calibre_library"
      container = "/books"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
