name = "Cap Captcha"
description = "The self-hosted CAPTCHA for the modern web."
category = "stack"
logo = "svgs/cap-captcha.png"

[[services]]
name = "cap"
category = "app"
subtype = "docker"
docker_image = "tiago2/cap:3.0.4"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    ADMIN_KEY = "${{ secret() }}"
    REDIS_URL = "redis://valkey:6379"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5

[[services]]
name = "valkey"
category = "app"
subtype = "docker"
docker_image = "valkey/valkey:9-alpine"
start_command = "valkey-server --save 60 1 --loglevel warning --maxmemory-policy noeviction"
source = { type = "docker"  }
  [services.scaling]
    web = 1
    [[services.storage]]
      host = "valkey-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 3

[[links]]
from = "cap"
to = "valkey"
