name = "Cap"
description = "Cap is the open source alternative to Loom. Lightweight, powerful, and cross-platform. Record and share in seconds."
category = "stack"
logo = "svgs/cap.svg"

[[services]]
name = "cap-web"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/capsoftware/cap-web:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "mysql://$SERVICE_USER_MYSQL:$SERVICE_PASSWORD_MYSQL@cap-db:3306/planetscale"
    WEB_URL = "https://example.com"
    NEXTAUTH_URL = "https://example.com"
    DATABASE_ENCRYPTION_KEY = "${{ secret() }}"
    NEXTAUTH_SECRET = "${{ secret() }}"
    CAP_AWS_ACCESS_KEY = "${CAP_AWS_ACCESS_KEY:?}"
    CAP_AWS_SECRET_KEY = "${CAP_AWS_SECRET_KEY:?}"
    CAP_AWS_BUCKET = "${CAP_AWS_BUCKET:?}"
    CAP_AWS_REGION = "${CAP_AWS_REGION:?}"
    S3_PUBLIC_ENDPOINT = "${S3_PUBLIC_ENDPOINT:?}"
    S3_INTERNAL_ENDPOINT = "${S3_INTERNAL_ENDPOINT:?}"
    NEXT_RUNTIME = "nodejs"
    S3_PATH_STYLE = "true"
    CAP_AWS_ENDPOINT = "${CAP_AWS_ENDPOINT:?}"

[[services]]
name = "cap-db"
category = "database"
subtype = "mysql"
start_command = "--max_connections=1000 --default-authentication-plugin=mysql_native_password"
source = { type = "docker"  }
  [services.env]
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "planetscale"
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_ALLOW_EMPTY_PASSWORD = "yes"
    [[services.storage]]
      host = "cap_db"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 10

[[links]]
from = "cap-web"
to = "cap-db"