name = "Castopod"
description = "Castopod is a free & open-source hosting platform made for podcasters who want engage and interact with their audience."
category = "stack"
logo = "svgs/castopod.svg"

[[services]]
name = "castopod"
category = "app"
subtype = "docker"
docker_image = "castopod/castopod:1.15.4"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CP_DISABLE_HTTPS = "1"
    CP_BASEURL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    CP_ANALYTICS_SALT = "${{ secret() }}"
    CP_CACHE_HANDLER = "redis"
    CP_REDIS_HOST = "redis"
    CP_REDIS_PASSWORD = "${{ linked.redis.REDIS_PASSWORD }}"
    [[services.storage]]
      host = "castopod-media"
      container = "/var/www/castopod/public/media"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "castopod"
    MYSQL_USER = "${{ secret() }}"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "castopod-db"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7.2-alpine"
start_command = "--requirepass ${{ secret() }}"
source = { type = "docker"  }
    [[services.storage]]
      host = "castopod-cache"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "castopod"
to = "mariadb"

[[links]]
from = "castopod"
to = "redis"