name = "Changedetection"
description = "Website change detection monitor and notifications."
category = "stack"
logo = "svgs/changedetection.png"

[[services]]
name = "changedetection"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/dgtlmoon/changedetection.io"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    BASE_URL = "https://example.com"
    PUID = "1000"
    PGID = "1000"
    PLAYWRIGHT_DRIVER_URL = "ws://browser-sockpuppet-chrome:3000"
    HIDE_REFERER = "true"
    FETCH_WORKERS = "10"
    MINIMUM_SECONDS_RECHECK_TIME = "3"
    DISABLE_VERSION_CHECK = "true"
    SCREENSHOT_MAX_HEIGHT = "16000"
    TZ = "UTC"
    LOGGER_LEVEL = "DEBUG"
    [[services.storage]]
      host = "changedetection-data"
      container = "/datastore"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "browser-sockpuppet-chrome"
category = "app"
subtype = "docker"
docker_image = "dgtlmoon/sockpuppetbrowser:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SCREEN_WIDTH = "1920"
    SCREEN_HEIGHT = "1024"
    SCREEN_DEPTH = "16"
    MAX_CONCURRENT_CHROME_PROCESSES = "10"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "changedetection"
to = "browser-sockpuppet-chrome"
