name = "Chatwoot"
description = "Delightful customer relationships at scale."
category = "stack"
logo = "svgs/chatwoot.svg"

[[services]]
name = "chatwoot"
category = "app"
subtype = "docker"
docker_image = "chatwoot/chatwoot:latest"
start_command = "sh -c \"bundle exec rails db:chatwoot_prepare && bundle exec rails s -p 3000 -b 0.0.0.0\""
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY_BASE = "$SERVICE_PASSWORD_CHATWOOT"
    FRONTEND_URL = "https://example.com"
    DEFAULT_LOCALE = "CHATWOOT_DEFAULT_LOCALE_VALUE"
    FORCE_SSL = "false"
    ENABLE_ACCOUNT_SIGNUP = "false"
    REDIS_URL = "redis://default@redis:6379"
    REDIS_PASSWORD = "$SERVICE_PASSWORD_REDIS"
    REDIS_OPENSSL_VERIFY_MODE = "none"
    POSTGRES_DATABASE = "chatwoot"
    POSTGRES_HOST = "postgres"
    POSTGRES_USERNAME = "$SERVICE_USER_POSTGRES"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    RAILS_MAX_THREADS = "5"
    NODE_ENV = "production"
    RAILS_ENV = "production"
    INSTALLATION_ENV = "docker"
    MAILER_SENDER_EMAIL = "admin@example.com"
    SMTP_ADDRESS = "CHATWOOT_SMTP_ADDRESS_VALUE"
    SMTP_AUTHENTICATION = "CHATWOOT_SMTP_AUTHENTICATION_VALUE"
    SMTP_DOMAIN = "CHATWOOT_SMTP_DOMAIN_VALUE"
    SMTP_ENABLE_STARTTLS_AUTO = "CHATWOOT_SMTP_ENABLE_STARTTLS_AUTO_VALUE"
    SMTP_PORT = "3000"
    SMTP_USERNAME = "CHATWOOT_SMTP_USERNAME_VALUE"
    SMTP_PASSWORD = "CHANGE_ME"
    ACTIVE_STORAGE_SERVICE = "local"
    [[services.storage]]
      host = "rails-data"
      container = "/app/storage"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "sidekiq"
category = "app"
subtype = "docker"
docker_image = "chatwoot/chatwoot:latest"
start_command = "bundle exec sidekiq -C config/sidekiq.yml"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY_BASE = "$SERVICE_PASSWORD_CHATWOOT"
    FRONTEND_URL = "https://example.com"
    DEFAULT_LOCALE = "CHATWOOT_DEFAULT_LOCALE_VALUE"
    FORCE_SSL = "false"
    ENABLE_ACCOUNT_SIGNUP = "false"
    REDIS_URL = "redis://default@redis:6379"
    REDIS_PASSWORD = "$SERVICE_PASSWORD_REDIS"
    REDIS_OPENSSL_VERIFY_MODE = "none"
    POSTGRES_DATABASE = "chatwoot"
    POSTGRES_HOST = "postgres"
    POSTGRES_USERNAME = "$SERVICE_USER_POSTGRES"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    RAILS_MAX_THREADS = "5"
    NODE_ENV = "production"
    RAILS_ENV = "production"
    INSTALLATION_ENV = "docker"
    MAILER_SENDER_EMAIL = "admin@example.com"
    SMTP_ADDRESS = "CHATWOOT_SMTP_ADDRESS_VALUE"
    SMTP_AUTHENTICATION = "CHATWOOT_SMTP_AUTHENTICATION_VALUE"
    SMTP_DOMAIN = "CHATWOOT_SMTP_DOMAIN_VALUE"
    SMTP_ENABLE_STARTTLS_AUTO = "CHATWOOT_SMTP_ENABLE_STARTTLS_AUTO_VALUE"
    SMTP_PORT = "3000"
    SMTP_USERNAME = "CHATWOOT_SMTP_USERNAME_VALUE"
    SMTP_PASSWORD = "CHANGE_ME"
    ACTIVE_STORAGE_SERVICE = "local"
    [[services.storage]]
      host = "rails-data"
      container = "/app/storage"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "postgres"
category = "app"
subtype = "docker"
docker_image = "pgvector/pgvector:pg12"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_DB = "chatwoot"
    POSTGRES_USER = "$SERVICE_USER_POSTGRES"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    [[services.storage]]
      host = "postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:alpine"
start_command = "sh -c redis-server --requirepass \"$SERVICE_PASSWORD_REDIS\""
source = { type = "docker"  }
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[links]]
from = "chatwoot"
to = "postgres"

[[links]]
from = "chatwoot"
to = "redis"

[[links]]
from = "sidekiq"
to = "postgres"

[[links]]
from = "sidekiq"
to = "redis"

[[links]]
from = "postgres"
to = "redis"
