name = "Checkmate"
description = "An open source server and websites monitoring application"
category = "stack"
logo = "svgs/checkmate.png"

[[services]]
name = "checkmate"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/bluewave-labs/checkmate-backend-mono-multiarch:v3.2.0"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    UPTIME_APP_API_BASE_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    UPTIME_APP_CLIENT_HOST = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    DB_CONNECTION_STRING = "mongodb://mongodb:27017/uptime_db"
    CLIENT_HOST = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    JWT_SECRET = "${{ secret() }}"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5

[[services]]
name = "mongodb"
category = "database"
subtype = "mongo"
start_command = "mongod --quiet --bind_ip_all"
source = { type = "docker"  }
    [[services.storage]]
      host = "checkmate-mongo"
      container = "/data/db"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[links]]
from = "checkmate"
to = "mongodb"