name = "Chroma"
description = "Chroma is the open-source search and retrieval database for AI applications."
category = "stack"
logo = "svgs/chroma.svg"

[[services]]
name = "chromadb"
category = "app"
subtype = "docker"
docker_image = "chromadb/chroma:1.0.15"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    IS_PERSISTENT = "TRUE"
    PERSIST_DIRECTORY = "/data"
    [[services.storage]]
      host = "chroma-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10
