name = "Cloudreve"
description = "A self-hosted file management and sharing system."
category = "stack"
logo = "svgs/cloudreve.svg"

[[services]]
name = "cloudreve"
category = "app"
subtype = "docker"
docker_image = "cloudreve/cloudreve:4.10.1"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CR_CONF_Database.Type = "postgres"
    CR_CONF_Database.Host = "postgres"
    CR_CONF_Database.User = "user"
    CR_CONF_Database.Password = "CHANGE_ME"
    CR_CONF_Database.Name = "cloudreve-db"
    CR_CONF_Database.Port = "5432"
    CR_CONF_Redis.Server = "redis:6379"
    CR_CONF_Redis.Password = "CHANGE_ME"
    [[services.storage]]
      host = "cloudreve-data"
      container = "/cloudreve/data"
  [services.checks]
    enabled = true
    wait = 20
    timeout = 10

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "cloudreve-db"
    [[services.storage]]
      host = "postgres-data"
      container = "/var/lib/postgresql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
start_command = "redis-server --requirepass ${SERVICE_PASSWORD_REDIS}"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "cloudreve"
to = "postgres"

[[links]]
from = "cloudreve"
to = "redis"