name = "CloudBeaver is a lightweight web application designed for comprehensive data management."
description = "CloudBeaver is a lightweight web application designed for comprehensive data management."
category = "stack"
logo = "svgs/cloudbeaver.svg"
[[services]]
name = "cloudbeaver"
category = "app"
subtype = "docker"
docker_image = "dbeaver/cloudbeaver:24"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_CLOUDBEAVER_8978 = ""
    [[services.storage]]
      host = "cloudbeaver-data"
      container = "/opt/cloudbeaver/workspace"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
