name = "A self-hosted file management and sharing system."
description = "A self-hosted file management and sharing system."
category = "stack"
logo = "svgs/cloudreve.svg"
[[services]]
name = "cloudreve"
category = "app"
subtype = "docker"
docker_image = "cloudreve/cloudreve:4.10.1"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_CLOUDREVE_5212 = ""
    CR_CONF_Database.Type = "postgres"
    CR_CONF_Database.Host = "postgres"
    CR_CONF_Database.User = "${SERVICE_USER_POSTGRES}"
    CR_CONF_Database.Password = "${SERVICE_PASSWORD_POSTGRES}"
    CR_CONF_Database.Name = "${POSTGRES_DB:-cloudreve-db}"
    CR_CONF_Database.Port = "5432"
    CR_CONF_Redis.Server = "redis:6379"
    CR_CONF_Redis.Password = "${SERVICE_PASSWORD_REDIS}"
    [[services.storage]]
      host = "cloudreve-data"
      container = "/cloudreve/data"
  [services.checks]
    enabled = true
    wait = 20
    timeout = 10

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:18-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "${SERVICE_USER_POSTGRES}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    POSTGRES_DB = "${POSTGRES_DB:-cloudreve-db}"
    [[services.storage]]
      host = "postgres-data"
      container = "/var/lib/postgresql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
start_command = "redis-server --requirepass ${SERVICE_PASSWORD_REDIS}"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "cloudreve"
to = "postgres"

[[links]]
from = "cloudreve"
to = "redis"
