name = "Cockpit"
description = "Cockpit is a headless content platform that is lightweight, fast and ready for takeoff."
category = "stack"
logo = "svgs/cockpit.svg"

[[services]]
name = "cockpit"
category = "app"
subtype = "docker"
docker_image = "cockpithq/cockpit:core-latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
    [[services.storage]]
      host = "cockpit-config"
      container = "/var/www/html/config"
    [[services.storage]]
      host = "cockpit-spaces"
      container = "/var/www/html/.spaces"
    [[services.storage]]
      host = "cockpit-storage"
      container = "/var/www/html/storage"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
