name = "Coder"
description = "Coder is an open-source platform for creating and managing cloud development environments on your infrastructure, with the tools and IDEs your developers already love."
category = "stack"
logo = "svgs/coder.svg"

[[services]]
name = "coder"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/coder/coder:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CODER_PG_CONNECTION_URL = "${{ linked.coder-database.DATABASE_URL }}"
    CODER_HTTP_ADDRESS = "0.0.0.0:7080"
    CODER_ACCESS_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "coder-database"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "coder-db"
    [[services.storage]]
      host = "coder-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "coder"
to = "coder-database"

[[links]]
from = "coder-database"
to = "coder"