name = "Coder"
description = "Coder is an open-source platform for creating and managing cloud development environments on your infrastructure, with the tools and IDEs your developers already love."
category = "stack"
logo = "svgs/coder.svg"

[[services]]
name = "coder"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/coder/coder:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CODER_PG_CONNECTION_URL = "postgresql://user:CHANGE_ME@coder-database/coder-db?sslmode=disable"
    CODER_HTTP_ADDRESS = "0.0.0.0:7080"
    CODER_ACCESS_URL = "https://example.com"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "coder-database"
category = "database"
subtype = "postgres"
docker_image = "postgres:16.4-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "coder-db"
    [[services.storage]]
      host = "coder-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "coder"
to = "coder-database"
