name = "Coder is an open-source platform for creating and managing cloud development environments on your infrastructure, with the tools and IDEs your developers already love."
description = "Coder is an open-source platform for creating and managing cloud development environments on your infrastructure, with the tools and IDEs your developers already love."
category = "stack"
logo = "svgs/coder.svg"
[[services]]
name = "coder"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/coder/coder:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_CODER_7080 = ""
    CODER_PG_CONNECTION_URL = "postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@coder-database/${POSTGRES_DB:-coder-db}?sslmode=disable"
    CODER_HTTP_ADDRESS = "0.0.0.0:7080"
    CODER_ACCESS_URL = "${SERVICE_URL_CODER}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "coder-database"
category = "database"
subtype = "postgres"
docker_image = "postgres:16.4-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "${SERVICE_USER_POSTGRES}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    POSTGRES_DB = "${POSTGRES_DB:-coder-db}"
    [[services.storage]]
      host = "coder-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "coder"
to = "coder-database"
