name = "Codimd"
description = "Realtime collaborative markdown notes on all platforms"
category = "stack"
logo = "svgs/codimd.png"

[[services]]
name = "codimd"
category = "app"
subtype = "docker"
docker_image = "nabo.codimd.dev/hackmdio/hackmd:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CMD_DOMAIN = "app.example.com"
    CMD_SESSION_SECRET = "${{ secret() }}"
    CMD_USECDN = "false"
    CMD_DB_URL = "postgres:${{ secret() }}@postgres:5432/codimd-db"
    CMD_EMAIL = "true"
    CMD_ALLOW_EMAIL_REGISTER = "true"
    [[services.storage]]
      host = "uploads_data"
      container = "/home/hackmd/app/public/uploads"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "codimd-db"
    [[services.storage]]
      host = "codimd_postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "codimd"
to = "postgres"