name = "Convex"
description = "Convex is the open-source reactive database for app developers."
category = "stack"
logo = "svgs/convex.svg"

[[services]]
name = "backend"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/get-convex/convex-backend:a9a760ca10399ed42e1b4bb87c78539a235488c7"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    INSTANCE_NAME = "self-hosted-convex"
    INSTANCE_SECRET = "${{ secret() }}"
    CONVEX_CLOUD_ORIGIN = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    CONVEX_SITE_ORIGIN = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    DISABLE_BEACON = "${DISABLE_BEACON:?false}"
    REDACT_LOGS_TO_CLIENT = "${REDACT_LOGS_TO_CLIENT:?false}"
    DO_NOT_REQUIRE_SSL = "${DO_NOT_REQUIRE_SSL:?true}"
    RUST_LOG = "info"
    [[services.storage]]
      host = "data"
      container = "/convex/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[services]]
name = "dashboard"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/get-convex/convex-dashboard:a9a760ca10399ed42e1b4bb87c78539a235488c7"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NEXT_PUBLIC_DEPLOYMENT_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[links]]
from = "dashboard"
to = "backend"
