name = "Convertx"
description = "A self-hosted online file converter. Supports over a thousand different formats."
category = "stack"
logo = "svgs/convertx.png"

[[services]]
name = "convertx"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/c4illin/convertx:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    ACCOUNT_REGISTRATION = "false"
    HTTP_ALLOWED = "true"
    ALLOW_UNAUTHENTICATED = "false"
    AUTO_DELETE_EVERY_N_HOURS = "24"
    JWT_SECRET = "CHANGE_ME"
    [[services.storage]]
      host = "convertx_data"
      container = "/app/data"
