name = "Secure note / file sharing service inspired by PrivNote."
description = "Secure note / file sharing service inspired by PrivNote."
category = "stack"
logo = "svgs/cryptgeon.png"
[[services]]
name = "app"
category = "app"
subtype = "docker"
docker_image = "cupcakearmy/cryptgeon:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_CRYPTGEON_8000 = ""
    SIZE_LIMIT = "${SIZE_LIMIT:-4 MiB}"
    MAX_VIEWS = "${MAX_VIEWS:-100}"
    MAX_EXPIRATION = "${MAX_EXPIRATION:-360}"
    ALLOW_ADVANCED = "${ALLOW_ADVANCED:-true}"
    ALLOW_FILES = "${ALLOW_FILES:-true}"
  [services.checks]
    enabled = true
    wait = 1
    timeout = 3

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
start_command = "redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru"
source = { type = "docker"  }
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "app"
to = "redis"
