name = "Dolibarr"
description = "Dolibarr is a modern software package to manage your organization's activity (contacts, quotes, invoices, orders, stocks, agenda, hr, expense reports, accountancy, ecm, manufacturing, ...)."
category = "stack"
logo = "svgs/dolibarr.png"

[[services]]
name = "dolibarr"
category = "app"
subtype = "docker"
docker_image = "dolibarr/dolibarr:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    WWW_USER_ID = "1000"
    WWW_GROUP_ID = "1000"
    DOLI_DB_HOST = "mariadb"
    DOLI_DB_NAME = "dolibarr-db"
    DOLI_DB_USER = "user"
    DOLI_DB_PASSWORD = "${{ secret() }}"
    DOLI_URL_ROOT = "https://example.com"
    DOLI_ADMIN_LOGIN = "user"
    DOLI_ADMIN_PASSWORD = "${{ secret() }}"
    DOLI_CRON = "0"
    DOLI_INIT_DEMO = "0"
    DOLI_COMPANY_NAME = "MyBigCompany"
    [[services.storage]]
      host = "dolibarr_docs"
      container = "/var/www/documents"
    [[services.storage]]
      host = "dolibarr_custom"
      container = "/var/www/html/custom"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
  [services.env]
    MYSQL_DATABASE = "dolibarr-db"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "dolibarr_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "dolibarr"
to = "mariadb"