name = "Drizzle Gateway"
description = "Free self-hosted Drizzle Studio on steroids"
category = "stack"
logo = "svgs/drizzle.jpeg"

[[services]]
name = "drizzle-gateway"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/drizzle-team/gateway:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    STORE_PATH = "/app"
    MASTERPASS = "$SERVICE_PASSWORD_DRIZZLE"
    [[services.storage]]
      host = "drizzle-gateway-data"
      container = "/app"
