name = "Drupal With Postgresql"
description = "Drupal is a free and open-source web content management system written in PHP and distributed under the GNU General Public License."
category = "stack"
logo = "svgs/drupal.svg"

[[services]]
name = "drupal"
category = "app"
subtype = "docker"
docker_image = "drupal:10-apache"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DB_PASSWORD = "${{ linked.postgres.POSTGRES_PASSWORD }}"
    [[services.storage]]
      host = "drupal_modules"
      container = "/var/www/html/modules"
    [[services.storage]]
      host = "drupal_profiles"
      container = "/var/www/html/profiles"
    [[services.storage]]
      host = "drupal_themes"
      container = "/var/www/html/themes"
    [[services.storage]]
      host = "drupal_sites"
      container = "/var/www/html/sites"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_DB = "postgres"
    POSTGRES_USER = "postgres"
    POSTGRES_PASSWORD = "${{ secret() }}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "drupal"
to = "postgres"