name = "Duplicati"
description = "Duplicati is a backup solution, allowing you to make scheduled backups with encryption."
category = "stack"
logo = "svgs/duplicati.webp"

[[services]]
name = "duplicati"
category = "app"
subtype = "docker"
docker_image = "lscr.io/linuxserver/duplicati:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PUID = "1000"
    PGID = "1000"
    TZ = "Europe/London"
    SETTINGS_ENCRYPTION_KEY = "${{ secret() }}"
    DUPLICATI__WEBSERVICE_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "duplicati-config"
      container = "/config"
    [[services.storage]]
      host = "duplicati-backups"
      container = "/backups"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
