name = "Edgedb"
description = "An open-source database designed as a spiritual successor to SQL and the relational paradigm. Powered by the Postgres query engine under the hood."
category = "stack"
logo = "svgs/edgedb.svg"

[[services]]
name = "edgedb"
category = "app"
subtype = "docker"
docker_image = "edgedb/edgedb"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    EDGEDB_SERVER_ADMIN_UI = "enabled"
    EDGEDB_SERVER_BACKEND_DSN = "postgres:${{ secret() }}@postgresql:5432/edgedb"
    EDGEDB_SERVER_SECURITY = "strict"
    EDGEDB_SERVER_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "edgedb"
    [[services.storage]]
      host = "edgedb-data"
      container = "/dbschema"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "edgedb"
    [[services.storage]]
      host = "edgedb-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "edgedb"
to = "postgresql"