name = "Elasticsearch"
description = "Elasticsearch is free and Open Source, Distributed, RESTful Search Engine."
category = "stack"
logo = "svgs/elasticsearch.svg"

[[services]]
name = "elasticsearch"
category = "search"
subtype = "elasticsearch"
docker_image = "docker.elastic.co/elasticsearch/elasticsearch-wolfi:8.19.0"
source = { type = "docker"  }
  [services.env]
    ELASTIC_PASSWORD = "CHANGE_ME"
    ES_JAVA_OPTS = "-Xms512m -Xmx512m"
    discovery.type = "single-node"
    bootstrap.memory_lock = "true"
    xpack.security.http.ssl.enabled = "false"
    [[services.storage]]
      host = "elasticsearch-data"
      container = "/usr/share/elasticsearch/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 10
