name = "Esphome"
description = "Smart Home Made Simple."
category = "stack"
logo = "svgs/esphome.svg"

[[services]]
name = "esphome"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/esphome/esphome:2025.12.4"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    USERNAME = "user"
    PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "esp_config"
      container = "/config"
