name = "Filebrowser"
description = "FileBrowser is a web-based file manager and file explorer with a user-friendly interface."
category = "stack"
logo = "svgs/filebrowser.svg"

[[services]]
name = "filebrowser"
category = "app"
subtype = "docker"
docker_image = "filebrowser/filebrowser:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
