name = "Firefly"
description = "A personal finances manager that can help you save money."
category = "stack"
logo = "svgs/firefly.svg"

[[services]]
name = "firefly"
category = "app"
subtype = "docker"
docker_image = "fireflyiii/core:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_KEY = "$SERVICE_BASE64_APPKEY"
    DB_HOST = "mysql"
    DB_PORT = "3306"
    DB_CONNECTION = "mysql"
    DB_DATABASE = "firefly"
    DB_USERNAME = "$SERVICE_USER_MYSQL"
    DB_PASSWORD = "$SERVICE_PASSWORD_MYSQL"
    STATIC_CRON_TOKEN = "$SERVICE_BASE64_CRONTOKEN"
    TRUSTED_PROXIES = "*"
    [[services.storage]]
      host = "firefly-upload"
      container = "/var/www/html/storage/upload"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "mysql"
category = "database"
subtype = "mariadb"
  [services.env]
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "firefly"
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "firefly-mysql-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "cron"
category = "app"
subtype = "docker"
docker_image = "alpine"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    STATIC_CRON_TOKEN = "$SERVICE_BASE64_CRONTOKEN"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[links]]
from = "firefly"
to = "mysql"

[[links]]
from = "cron"
to = "mysql"