name = "Flowise"
description = "Flowise is an open source low-code tool for developers to build customized LLM orchestration flows & AI agents."
category = "stack"
logo = "svgs/flowise.png"

[[services]]
name = "flowise"
category = "app"
subtype = "docker"
docker_image = "flowiseai/flowise:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DEBUG = "false"
    DISABLE_FLOWISE_TELEMETRY = "true"
    PORT = "3001"
    DATABASE_PATH = "/root/.flowise"
    APIKEY_PATH = "/root/.flowise"
    SECRETKEY_PATH = "/root/.flowise"
    LOG_PATH = "/root/.flowise/logs"
    BLOB_STORAGE_PATH = "/root/.flowise/storage"
    FLOWISE_USERNAME = "user"
    FLOWISE_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "flowise-data"
      container = "/root/.flowise"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5
