name = "Formbricks"
description = "Open Source Survey Platform"
category = "stack"
logo = "svgs/formbricks.png"

[[services]]
name = "formbricks"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/formbricks/formbricks:4.5.0"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    WEBAPP_URL = "$SERVICE_URL_FORMBRICKS"
    DATABASE_URL = "postgres://$SERVICE_USER_POSTGRESQL:$SERVICE_PASSWORD_POSTGRESQL@postgresql:5432/formbricks"
    POSTGRES_PASSWORD = "CHANGE_ME"
    NEXTAUTH_SECRET = "$SERVICE_BASE64_NEXTAUTH"
    NEXTAUTH_URL = "$SERVICE_URL_FORMBRICKS"
    ENCRYPTION_KEY = "$SERVICE_BASE64_ENCRYPTION"
    CRON_SECRET = "$SERVICE_BASE64_CRON"
    ENTERPRISE_LICENSE_KEY = "CHANGE_ME"
    MAIL_FROM = "test@example.com"
    SMTP_HOST = "test.example.com"
    SMTP_PORT = "587"
    SMTP_USER = "test"
    SMTP_PASSWORD = "test"
    SMTP_SECURE_ENABLED = "0"
    SMTP_REJECT_UNAUTHORIZED_TLS = "1"
    SHORT_URL_BASE = "https://example.com"
    EMAIL_VERIFICATION_DISABLED = "1"
    PASSWORD_RESET_DISABLED = "1"
    EMAIL_AUTH_DISABLED = "0"
    INVITE_DISABLED = "0"
    ASSET_PREFIX_URL = "https://example.com"
    UNSPLASH_ACCESS_KEY = "CHANGE_ME"
    GITHUB_ID = "GITHUB_ID_VALUE"
    GITHUB_SECRET = "CHANGE_ME"
    GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID_VALUE"
    GOOGLE_CLIENT_SECRET = "CHANGE_ME"
    AZUREAD_CLIENT_ID = "AZUREAD_CLIENT_ID_VALUE"
    AZUREAD_CLIENT_SECRET = "CHANGE_ME"
    AZUREAD_TENANT_ID = "AZUREAD_TENANT_ID_VALUE"
    OIDC_CLIENT_ID = "OIDC_CLIENT_ID_VALUE"
    OIDC_CLIENT_SECRET = "CHANGE_ME"
    OIDC_ISSUER = "OIDC_ISSUER_VALUE"
    OIDC_DISPLAY_NAME = "OIDC_DISPLAY_NAME_VALUE"
    OIDC_SIGNING_ALGORITHM = "OIDC_SIGNING_ALGORITHM_VALUE"
    NOTION_OAUTH_CLIENT_ID = "NOTION_OAUTH_CLIENT_ID_VALUE"
    NOTION_OAUTH_CLIENT_SECRET = "CHANGE_ME"
    GOOGLE_SHEETS_CLIENT_ID = "GOOGLE_SHEETS_CLIENT_ID_VALUE"
    GOOGLE_SHEETS_CLIENT_SECRET = "CHANGE_ME"
    GOOGLE_SHEETS_REDIRECT_URL = "https://example.com"
    AIRTABLE_CLIENT_ID = "AIRTABLE_CLIENT_ID_VALUE"
    SLACK_CLIENT_ID = "SLACK_CLIENT_ID_VALUE"
    SLACK_CLIENT_SECRET = "CHANGE_ME"
    PRIVACY_URL = "https://example.com"
    TERMS_URL = "https://example.com"
    IMPRINT_URL = "https://example.com"
    RATE_LIMITING_DISABLED = "0"
    OPENTELEMETRY_LISTENER_URL = "https://example.com"
    REDIS_URL = "redis://valkey:6379"
    DEFAULT_ORGANIZATION_ID = "DEFAULT_ORGANIZATION_ID_VALUE"
    DEFAULT_ORGANIZATION_ROLE = "owner"
    S3_ACCESS_KEY = "$SERVICE_USER_MINIO"
    S3_SECRET_KEY = "CHANGE_ME"
    S3_REGION = "us-east-1"
    S3_BUCKET_NAME = "formbricks"
    S3_ENDPOINT_URL = "$MINIO_SERVER_URL"
    S3_FORCE_PATH_STYLE = "1"
    [[services.storage]]
      host = "formbricks-uploads"
      container = "/apps/web/uploads/"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "postgresql"
category = "app"
subtype = "docker"
docker_image = "pgvector/pgvector:pg16"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "formbricks"
    [[services.storage]]
      host = "formbricks-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "valkey"
category = "app"
subtype = "docker"
docker_image = "valkey/valkey:8-alpine"
start_command = "valkey-server --appendonly yes"
source = { type = "docker"  }
  [services.scaling]
    web = 1
    [[services.storage]]
      host = "formbricks-valkey"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "minio"
category = "service"
subtype = "s3"
docker_image = "ghcr.io/coollabsio/minio:RELEASE.2025-10-15T17-29-55Z"
start_command = "server /data --console-address \":9001\""
source = { type = "docker"  }
  [services.env]
    MINIO_SERVER_URL = "$MINIO_SERVER_URL"
    MINIO_BROWSER_REDIRECT_URL = "$MINIO_BROWSER_REDIRECT_URL"
    MINIO_ROOT_USER = "$SERVICE_USER_MINIO"
    MINIO_ROOT_PASSWORD = "$SERVICE_PASSWORD_MINIO"
    [[services.storage]]
      host = "formbricks-minio-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "formbricks"
to = "postgresql"

[[links]]
from = "formbricks"
to = "valkey"

[[links]]
from = "formbricks"
to = "minio"

[[links]]
from = "minio-init"
to = "minio"
