name = "Foundryvtt"
description = "Foundry Virtual Tabletop is a self-hosted & modern roleplaying platform"
category = "stack"
logo = "svgs/foundryvtt.png"

[[services]]
name = "foundryvtt"
category = "app"
subtype = "docker"
docker_image = "felddy/foundryvtt:release"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    FOUNDRY_USERNAME = "FOUNDRY_USERNAME_VALUE"
    FOUNDRY_PASSWORD = "${{ secret() }}"
    FOUNDRY_RELEASE_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    FOUNDRY_LICENSE_KEY = "${{ secret() }}"
    FOUNDRY_ADMIN_KEY = "atropos"
    FOUNDRY_HOSTNAME = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    FOUNDRY_ROUTE_PREFIX = "FOUNDRY_ROUTE_PREFIX_VALUE"
    FOUNDRY_PROXY_PORT = "80"
    FOUNDRY_PROXY_SSL = "true"
    FOUNDRY_AWS_CONFIG = "FOUNDRY_AWS_CONFIG_VALUE"
    FOUNDRY_LANGUAGE = "en.core"
    FOUNDRY_CSS_THEME = "foundry"
    FOUNDRY_MINIFY_STATIC_FILES = "true"
    FOUNDRY_WORLD = "FOUNDRY_WORLD_VALUE"
    FOUNDRY_TELEMETRY = "false"
    TIMEZONE = "UTC"
    CONTAINER_CACHE = "/data/container_cache"
    [[services.storage]]
      host = "${FOUNDRY_DATA:-/data/foundryvtt}"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5
