name = "Freescout"
description = "FreeScout is the super lightweight and powerful free open source help desk and shared inbox written in PHP (Laravel framework)."
category = "stack"
logo = "svgs/freescout.png"

[[services]]
name = "freescout"
category = "app"
subtype = "docker"
docker_image = "tiredofit/freescout:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DB_HOST = "mariadb"
    DB_NAME = "freescout"
    DB_USER = "user"
    DB_PASS = "${{ secret() }}"
    SITE_URL = "https://example.com"
    ADMIN_EMAIL = "admin@example.com"
    ADMIN_PASS = "${{ secret() }}"
    DISPLAY_ERRORS = "FALSE"
    TIMEZONE = "UTC"
    [[services.storage]]
      host = "freescout-data"
      container = "/data"
    [[services.storage]]
      host = "freescout-logs"
      container = "/www/logs"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
  [services.env]
    MARIADB_ROOT_PASSWORD = "${{ secret() }}"
    MARIADB_DATABASE = "MARIADB_DATABASE_VALUE"
    MARIADB_USER = "user"
    MARIADB_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "mariadb-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "freescout"
to = "mariadb"