name = "FreeScout is the super lightweight and powerful free open source help desk and shared inbox written in PHP (Laravel framework)."
description = "FreeScout is the super lightweight and powerful free open source help desk and shared inbox written in PHP (Laravel framework)."
category = "stack"
logo = "svgs/freescout.png"
[[services]]
name = "freescout"
category = "app"
subtype = "docker"
docker_image = "tiredofit/freescout:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_FREESCOUT_80 = ""
    DB_HOST = "mariadb"
    DB_NAME = "${MARIADB_DATABASE:-freescout}"
    DB_USER = "${SERVICE_USER_MARIADB:-freescout}"
    DB_PASS = "${SERVICE_PASSWORD_MARIADB}"
    SITE_URL = "${SERVICE_URL_FREESCOUT}"
    ADMIN_EMAIL = "${ADMIN_EMAIL:-admin@example.com}"
    ADMIN_PASS = "${SERVICE_PASSWORD_ADMIN}"
    DISPLAY_ERRORS = "${DISPLAY_ERRORS:-FALSE}"
    TIMEZONE = "${TIMEZONE:-UTC}"
    [[services.storage]]
      host = "freescout-data"
      container = "/data"
    [[services.storage]]
      host = "freescout-logs"
      container = "/www/logs"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb"
source = { type = "docker"  }
  [services.env]
    MARIADB_ROOT_PASSWORD = "${SERVICE_PASSWORD_ROOT}"
    MARIADB_DATABASE = "${MARIADB_DATABASE}"
    MARIADB_USER = "${SERVICE_USER_MARIADB}"
    MARIADB_PASSWORD = "${SERVICE_PASSWORD_MARIADB}"
    [[services.storage]]
      host = "mariadb-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "freescout"
to = "mariadb"
