name = "Getoutline"
description = "Your team’s knowledge base"
category = "stack"
logo = "svgs/getoutline.jpeg"

[[services]]
name = "outline"
category = "app"
subtype = "docker"
docker_image = "docker.getoutline.com/outlinewiki/outline:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NODE_ENV = "production"
    SECRET_KEY = "SERVICE_HEX_64_OUTLINE_VALUE"
    UTILS_SECRET = "${{ secret() }}"
    DATABASE_URL = "postgres:${{ secret() }}@postgres:5432/outline"
    REDIS_URL = "redis://:CHANGE_ME@redis:6379"
    URL = "https://example.com"
    PORT = "3000"
    FILE_STORAGE = "local"
    FILE_STORAGE_LOCAL_ROOT_DIR = "/var/lib/outline/data"
    FILE_STORAGE_UPLOAD_MAX_SIZE = "2000"
    FILE_STORAGE_IMPORT_MAX_SIZE = "100"
    FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE = "3000"
    AWS_ACCESS_KEY_ID = "${{ secret() }}"
    AWS_SECRET_ACCESS_KEY = "${{ secret() }}"
    AWS_REGION = "AWS_REGION_VALUE"
    AWS_S3_ACCELERATE_URL = "https://example.com"
    AWS_S3_UPLOAD_BUCKET_URL = "https://example.com"
    AWS_S3_UPLOAD_BUCKET_NAME = "AWS_S3_UPLOAD_BUCKET_NAME_VALUE"
    AWS_S3_FORCE_PATH_STYLE = "true"
    AWS_S3_ACL = "private"
    SLACK_CLIENT_ID = "SLACK_CLIENT_ID_VALUE"
    SLACK_CLIENT_SECRET = "${{ secret() }}"
    GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID_VALUE"
    GOOGLE_CLIENT_SECRET = "${{ secret() }}"
    AZURE_CLIENT_ID = "AZURE_CLIENT_ID_VALUE"
    AZURE_CLIENT_SECRET = "${{ secret() }}"
    AZURE_RESOURCE_APP_ID = "AZURE_RESOURCE_APP_ID_VALUE"
    OIDC_CLIENT_ID = "OIDC_CLIENT_ID_VALUE"
    OIDC_CLIENT_SECRET = "${{ secret() }}"
    OIDC_AUTH_URI = "OIDC_AUTH_URI_VALUE"
    OIDC_TOKEN_URI = "${{ secret() }}"
    OIDC_USERINFO_URI = "OIDC_USERINFO_URI_VALUE"
    OIDC_LOGOUT_URI = "OIDC_LOGOUT_URI_VALUE"
    OIDC_USERNAME_CLAIM = "OIDC_USERNAME_CLAIM_VALUE"
    OIDC_DISPLAY_NAME = "OIDC_DISPLAY_NAME_VALUE"
    OIDC_SCOPES = "OIDC_SCOPES_VALUE"
    GITHUB_CLIENT_ID = "GITHUB_CLIENT_ID_VALUE"
    GITHUB_CLIENT_SECRET = "${{ secret() }}"
    GITHUB_APP_NAME = "GITHUB_APP_NAME_VALUE"
    GITHUB_APP_ID = "GITHUB_APP_ID_VALUE"
    GITHUB_APP_PRIVATE_KEY = "${{ secret() }}"
    DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID_VALUE"
    DISCORD_CLIENT_SECRET = "${{ secret() }}"
    DISCORD_SERVER_ID = "DISCORD_SERVER_ID_VALUE"
    DISCORD_SERVER_ROLES = "DISCORD_SERVER_ROLES_VALUE"
    PGSSLMODE = "disable"
    FORCE_HTTPS = "true"
    SMTP_HOST = "https://example.com"
    SMTP_PORT = "3000"
    SMTP_USERNAME = "SMTP_USERNAME_VALUE"
    SMTP_PASSWORD = "${{ secret() }}"
    SMTP_FROM_EMAIL = "admin@example.com"
    SMTP_REPLY_EMAIL = "admin@example.com"
    SMTP_TLS_CIPHERS = "SMTP_TLS_CIPHERS_VALUE"
    SMTP_SECURE = "SMTP_SECURE_VALUE"
    SMTP_NAME = "SMTP_NAME_VALUE"
    [[services.storage]]
      host = "storage-data"
      container = "/var/lib/outline/data"

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:alpine"
start_command = "redis-server --requirepass ${SERVICE_PASSWORD_64_REDIS}"
source = { type = "docker"  }
  [services.env]
    REDIS_PASSWORD = "${{ secret() }}"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 30

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:12-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "outline"
    [[services.storage]]
      host = "database-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 20

[[links]]
from = "outline"
to = "postgres"

[[links]]
from = "outline"
to = "redis"
