name = "Github Runner"
description = "A GitHub Actions runner for Docker"
category = "stack"
logo = "svgs/github-runner.png"

[[services]]
name = "runner"
category = "app"
subtype = "docker"
docker_image = "myoung34/github-runner:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    REPO_URL = "https://example.com"
    RUNNER_NAME_PREFIX = "coolify-runner"
    RUNNER_NAME_SUFFIX = "false"
    ACCESS_TOKEN = "${{ secret() }}"
    RUNNER_WORKDIR = "/runner/work"
    RUNNER_SCOPE = "repo"
    LABELS = "default"
    ORG_NAME = "ORG_NAME_VALUE"
    [[services.storage]]
      host = "runner-data"
      container = "/runner"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10
