name = "Glances"
description = "An Eye on your system"
category = "stack"
logo = "svgs/glances.png"

[[services]]
name = "glances"
category = "app"
subtype = "docker"
docker_image = "nicolargo/glances:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    GLANCES_OPT = "-w"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
