name = "Glpi"
description = "GLPI (Gestionnaire Libre de Parc Informatique) is a free, open-source IT Service Management (ITSM) platform used for IT asset management, helpdesk, and service desk operations."
category = "stack"
logo = "svgs/glpi.svg"

[[services]]
name = "glpi"
category = "app"
subtype = "docker"
docker_image = "glpi/glpi:11"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    GLPI_DB_HOST = "glpi-db"
    GLPI_DB_PORT = "3306"
    GLPI_DB_NAME = "glpi-db"
    GLPI_DB_USER = "user"
    GLPI_DB_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "glpi-data"
      container = "/var/glpi"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "glpi-db"
category = "database"
subtype = "mysql"
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "glpi-db"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "mysql-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "glpi"
to = "glpi-db"