name = "Lightweight web analytics platform."
description = "Lightweight web analytics platform."
category = "stack"
logo = "svgs/goatcounter.svg"
[[services]]
name = "goatcounter"
category = "app"
subtype = "docker"
docker_image = "arp242/goatcounter:2.7"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_GOATCOUNTER_8080 = ""
    [[services.storage]]
      host = "goatcounter-data"
      container = "/home/goatcounter/goatcounter-data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5
