name = "Gowa"
description = "Golang WhatsApp - Built with Go for efficient memory use"
category = "stack"
logo = "svgs/gowa.svg"

[[services]]
name = "gowa"
category = "app"
subtype = "docker"
docker_image = "aldinokemal2104/go-whatsapp-web-multidevice:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_BASIC_AUTH = "user:${{ secret() }}"
    APP_PORT = "3000"
    APP_DEBUG = "false"
    APP_ACCOUNT_VALIDATION = "false"
    WHATSAPP_WEBHOOK = "WHATSAPP_WEBHOOK_VALUE"
    WHATSAPP_WEBHOOK_SECRET = "${{ secret() }}"
    [[services.storage]]
      host = "gowa_data"
      container = "/app/storages"
