name = "Grafana"
description = "Grafana is the open source analytics & monitoring solution for every database."
category = "stack"
logo = "svgs/grafana.svg"

[[services]]
name = "grafana"
category = "app"
subtype = "docker"
docker_image = "grafana/grafana-oss"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    GF_SERVER_ROOT_URL = "https://example.com"
    GF_SERVER_DOMAIN = "app.example.com"
    GF_SECURITY_ADMIN_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "grafana-data"
      container = "/var/lib/grafana"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
