name = "Homebox"
description = "Homebox is the inventory and organization system built for the Home User."
category = "stack"
logo = "svgs/homebox.svg"

[[services]]
name = "homebox"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/sysadminsmedia/homebox:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    HBOX_OPTIONS_ALLOW_REGISTRATION = "false"
    HBOX_LOG_LEVEL = "info"
    HBOX_LOG_FORMAT = "text"
    HBOX_WEB_MAX_UPLOAD_SIZE = "10"
    HBOX_MAILER_HOST = "https://example.com"
    HBOX_MAILER_PORT = "587"
    HBOX_MAILER_USERNAME = "HBOX_MAILER_USERNAME_VALUE"
    HBOX_MAILER_PASSWORD = "${{ secret() }}"
    HBOX_MAILER_FROM = "HBOX_MAILER_FROM_VALUE"
    [[services.storage]]
      host = "homebox-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5
