name = "Homepage"
description = "A modern, fully static, fast, secure fully proxied, highly customizable application dashboard"
category = "stack"
logo = "svgs/homepage.png"

[[services]]
name = "homepage"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/gethomepage/homepage:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    HOMEPAGE_VAR_BASE = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
