name = "Hoppscotch"
description = "The Open Source API Development Platform"
category = "stack"
logo = "svgs/hoppscotch.png"

[[services]]
name = "backend"
category = "app"
subtype = "docker"
docker_image = "hoppscotch/hoppscotch:2026.2.1"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    VITE_ALLOWED_AUTH_PROVIDERS = "GOOGLE,GITHUB,MICROSOFT,EMAIL"
    DATA_ENCRYPTION_KEY = "BASE64_GENERATED"
    WHITELISTED_ORIGINS = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    MAILER_USE_CUSTOM_CONFIGS = "true"
    VITE_BASE_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    VITE_SHORTCODE_BASE_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    VITE_ADMIN_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    VITE_BACKEND_GQL_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    VITE_BACKEND_WS_URL = "wss://${{ RAILDOCK_PUBLIC_DOMAIN }}/backend/graphql"
    VITE_BACKEND_API_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    VITE_APP_TOS_LINK = "https://docs.hoppscotch.io/support/terms"
    VITE_APP_PRIVACY_POLICY_LINK = "https://docs.hoppscotch.io/support/privacy"
    ENABLE_SUBPATH_BASED_ACCESS = "true"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "hoppscotch-db"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "hoppscotch"
    [[services.storage]]
      host = "postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[services]]
name = "db-migration"
category = "app"
subtype = "docker"
docker_image = "hoppscotch/hoppscotch:2026.2.1"
start_command = "pnpx prisma migrate deploy"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "postgres:${{ secret() }}@hoppscotch-db:5432/hoppscotch"

[[links]]
from = "backend"
to = "db-migration"

[[links]]
from = "db-migration"
to = "hoppscotch-db"

[[links]]
from = "backend"
to = "hoppscotch-db"