name = "Hoppscotch"
description = "The Open Source API Development Platform"
category = "stack"
logo = "svgs/hoppscotch.png"

[[services]]
name = "backend"
category = "app"
subtype = "docker"
docker_image = "hoppscotch/hoppscotch:2026.2.1"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    VITE_ALLOWED_AUTH_PROVIDERS = "GOOGLE,GITHUB,MICROSOFT,EMAIL"
    DATABASE_URL = "postgresql://user:CHANGE_ME@hoppscotch-db:5432/POSTGRES_DB_VALUE"
    DATA_ENCRYPTION_KEY = "BASE64_GENERATED"
    WHITELISTED_ORIGINS = "https://example.com/backend,https://example.com,https://example.com/admin"
    MAILER_USE_CUSTOM_CONFIGS = "true"
    VITE_BASE_URL = "https://example.com"
    VITE_SHORTCODE_BASE_URL = "https://example.com"
    VITE_ADMIN_URL = "https://example.com/admin"
    VITE_BACKEND_GQL_URL = "https://example.com/backend/graphql"
    VITE_BACKEND_WS_URL = "wss://app.example.com/backend/graphql"
    VITE_BACKEND_API_URL = "https://example.com/backend/v1"
    VITE_APP_TOS_LINK = "https://docs.hoppscotch.io/support/terms"
    VITE_APP_PRIVACY_POLICY_LINK = "https://docs.hoppscotch.io/support/privacy"
    ENABLE_SUBPATH_BASED_ACCESS = "true"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "hoppscotch-db"
category = "database"
subtype = "postgres"
docker_image = "postgres:15"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "hoppscotch"
    [[services.storage]]
      host = "postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[services]]
name = "db-migration"
category = "app"
subtype = "docker"
docker_image = "hoppscotch/hoppscotch:2026.2.1"
start_command = "pnpx prisma migrate deploy"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "hoppscotch"
    DATABASE_URL = "postgres://user:CHANGE_ME@hoppscotch-db:5432/hoppscotch"

[[links]]
from = "backend"
to = "db-migration"

[[links]]
from = "db-migration"
to = "hoppscotch-db"

[[links]]
from = "backend"
to = "hoppscotch-db"
