name = "Infisical"
description = "Infisical is the open source secret management platform that developers use to centralize their application configuration and secrets like API keys and database credentials."
category = "stack"
logo = "svgs/infisical.png"

[[services]]
name = "backend"
category = "app"
subtype = "docker"
docker_image = "infisical/infisical:v0.154.6"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SITE_URL = "https://example.com"
    NODE_ENV = "production"
    ENCRYPTION_KEY = "${{ secret() }}"
    AUTH_SECRET = "${{ secret() }}"
    SMTP_HOST = "https://example.com"
    SMTP_USERNAME = "SMTP_USERNAME_VALUE"
    SMTP_PASSWORD = "${{ secret() }}"
    SMTP_PORT = "3000"
    SMTP_FROM_ADDRESS = "SMTP_FROM_ADDRESS_VALUE"
    SMTP_FROM_NAME = "SMTP_FROM_NAME_VALUE"
    INF_APP_CONNECTION_GITHUB_APP_CLIENT_ID = "INF_APP_CONNECTION_GITHUB_APP_CLIENT_ID_VALUE"
    INF_APP_CONNECTION_GITHUB_APP_CLIENT_SECRET = "${{ secret() }}"
    INF_APP_CONNECTION_GITHUB_APP_SLUG = "INF_APP_CONNECTION_GITHUB_APP_SLUG_VALUE"
    INF_APP_CONNECTION_GITHUB_APP_ID = "INF_APP_CONNECTION_GITHUB_APP_ID_VALUE"
    INF_APP_CONNECTION_GITHUB_APP_PRIVATE_KEY = "${{ secret() }}"
    DB_CONNECTION_URI = "postgres:${{ secret() }}@db:5432/POSTGRES_DB_VALUE"
    REDIS_URL = "redis://redis:6379"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7"
source = { type = "docker"  }
  [services.env]
    ALLOW_EMPTY_PASSWORD = "yes"
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "db"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "infisical"
    [[services.storage]]
      host = "pg_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "backend"
to = "redis"

[[links]]
from = "backend"
to = "db"