name = "Invoice Ninja"
description = "The leading open-source invoicing platform"
category = "stack"
logo = "svgs/invoiceninja.png"

[[services]]
name = "invoice-ninja"
category = "app"
subtype = "docker"
docker_image = "invoiceninja/invoiceninja:5"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_NAME = "\"Invoice Ninja\""
    APP_ENV = "production"
    APP_URL = "https://example.com"
    APP_KEY = "base64:SERVICE_REALBASE64_INVOICENINJA_VALUE"
    APP_DEBUG = "false"
    REQUIRE_HTTPS = "false"
    PHANTOMJS_PDF_GENERATION = "false"
    PDF_GENERATOR = "hosted_ninja"
    TRUSTED_PROXIES = "*"
    CACHE_DRIVER = "redis"
    QUEUE_CONNECTION = "redis"
    SESSION_DRIVER = "redis"
    REDIS_HOST = "redis"
    REDIS_PASSWORD = "CHANGE_ME"
    REDIS_PORT = "6379"
    DB_HOST = "mariadb"
    DB_PORT = "3306"
    DB_DATABASE = "invoiceninja"
    DB_USERNAME = "user"
    DB_PASSWORD = "CHANGE_ME"
    IN_USER_EMAIL = "admin@example.com"
    IN_PASSWORD = "CHANGE_ME"
    MAIL_MAILER = "log"
    MAIL_HOST = "https://example.com"
    MAIL_PORT = "3000"
    MAIL_USERNAME = "MAIL_USERNAME_VALUE"
    MAIL_PASSWORD = "CHANGE_ME"
    MAIL_ENCRYPTION = "MAIL_ENCRYPTION_VALUE"
    MAIL_FROM_ADDRESS = "MAIL_FROM_ADDRESS_VALUE"
    MAIL_FROM_NAME = "MAIL_FROM_NAME_VALUE"
    AWS_ACCESS_KEY_ID = "CHANGE_ME"
    AWS_SECRET_ACCESS_KEY = "CHANGE_ME"
    AWS_DEFAULT_REGION = "AWS_DEFAULT_REGION_VALUE"
    AWS_BUCKET = "AWS_BUCKET_VALUE"
    AWS_URL = "https://example.com"
    AWS_ENDPOINT = "AWS_ENDPOINT_VALUE"
    NORDIGEN_SECRET_ID = "CHANGE_ME"
    NORDIGEN_SECRET_KEY = "CHANGE_ME"
    IS_DOCKER = "true"
    SCOUT_DRIVER = "SCOUT_DRIVER_VALUE"
    LICENSE_KEY = "CHANGE_ME"
    [[services.storage]]
      host = "invoice-ninja-public"
      container = "/var/www/app/public"
    [[services.storage]]
      host = "invoice-ninja-storage"
      container = "/var/www/app/storage"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:11"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "CHANGE_ME"
    MYSQL_DATABASE = "invoiceninja"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "mariadb-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7.4-alpine"
start_command = "redis-server --requirepass ${SERVICE_PASSWORD_REDIS}"
source = { type = "docker"  }
  [services.env]
    REDIS_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "invoice-ninja-redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "invoice-ninja"
to = "mariadb"
