name = "The leading open-source invoicing platform"
description = "The leading open-source invoicing platform"
category = "stack"
logo = "svgs/invoiceninja.png"
[[services]]
name = "invoice-ninja"
category = "app"
subtype = "docker"
docker_image = "invoiceninja/invoiceninja:5"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_INVOICENINJA = ""
    APP_NAME = "${APP_NAME:-\"Invoice Ninja\"}"
    APP_ENV = "${APP_ENV:-production}"
    APP_URL = "${SERVICE_URL_INVOICENINJA}"
    APP_KEY = "base64:${SERVICE_REALBASE64_INVOICENINJA}"
    APP_DEBUG = "${APP_DEBUG:-false}"
    REQUIRE_HTTPS = "${REQUIRE_HTTPS:-false}"
    PHANTOMJS_PDF_GENERATION = "${PHANTOMJS_PDF_GENERATION:-false}"
    PDF_GENERATOR = "${PDF_GENERATOR:-hosted_ninja}"
    TRUSTED_PROXIES = "${TRUSTED_PROXIES:-*}"
    CACHE_DRIVER = "redis"
    QUEUE_CONNECTION = "${QUEUE_CONNECTION:-redis}"
    SESSION_DRIVER = "redis"
    REDIS_HOST = "${REDIS_HOST:-redis}"
    REDIS_PASSWORD = "${SERVICE_PASSWORD_REDIS}"
    REDIS_PORT = "${REDIS_PORT:-6379}"
    DB_HOST = "${DB_HOST:-mariadb}"
    DB_PORT = "${DB_PORT:-3306}"
    DB_DATABASE = "${DB_DATABASE:-invoiceninja}"
    DB_USERNAME = "${SERVICE_USER_MARIADB}"
    DB_PASSWORD = "${SERVICE_PASSWORD_MARIADB}"
    IN_USER_EMAIL = "${IN_USER_EMAIL:-admin@example.com}"
    IN_PASSWORD = "${SERVICE_PASSWORD_INVOICENINJAUSER}"
    MAIL_MAILER = "${MAIL_MAILER:-log}"
    MAIL_HOST = "${MAIL_HOST}"
    MAIL_PORT = "${MAIL_PORT}"
    MAIL_USERNAME = "${MAIL_USERNAME}"
    MAIL_PASSWORD = "${MAIL_PASSWORD}"
    MAIL_ENCRYPTION = "${MAIL_ENCRYPTION}"
    MAIL_FROM_ADDRESS = "${MAIL_FROM_ADDRESS}"
    MAIL_FROM_NAME = "${MAIL_FROM_NAME}"
    AWS_ACCESS_KEY_ID = "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY = "${AWS_SECRET_ACCESS_KEY}"
    AWS_DEFAULT_REGION = "${AWS_DEFAULT_REGION}"
    AWS_BUCKET = "${AWS_BUCKET}"
    AWS_URL = "${AWS_URL}"
    AWS_ENDPOINT = "${AWS_ENDPOINT}"
    NORDIGEN_SECRET_ID = "${NORDIGEN_SECRET_ID}"
    NORDIGEN_SECRET_KEY = "${NORDIGEN_SECRET_KEY}"
    IS_DOCKER = "true"
    SCOUT_DRIVER = "${SCOUT_DRIVER}"
    LICENSE_KEY = "${LICENSE_KEY}"
    [[services.storage]]
      host = "invoice-ninja-public"
      container = "/var/www/app/public"
    [[services.storage]]
      host = "invoice-ninja-storage"
      container = "/var/www/app/storage"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:11"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "${SERVICE_PASSWORD_MARIADBROOT}"
    MYSQL_DATABASE = "${DB_DATABASE:-invoiceninja}"
    MYSQL_USER = "${SERVICE_USER_MARIADB}"
    MYSQL_PASSWORD = "${SERVICE_PASSWORD_MARIADB}"
    [[services.storage]]
      host = "mariadb-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7.4-alpine"
start_command = "redis-server --requirepass ${SERVICE_PASSWORD_REDIS}"
source = { type = "docker"  }
  [services.env]
    REDIS_PASSWORD = "${SERVICE_PASSWORD_REDIS}"
    [[services.storage]]
      host = "invoice-ninja-redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "invoice-ninja"
to = "mariadb"
