name = "IT Tools is a self-hosted solution for managing various IT tasks."
description = "IT Tools is a self-hosted solution for managing various IT tasks."
category = "stack"
logo = "svgs/it-tools.svg"
[[services]]
name = "it-tools"
category = "app"
subtype = "docker"
docker_image = "corentinth/it-tools:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_ITTOOLS_80 = ""
    [[services.storage]]
      host = "it-tools-data"
      container = "/app/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10
