name = "Jenkins"
description = "Jenkins is an open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project."
category = "stack"
logo = "svgs/jenkins.svg"

[[services]]
name = "jenkins"
category = "app"
subtype = "docker"
docker_image = "jenkins/jenkins:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
    [[services.storage]]
      host = "jenkins-home"
      container = "/var/jenkins_home"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10
