name = "Joomla With Mariadb"
description = "Joomla! is the mobile-ready and user-friendly way to build your website. Choose from thousands of features and designs. Joomla! is free and open source."
category = "stack"
logo = "svgs/joomla.svg"

[[services]]
name = "joomla"
category = "app"
subtype = "docker"
docker_image = "joomla:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    JOOMLA_DB_HOST = "mariadb"
    JOOMLA_DB_USER = "user"
    JOOMLA_DB_PASSWORD = "${{ secret() }}"
    JOOMLA_DB_NAME = "joomla-db"
    [[services.storage]]
      host = "joomla_data"
      container = "/var/www/html"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:11"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "joomla-db"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "joomla_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "joomla"
to = "mariadb"
