name = "Joplin"
description = "Self-hosted sync server for Joplin"
category = "stack"
logo = "svgs/joplin.png"

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_DB = "joplin"
    [[services.storage]]
      host = "joplin-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "joplin"
category = "app"
subtype = "docker"
docker_image = "joplin/server:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_BASE_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    DB_CLIENT = "pg"
    POSTGRES_DATABASE = "joplin"
    POSTGRES_HOST = "postgres"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "joplin"
to = "postgres"