name = "Keycloak With Postgres"
description = "Keycloak is an open-source Identity and Access Management tool."
category = "stack"
logo = "svgs/keycloak.svg"

[[services]]
name = "keycloak"
category = "app"
subtype = "docker"
docker_image = "quay.io/keycloak/keycloak:26.1"
start_command = "start"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    TZ = "UTC"
    KC_BOOTSTRAP_ADMIN_USERNAME = "user"
    KC_BOOTSTRAP_ADMIN_PASSWORD = "${{ secret() }}"
    KC_DB = "postgres"
    KC_DB_USERNAME = "user"
    KC_DB_PASSWORD = "${{ secret() }}"
    KC_DB_URL_PORT = "5432"
    KC_DB_URL = "jdbc:postgresql://postgres/keycloak"
    KC_HOSTNAME = "https://example.com"
    KC_HTTP_ENABLED = "true"
    KC_HEALTH_ENABLED = "true"
    KC_PROXY_HEADERS = "xforwarded"
    [[services.storage]]
      host = "keycloak-data"
      container = "/opt/keycloak/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "keycloak"
    [[services.storage]]
      host = "keycloak-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "keycloak"
to = "postgres"