name = "Kimai"
description = "Open source time-tracking app."
category = "stack"
logo = "svgs/kimai.svg"

[[services]]
name = "mysql"
category = "database"
subtype = "mysql"
docker_image = "mysql:8"
start_command = "--default-storage-engine innodb"
source = { type = "docker"  }
  [services.env]
    MYSQL_DATABASE = "kimai"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "kimai-mysql-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "kimai"
category = "app"
subtype = "docker"
docker_image = "kimai/kimai2:apache"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_SECRET = "${{ secret() }}"
    MAILER_FROM = "kimai@example.com"
    MAILER_URL = "null://null"
    ADMINMAIL = "admin@kimai.local"
    ADMINPASS = "${{ secret() }}"
    DATABASE_URL = "mysql:${{ secret() }}@mysql/MYSQL_DATABASE_VALUE?charset=utf8mb4&serverVersion=8.3.0"
    TRUSTED_HOSTS = "https://example.com|localhost|127.0.0.1"
    [[services.storage]]
      host = "kimai-data"
      container = "/opt/kimai/var/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[links]]
from = "kimai"
to = "mysql"
