name = "Labelstudio"
description = "Label Studio is a multi-type data labeling and annotation tool with standardized output format"
category = "stack"
logo = "svgs/labelstudio.png"

[[services]]
name = "labelstudio"
category = "app"
subtype = "docker"
docker_image = "heartexlabs/label-studio:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CSRF_TRUSTED_ORIGINS = "https://example.com"
    EXPERIMENTAL_FEATURES = "false"
    DJANGO_DB = "default"
    POSTGRE_NAME = "labelstudio"
    POSTGRE_USER = "user"
    POSTGRE_PASSWORD = "${{ secret() }}"
    POSTGRE_PORT = "5432"
    POSTGRE_HOST = "postgres"
    LABEL_STUDIO_HOST = "https://example.com"
    SSRF_PROTECTION_ENABLED = "true"
    LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK = "true"
    DATA_UPLOAD_MAX_NUMBER_FILES = "10000"
    LABEL_STUDIO_USERNAME = "admin@example.com"
    LABEL_STUDIO_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "labelstudio-data"
      container = "/label-studio/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "labelstudio"
    [[services.storage]]
      host = "pg-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "labelstudio"
to = "postgres"
