name = "Langfuse"
description = "Langfuse is an open-source LLM engineering platform that helps teams collaboratively debug, analyze, and iterate on their LLM applications."
category = "stack"
logo = "svgs/langfuse.svg"

[[services]]
name = "langfuse"
category = "app"
subtype = "docker"
docker_image = "langfuse/langfuse:3"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    << = "[\"NEXTAUTH_URL=https://example.com\", \"DATABASE_URL=postgresql://user:CHANGE_ME@postgres:5432/langfuse-db\", \"SALT=CHANGE_ME\", \"ENCRYPTION_KEY=CHANGE_ME\", \"TELEMETRY_ENABLED=false\", \"LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false\", \"CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000\", \"CLICKHOUSE_URL=http://clickhouse:8123\", \"CLICKHOUSE_USER=user\", \"CLICKHOUSE_PASSWORD=CHANGE_ME\", \"CLICKHOUSE_CLUSTER_ENABLED=false\", \"LANGFUSE_USE_AZURE_BLOB=false\", \"LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse\", \"LANGFUSE_S3_EVENT_UPLOAD_REGION=auto\", \"LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=CHANGE_ME\", \"LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=CHANGE_ME\", \"LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT_VALUE\", \"LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true\", \"LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/\", \"LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=langfuse\", \"LANGFUSE_S3_MEDIA_UPLOAD_REGION=auto\", \"LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=CHANGE_ME\", \"LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=CHANGE_ME\", \"LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT_VALUE\", \"LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=true\", \"LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=media/\", \"LANGFUSE_S3_BATCH_EXPORT_ENABLED=false\", \"LANGFUSE_S3_BATCH_EXPORT_BUCKET=langfuse\", \"LANGFUSE_S3_BATCH_EXPORT_PREFIX=exports/\", \"LANGFUSE_S3_BATCH_EXPORT_REGION=auto\", \"LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=3000\", \"LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT=3000\", \"LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=CHANGE_ME\", \"LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=CHANGE_ME\", \"LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE=true\", \"LANGFUSE_INGESTION_QUEUE_DELAY_MS=1\", \"LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS=1000\", \"REDIS_HOST=redis\", \"REDIS_PORT=6379\", \"REDIS_AUTH=CHANGE_ME\", \"EMAIL_FROM_ADDRESS=admin@example.com\", \"SMTP_CONNECTION_URL=\", \"NEXTAUTH_SECRET=BASE64_GENERATED\", \"AUTH_DISABLE_SIGNUP=true\", \"HOSTNAME=0.0.0.0\", \"LANGFUSE_INIT_ORG_ID=my-org\", \"LANGFUSE_INIT_ORG_NAME=My Org\", \"LANGFUSE_INIT_PROJECT_ID=my-project\", \"LANGFUSE_INIT_PROJECT_NAME=My Project\", \"LANGFUSE_INIT_USER_EMAIL=admin@example.com\", \"LANGFUSE_INIT_USER_NAME=user\", \"LANGFUSE_INIT_USER_PASSWORD=CHANGE_ME\"]"
    SERVICE_URL_LANGFUSE_3000 = "https://example.com"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "langfuse-worker"
category = "app"
subtype = "docker"
docker_image = "langfuse/langfuse-worker:3"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    << = "[\"NEXTAUTH_URL=https://example.com\", \"DATABASE_URL=postgresql://user:CHANGE_ME@postgres:5432/langfuse-db\", \"SALT=CHANGE_ME\", \"ENCRYPTION_KEY=CHANGE_ME\", \"TELEMETRY_ENABLED=false\", \"LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false\", \"CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000\", \"CLICKHOUSE_URL=http://clickhouse:8123\", \"CLICKHOUSE_USER=user\", \"CLICKHOUSE_PASSWORD=CHANGE_ME\", \"CLICKHOUSE_CLUSTER_ENABLED=false\", \"LANGFUSE_USE_AZURE_BLOB=false\", \"LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse\", \"LANGFUSE_S3_EVENT_UPLOAD_REGION=auto\", \"LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=CHANGE_ME\", \"LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=CHANGE_ME\", \"LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT_VALUE\", \"LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true\", \"LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/\", \"LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=langfuse\", \"LANGFUSE_S3_MEDIA_UPLOAD_REGION=auto\", \"LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=CHANGE_ME\", \"LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=CHANGE_ME\", \"LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT_VALUE\", \"LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=true\", \"LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=media/\", \"LANGFUSE_S3_BATCH_EXPORT_ENABLED=false\", \"LANGFUSE_S3_BATCH_EXPORT_BUCKET=langfuse\", \"LANGFUSE_S3_BATCH_EXPORT_PREFIX=exports/\", \"LANGFUSE_S3_BATCH_EXPORT_REGION=auto\", \"LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=3000\", \"LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT=3000\", \"LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=CHANGE_ME\", \"LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=CHANGE_ME\", \"LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE=true\", \"LANGFUSE_INGESTION_QUEUE_DELAY_MS=1\", \"LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS=1000\", \"REDIS_HOST=redis\", \"REDIS_PORT=6379\", \"REDIS_AUTH=CHANGE_ME\", \"EMAIL_FROM_ADDRESS=admin@example.com\", \"SMTP_CONNECTION_URL=\", \"NEXTAUTH_SECRET=BASE64_GENERATED\", \"AUTH_DISABLE_SIGNUP=true\", \"HOSTNAME=0.0.0.0\", \"LANGFUSE_INIT_ORG_ID=my-org\", \"LANGFUSE_INIT_ORG_NAME=My Org\", \"LANGFUSE_INIT_PROJECT_ID=my-project\", \"LANGFUSE_INIT_PROJECT_NAME=My Project\", \"LANGFUSE_INIT_USER_EMAIL=admin@example.com\", \"LANGFUSE_INIT_USER_NAME=user\", \"LANGFUSE_INIT_USER_PASSWORD=CHANGE_ME\"]"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_DB = "langfuse-db"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_USER = "user"
    [[services.storage]]
      host = "langfuse_postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:8"
start_command = "sh -c redis-server --requirepass \"$SERVICE_PASSWORD_REDIS\""
source = { type = "docker"  }
  [services.env]
    REDIS_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "langfuse_redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 3
    timeout = 10

[[services]]
name = "clickhouse"
category = "app"
subtype = "docker"
docker_image = "clickhouse/clickhouse-server:26.2.4.23"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CLICKHOUSE_DB = "default"
    CLICKHOUSE_USER = "user"
    CLICKHOUSE_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "langfuse_clickhouse_data"
      container = "/var/lib/clickhouse"
    [[services.storage]]
      host = "langfuse_clickhouse_logs"
      container = "/var/log/clickhouse-server"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "langfuse"
to = "postgres"

[[links]]
from = "langfuse"
to = "redis"

[[links]]
from = "langfuse"
to = "clickhouse"

[[links]]
from = "langfuse-worker"
to = "postgres"

[[links]]
from = "langfuse-worker"
to = "redis"

[[links]]
from = "langfuse-worker"
to = "clickhouse"

[[links]]
from = "clickhouse"
to = "postgres"

[[links]]
from = "clickhouse"
to = "redis"

[[links]]
from = "langfuse-worker"
to = "langfuse"