name = "Librechat"
description = "Self-hosted, powerful, and privacy-focused chat UI for multiple AI models"
category = "stack"
logo = "svgs/librechat.svg"

[[services]]
name = "librechat"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/danny-avila/librechat-dev-api:6ecd1b510faaa593ad954fb6276c18e5f12a8e53"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DOMAIN_CLIENT = "https://example.com"
    DOMAIN_SERVER = "https://example.com"
    HOST = "0.0.0.0"
    PORT = "3080"
    MONGO_URI = "mongodb://user:CHANGE_ME@mongodb:27017/librechat?authSource=admin"
    MEILI_HOST = "http://meilisearch:7700"
    MEILI_MASTER_KEY = "CHANGE_ME"
    RAG_PORT = "8000"
    RAG_API_URL = "http://rag-api:8000"
    JWT_SECRET = "CHANGE_ME"
    JWT_REFRESH_SECRET = "CHANGE_ME"
    APP_TITLE = "LibreChat"
    ALLOW_EMAIL_LOGIN = "true"
    ALLOW_REGISTRATION = "true"
    ALLOW_SOCIAL_LOGIN = "false"
    ALLOW_SOCIAL_REGISTRATION = "false"
    ALLOW_PASSWORD_RESET = "false"
    ALLOW_UNVERIFIED_EMAIL_LOGIN = "true"
    CREDS_KEY = "CHANGE_ME"
    CREDS_IV = "CHANGE_ME"
    ANTHROPIC_API_KEY = "user_provided"
    GOOGLE_KEY = "user_provided"
    OPENAI_API_KEY = "user_provided"
    ASSISTANTS_API_KEY = "user_provided"
    DEBUG_LOGGING = "false"
    DEBUG_OPENAI = "false"
    DEBUG_PLUGINS = "false"
    NO_INDEX = "true"
    [[services.storage]]
      host = "librechat-images"
      container = "/app/client/public/images"
    [[services.storage]]
      host = "librechat-logs"
      container = "/app/api/logs"
    [[services.storage]]
      host = "librechat-uploads"
      container = "/app/uploads"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[services]]
name = "mongodb"
category = "database"
subtype = "mongo"
docker_image = "mongo:8"
source = { type = "docker"  }
  [services.env]
    MONGO_INITDB_ROOT_USERNAME = "user"
    MONGO_INITDB_ROOT_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "mongodb-data"
      container = "/data/db"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[services]]
name = "meilisearch"
category = "search"
subtype = "meilisearch"
docker_image = "getmeili/meilisearch:v1.35.1"
source = { type = "docker"  }
  [services.env]
    MEILI_MASTER_KEY = "CHANGE_ME"
    MEILI_NO_ANALYTICS = "false"
    MEILI_ENV = "production"
    MEILI_HOST = "http://meilisearch:7700"
    [[services.storage]]
      host = "meilisearch-data"
      container = "/meili_data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "vectordb"
category = "app"
subtype = "docker"
docker_image = "ankane/pgvector:v0.5.1"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_DB = "rag"
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_HOST_AUTH_METHOD = "trust"
    [[services.storage]]
      host = "vectordb-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 1

[[services]]
name = "rag-api"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/danny-avila/librechat-rag-api-dev-lite:v0.7.3"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_DB = "rag"
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    DB_HOST = "vectordb"
    DB_USER = "user"
    DB_PASSWORD = "CHANGE_ME"
    DB_NAME = "rag"
    RAG_PORT = "8000"
    RAG_OPENAI_API_KEY = "user_provided"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "librechat"
to = "mongodb"

[[links]]
from = "librechat"
to = "meilisearch"

[[links]]
from = "librechat"
to = "vectordb"

[[links]]
from = "librechat"
to = "rag-api"

[[links]]
from = "rag-api"
to = "vectordb"

[[links]]
from = "vectordb"
to = "mongodb"

[[links]]
from = "vectordb"
to = "meilisearch"

[[links]]
from = "rag-api"
to = "mongodb"

[[links]]
from = "rag-api"
to = "meilisearch"
