name = "Libreoffice"
description = "LibreOffice is a free and powerful office suite."
category = "stack"
logo = "svgs/libreoffice.svg"

[[services]]
name = "libreoffice"
category = "app"
subtype = "docker"
docker_image = "lscr.io/linuxserver/libreoffice:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PUID = "1000"
    PGID = "1000"
    TZ = "Etc/UTC"
    [[services.storage]]
      host = "libreoffice-config"
      container = "/config"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10
