name = "Librespeed"
description = "Self-hosted lightweight Speed Test."
category = "stack"
logo = "svgs/librespeed.png"

[[services]]
name = "librespeed"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/librespeed/speedtest:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    MODE = "standalone"
    TELEMETRY = "false"
    DISTANCE = "km"
    WEBPORT = "82"
  [services.checks]
    enabled = true
    wait = 1
    timeout = 1
