name = "Limesurvey"
description = "Simple, quick and anonymous online survey tool that's bursting with juicy insights."
category = "stack"
logo = "svgs/limesurvey.svg"

[[services]]
name = "limesurvey"
category = "app"
subtype = "docker"
docker_image = "adamzammit/limesurvey:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    LIMESURVEY_DB_HOST = "mariadb"
    LIMESURVEY_DB_PASSWORD = "CHANGE_ME"
    LIMESURVEY_DB_USER = "user"
    LIMESURVEY_DB_NAME = "limesurvey-db"
    LIMESURVEY_ADMIN_USER = "admin"
    LIMESURVEY_ADMIN_PASSWORD = "CHANGE_ME"
    LIMESURVEY_ADMIN_NAME = "Admin"
    LIMESURVEY_ADMIN_EMAIL = "admin@example.com"
    LIMESURVEY_FROM_EMAIL = "admin@example.com"
    LIMESURVEY_SMTP_HOST = "https://example.com"
    LIMESURVEY_SMTP_USER = "LIMESURVEY_SMTP_USER_VALUE"
    LIMESURVEY_SMTP_PASSWORD = "CHANGE_ME"
    LIMESURVEY_SMTP_SSL = "LIMESURVEY_SMTP_SSL_VALUE"
    LIMESURVEY_PHP_SESSION_SAVE_HANDLER = "redis"
    LIMESURVEY_PHP_SESSION_SAVE_PATH = "tcp://redis:6379"
    TZ = "America/Jamaica"
    [[services.storage]]
      host = "limesurvey_plugins_data"
      container = "/var/www/html/plugins"
    [[services.storage]]
      host = "limesurvey_upload_data"
      container = "/var/www/html/upload"
    [[services.storage]]
      host = "limesurvey_config_data"
      container = "/var/www/html/application/config"
    [[services.storage]]
      host = "limesurvey_sessions_data"
      container = "/var/lime/sessions"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:11"
source = { type = "docker"  }
  [services.env]
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "CHANGE_ME"
    MYSQL_DATABASE = "limesurvey-db"
    MYSQL_ROOT_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "limesurvey_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
source = { type = "docker"  }
  [services.checks]
    enabled = true
    wait = 5
    timeout = 3

[[links]]
from = "limesurvey"
to = "mariadb"

[[links]]
from = "limesurvey"
to = "redis"
