name = "Simple, quick and anonymous online survey tool that's bursting with juicy insights."
description = "Simple, quick and anonymous online survey tool that's bursting with juicy insights."
category = "stack"
logo = "svgs/limesurvey.svg"
[[services]]
name = "limesurvey"
category = "app"
subtype = "docker"
docker_image = "adamzammit/limesurvey:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_LIMESURVEY_80 = ""
    LIMESURVEY_DB_HOST = "mariadb"
    LIMESURVEY_DB_PASSWORD = "${SERVICE_PASSWORD_MYSQL}"
    LIMESURVEY_DB_USER = "${SERVICE_USER_MYSQL}"
    LIMESURVEY_DB_NAME = "${MYSQL_DATABASE:-limesurvey-db}"
    LIMESURVEY_ADMIN_USER = "${LIMESURVEY_ADMIN_USER:-admin}"
    LIMESURVEY_ADMIN_PASSWORD = "${SERVICE_PASSWORD_ADMIN}"
    LIMESURVEY_ADMIN_NAME = "${LIMESURVEY_ADMIN_NAME:-Admin}"
    LIMESURVEY_ADMIN_EMAIL = "${LIMESURVEY_ADMIN_EMAIL:-admin@example.com}"
    LIMESURVEY_FROM_EMAIL = "${LIMESURVEY_FROM_EMAIL}"
    LIMESURVEY_SMTP_HOST = "${LIMESURVEY_SMTP_HOST}"
    LIMESURVEY_SMTP_USER = "${LIMESURVEY_SMTP_USER}"
    LIMESURVEY_SMTP_PASSWORD = "${LIMESURVEY_SMTP_PASSWORD}"
    LIMESURVEY_SMTP_SSL = "${LIMESURVEY_SMTP_SSL}"
    LIMESURVEY_PHP_SESSION_SAVE_HANDLER = "redis"
    LIMESURVEY_PHP_SESSION_SAVE_PATH = "tcp://redis:6379"
    TZ = "${TZ:-America/Jamaica}"
    [[services.storage]]
      host = "limesurvey_plugins_data"
      container = "/var/www/html/plugins"
    [[services.storage]]
      host = "limesurvey_upload_data"
      container = "/var/www/html/upload"
    [[services.storage]]
      host = "limesurvey_config_data"
      container = "/var/www/html/application/config"
    [[services.storage]]
      host = "limesurvey_sessions_data"
      container = "/var/lime/sessions"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:11"
source = { type = "docker"  }
  [services.env]
    MYSQL_USER = "${SERVICE_USER_MYSQL}"
    MYSQL_PASSWORD = "${SERVICE_PASSWORD_MYSQL}"
    MYSQL_DATABASE = "${MYSQL_DATABASE:-limesurvey-db}"
    MYSQL_ROOT_PASSWORD = "${SERVICE_PASSWORD_MYSQLROOT}"
    [[services.storage]]
      host = "limesurvey_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
source = { type = "docker"  }
  [services.checks]
    enabled = true
    wait = 5
    timeout = 3

[[links]]
from = "limesurvey"
to = "mariadb"

[[links]]
from = "limesurvey"
to = "redis"
