name = "Lite Queen is an open-source SQLite database management software that runs on your server."
description = "Lite Queen is an open-source SQLite database management software that runs on your server."
category = "stack"
logo = "svgs/litequeen.svg"
[[services]]
name = "litequeen"
category = "app"
subtype = "docker"
docker_image = "kivsegrob/lite-queen:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_LITEQUEEN_8000 = ""
    [[services.storage]]
      host = "litequeen-data"
      container = "/home/litequeen/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5
