name = "Litellm"
description = "Call all LLM APIs using the OpenAI format. Use Bedrock, Azure, OpenAI, Cohere, Anthropic, Ollama, Sagemaker, HuggingFace, Replicate, Groq (100+ LLMs)"
category = "stack"
logo = "svgs/litellm.svg"

[[services]]
name = "litellm"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/berriai/litellm-database:main-stable"
start_command = "--config /app/config.yaml --port 4000 --num_workers 8"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    LITELLM_LOG = "ERROR"
    LITELLM_MODE = "PRODUCTION"
    LITELLM_MASTER_KEY = "CHANGE_ME"
    UI_USERNAME = "user"
    UI_PASSWORD = "CHANGE_ME"
    DATABASE_URL = "postgresql://user:CHANGE_ME@postgres:5432/litellm"
    REDIS_HOST = "redis"
    REDIS_PORT = "6379"
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "litellm"
    OPENAI_API_KEY = "CHANGE_ME"
    OPENAI_API_BASE = "OPENAI_API_BASE_VALUE"
    ANTHROPIC_API_KEY = "CHANGE_ME"
    ANTHROPIC_API_BASE = "ANTHROPIC_API_BASE_VALUE"
    VOYAGE_API_KEY = "CHANGE_ME"
    VOYAGE_API_BASE = "VOYAGE_API_BASE_VALUE"
    STORE_MODEL_IN_DB = "STORE_MODEL_IN_DB_VALUE"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_DB = "litellm"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    POSTGRES_USER = "$SERVICE_USER_POSTGRES"
    [[services.storage]]
      host = "pg-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
start_command = "redis-server --appendonly yes"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "litellm"
to = "postgres"

[[links]]
from = "litellm"
to = "redis"
