name = "Lobe Chat"
description = "An open-source, modern-design AI chat framework."
category = "stack"
logo = "svgs/lobe-chat.png"

[[services]]
name = "lobe-chat"
category = "app"
subtype = "docker"
docker_image = "lobehub/lobe-chat:1.135.5"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    OPENAI_API_KEY = "CHANGE_ME"
    OPENAI_PROXY_URL = "https://api.openai.com/v1"
    ACCESS_CODE = "CHANGE_ME"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
