name = "Logto"
description = "A comprehensive identity solution covering both the front and backend, complete with pre-built infrastructure and enterprise-grade solutions."
category = "stack"
logo = "svgs/logto_dark.svg"

[[services]]
name = "logto"
category = "app"
subtype = "docker"
docker_image = "svhd/logto:${TAG-latest}"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    TRUST_PROXY_HEADER = "1"
    DB_URL = "postgres://user:CHANGE_ME@postgres:5432/logto"
    ENDPOINT = "$LOGTO_ENDPOINT"
    ADMIN_ENDPOINT = "$LOGTO_ADMIN_ENDPOINT"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:14-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "logto"
    [[services.storage]]
      host = "logto-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "logto"
to = "postgres"

[[links]]
from = "postgres"
to = "logto"
