name = "Lowcoder"
description = "Lowcoder (forked from OpenBlocks) is a self-hosted, open-source, low-code platform for building internal tools."
category = "stack"
logo = "svgs/lowcoder.svg"

[[services]]
name = "lowcoder"
category = "app"
subtype = "docker"
docker_image = "lowcoderorg/lowcoder-ce"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    LOWCODER_EMAIL_SIGNUP_ENABLED = "true"
    LOWCODER_DB_ENCRYPTION_PASSWORD = "CHANGE_ME"
    LOWCODER_DB_ENCRYPTION_SALT = "CHANGE_ME"
    [[services.storage]]
      host = "lowcoder_data"
      container = "/lowcoder-stacks"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
