name = "Martin"
description = "Martin is a tile server able to generate and serve vector tiles on the fly from large PostGIS databases, PMTiles (local or remote), and MBTiles files, allowing multiple tile sources to be dynamically combined into one."
category = "stack"
logo = "svgs/martin.png"

[[services]]
name = "martin"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/maplibre/martin:v0.13.0"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    HOST = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    DATABASE_URL = "postgresql://user:${{ secret() }}@postgresql:5432/martin-db"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgresql"
category = "app"
subtype = "docker"
docker_image = "postgis/postgis:16-3.4-alpine"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "martin-db"
    [[services.storage]]
      host = "martin-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "martin"
to = "postgresql"
