name = "Maybe"
description = "Maybe, the OS for your personal finances."
category = "stack"
logo = "svgs/maybe.svg"

[[services]]
name = "maybe"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/maybe-finance/maybe:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SELF_HOSTED = "true"
    RAILS_FORCE_SSL = "false"
    RAILS_ASSUME_SSL = "false"
    GOOD_JOB_EXECUTION_MODE = "async"
    SECRET_KEY_BASE = "BASE64_GENERATED"
    REDIS_URL = "redis:${{ secret() }}@redis:6379/1"
    OPENAI_ACCESS_TOKEN = "${{ secret() }}"
    [[services.storage]]
      host = "app_storage"
      container = "/rails/storage"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 10

[[services]]
name = "worker"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/maybe-finance/maybe:latest"
start_command = "bundle exec sidekiq"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY_BASE = "BASE64_GENERATED"
    SELF_HOSTED = "true"
    RAILS_FORCE_SSL = "false"
    RAILS_ASSUME_SSL = "false"
    GOOD_JOB_EXECUTION_MODE = "async"
    REDIS_URL = "redis:${{ secret() }}@redis:6379/1"
    OPENAI_ACCESS_TOKEN = "${{ secret() }}"

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "maybe-db"
    [[services.storage]]
      host = "maybe_postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:8-alpine"
start_command = "redis-server --appendonly yes --requirepass ${{ secret() }}"
source = { type = "docker"  }
  [services.env]
    REDIS_PASSWORD = "${{ secret() }}"
    REDIS_PORT = "6379"
    REDIS_DB = "1"
    [[services.storage]]
      host = "redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 3

[[links]]
from = "maybe"
to = "postgres"

[[links]]
from = "maybe"
to = "redis"

[[links]]
from = "worker"
to = "postgres"

[[links]]
from = "worker"
to = "redis"