name = "Mediawiki"
description = "MediaWiki is a collaboration and documentation platform brought to you by a vibrant community."
category = "stack"
logo = "svgs/mediawiki.ico"

[[services]]
name = "mediawiki"
category = "app"
subtype = "docker"
docker_image = "mediawiki:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
    [[services.storage]]
      host = "mediawiki-images"
      container = "/var/www/html/images"
    [[services.storage]]
      host = "mediawiki-sqlite"
      container = "/var/www/html/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
