name = "Meilisearch"
description = "MeiliSearch is a powerful, fast, easy to use and deploy search engine."
category = "stack"
logo = "svgs/meilisearch.svg"

[[services]]
name = "meilisearch"
category = "search"
subtype = "meilisearch"
docker_image = "getmeili/meilisearch:latest"
source = { type = "docker"  }
  [services.env]
    MEILI_NO_ANALYTICS = "true"
    MEILI_ENV = "production"
    MEILI_MASTER_KEY = "${{ secret() }}"
    [[services.storage]]
      host = "meilisearch-data"
      container = "/meili_data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
