name = "MeiliSearch is a powerful, fast, easy to use and deploy search engine."
description = "MeiliSearch is a powerful, fast, easy to use and deploy search engine."
category = "stack"
logo = "svgs/meilisearch.svg"
[[services]]
name = "meilisearch"
category = "search"
subtype = "meilisearch"
docker_image = "getmeili/meilisearch:latest"
source = { type = "docker"  }
  [services.env]
    SERVICE_URL_MEILISEARCH_7700 = ""
    MEILI_NO_ANALYTICS = "${MEILI_NO_ANALYTICS:-true}"
    MEILI_ENV = "${MEILI_ENV:-production}"
    MEILI_MASTER_KEY = "${SERVICE_PASSWORD_MEILISEARCH}"
    [[services.storage]]
      host = "meilisearch-data"
      container = "/meili_data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
