name = "Metabase"
description = "Fast analytics with the friendly UX and integrated tooling to let your company explore data on their own."
category = "stack"
logo = "svgs/metabase.svg"

[[services]]
name = "metabase"
category = "app"
subtype = "docker"
docker_image = "metabase/metabase:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    MB_DB_TYPE = "postgres"
    MB_DB_HOST = "postgresql"
    MB_DB_PORT = "5432"
    MB_DB_DBNAME = "metabase"
    MB_DB_USER = "${{ linked.postgresql.POSTGRES_USER }}"
    MB_DB_PASS = "${{ linked.postgresql.POSTGRES_PASSWORD }}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "metabase"
    [[services.storage]]
      host = "metabase-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "metabase"
to = "postgresql"