name = "Metamcp"
description = "MCP Aggregator, Orchestrator, Middleware, Gateway in one app"
category = "stack"
logo = "svgs/metamcp.png"

[[services]]
name = "app"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/metatool-ai/metamcp:2.4"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    POSTGRES_HOST = "postgres"
    POSTGRES_PORT = "5432"
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "metamcp_db"
    DATABASE_URL = "postgresql://user:CHANGE_ME@postgres:5432/metamcp_db"
    APP_URL = "https://example.com"
    NEXT_PUBLIC_APP_URL = "https://example.com"
    BETTER_AUTH_SECRET = "${{ secret() }}"
    TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL = "true"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_DB = "metamcp_db"
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "app"
to = "postgres"
