name = "Mindsdb"
description = "MindsDB is the platform for building AI from enterprise data, enabling smarter organizations."
category = "stack"
logo = "svgs/mindsdb.svg"

[[services]]
name = "mindsdb"
category = "app"
subtype = "docker"
docker_image = "mindsdb/mindsdb:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_API_47335 = "/api"
    MINDSDB_DOCKER_ENV = "true"
    MINDSDB_STORAGE_DIR = "/mindsdb/var"
    FLASK_DEBUG = "1"
    OPENAI_API_KEY = "${{ secret() }}"
    LANGFUSE_HOST = "https://example.com"
    LANGFUSE_PUBLIC_KEY = "${{ secret() }}"
    LANGFUSE_SECRET_KEY = "${{ secret() }}"
    LANGFUSE_RELEASE = "local"
    LANGFUSE_DEBUG = "False"
    LANGFUSE_TIMEOUT = "10"
    LANGFUSE_SAMPLE_RATE = "1.0"
    MINDSDB_DB_CON = "postgresql://user:CHANGE_ME@postgresql/mindsdb-db"
    [[services.storage]]
      host = "mindsdb-data"
      container = "/mindsdb/var"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "mindsdb-db"
    [[services.storage]]
      host = "mindsdb-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "mindsdb"
to = "postgresql"
