name = "Minecraft"
description = "Minecraft Server that will automatically download selected version at startup."
category = "stack"
logo = "svgs/minecraft.svg"

[[services]]
name = "mc"
category = "app"
subtype = "docker"
docker_image = "itzg/minecraft-server"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    EULA = "true"
    VERSION = "latest"
    TYPE = "VANILLA"
    SERVER_NAME = "Minecraft Server"
    MOTD = "Minecraft Server powered by §aCoolify§r"
    DIFFICULTY = "normal"
    MAX_PLAYERS = "10"
    MAX_WORLD_SIZE = "10000"
    VIEW_DISTANCE = "10"
    MAX_BUILD_HEIGHT = "256"
    MAX_TICK_TIME = "60000"
    ALLOW_NETHER = "true"
    ANNOUNCE_PLAYER_ACHIEVEMENTS = "true"
    GENERATE_STRUCTURES = "true"
    PVP = "true"
    MODE = "survival"
    FORCE_GAMEMODE = "false"
    HARDCORE = "false"
    ENABLE_COMMAND_BLOCK = "false"
    SPAWN_ANIMALS = "true"
    SPAWN_MONSTERS = "true"
    SPAWN_NPCS = "true"
    SNOOPER_ENABLED = "false"
    ONLINE_MODE = "true"
    PLAYER_IDLE_TIMEOUT = "0"
    INIT_MEMORY = "256M"
    MAX_MEMORY = "1G"
    GUI = "false"
    ENABLE_AUTOPAUSE = "false"
    RCON_PASSWORD = "CHANGE_ME"
    PORT = "25565"
  [services.proxy]
    enabled = true
    type = "traefik"
    [[services.proxy.ports]]
      host = 0
      container = 25565
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
