name = "Miniflux"
description = "Miniflux is a minimalist and opinionated feed reader."
category = "stack"
logo = "svgs/miniflux.svg"

[[services]]
name = "miniflux"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/miniflux/miniflux:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    BASE_URL = "https://example.com"
    PORT = "8080"
    RUN_MIGRATIONS = "1"
    CREATE_ADMIN = "1"
    ADMIN_USERNAME = "user"
    ADMIN_PASSWORD = "${{ secret() }}"
    DATABASE_URL = "postgres:${{ secret() }}@postgres:5432/miniflux-db?sslmode=disable"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "miniflux-db"
    [[services.storage]]
      host = "miniflux-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "miniflux"
to = "postgres"
