name = "Miniflux is a minimalist and opinionated feed reader."
description = "Miniflux is a minimalist and opinionated feed reader."
category = "stack"
logo = "svgs/miniflux.svg"
[[services]]
name = "miniflux"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/miniflux/miniflux:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_MINIFLUX = ""
    BASE_URL = "${SERVICE_URL_MINIFLUX}"
    PORT = "${PORT:-8080}"
    RUN_MIGRATIONS = "${RUN_MIGRATIONS:-1}"
    CREATE_ADMIN = "${CREATE_ADMIN:-1}"
    ADMIN_USERNAME = "${SERVICE_USER_ADMIN}"
    ADMIN_PASSWORD = "${SERVICE_PASSWORD_64_ADMIN}"
    DATABASE_URL = "postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-miniflux-db}?sslmode=disable"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "${SERVICE_USER_POSTGRES}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    POSTGRES_DB = "${POSTGRES_DB:-miniflux-db}"
    [[services.storage]]
      host = "miniflux-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "miniflux"
to = "postgres"
