name = "Mixpost"
description = "Mixpost is a robust and versatile social media management software, designed to streamline social media operations and enhance content marketing strategies."
category = "stack"
logo = "svgs/mixpost.svg"

[[services]]
name = "mixpost"
category = "app"
subtype = "docker"
docker_image = "inovector/mixpost:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_NAME = "Mixpost"
    APP_KEY = "BASE64_GENERATED"
    APP_DEBUG = "false"
    APP_DOMAIN = "https://example.com"
    APP_URL = "https://example.com"
    DB_DATABASE = "mixpost_db"
    DB_USERNAME = "user"
    DB_PASSWORD = "${{ secret() }}"
    SSL_EMAIL = "user@example.com"
    [[services.storage]]
      host = "mixpost-storage"
      container = "/var/www/html/storage/app"
    [[services.storage]]
      host = "mixpost-logs"
      container = "/var/www/html/storage/logs"

[[services]]
name = "mysql"
category = "database"
subtype = "mysql"
docker_image = "mysql/mysql-server:8.0"
source = { type = "docker"  }
  [services.env]
    MYSQL_DATABASE = "mixpost_db"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "mixpost-mysql"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:alpine"
source = { type = "docker"  }
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[links]]
from = "mixpost"
to = "mysql"

[[links]]
from = "mixpost"
to = "redis"
