name = "Mosquitto"
description = "Mosquitto is lightweight and suitable for use on all devices, from low-power single-board computers to full servers."
category = "stack"
logo = "svgs/mosquitto.svg"

[[services]]
name = "mosquitto"
category = "app"
subtype = "docker"
docker_image = "eclipse-mosquitto"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    MQTT_USERNAME = "user"
    MQTT_PASSWORD = "${{ secret() }}"
    REQUIRE_CERTIFICATE = "false"
    ALLOW_ANONYMOUS = "true"
  [services.proxy]
    enabled = true
    type = "traefik"
    [[services.proxy.ports]]
      host = 8883
      container = 8883
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10
