name = "N8n"
description = "n8n is an extendable workflow automation tool."
category = "stack"
logo = "svgs/n8n.png"

[[services]]
name = "n8n"
category = "app"
subtype = "docker"
docker_image = "n8nio/n8n:2.10.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    N8N_EDITOR_BASE_URL = "https://example.com"
    WEBHOOK_URL = "https://example.com"
    N8N_HOST = "app.example.com"
    N8N_PROTOCOL = "https"
    GENERIC_TIMEZONE = "UTC"
    TZ = "UTC"
    DB_SQLITE_POOL_SIZE = "2"
    N8N_RUNNERS_ENABLED = "true"
    N8N_RUNNERS_MODE = "external"
    N8N_RUNNERS_BROKER_LISTEN_ADDRESS = "0.0.0.0"
    N8N_RUNNERS_BROKER_PORT = "5679"
    N8N_RUNNERS_AUTH_TOKEN = "CHANGE_ME"
    N8N_NATIVE_PYTHON_RUNNER = "true"
    N8N_RUNNERS_MAX_CONCURRENCY = "5"
    N8N_BLOCK_ENV_ACCESS_IN_NODE = "true"
    N8N_GIT_NODE_DISABLE_BARE_REPOS = "true"
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS = "true"
    N8N_PROXY_HOPS = "1"
    N8N_SKIP_AUTH_ON_OAUTH_CALLBACK = "false"
    [[services.storage]]
      host = "n8n-data"
      container = "/home/node/.n8n"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "task-runners"
category = "app"
subtype = "docker"
docker_image = "n8nio/runners:2.10.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    N8N_RUNNERS_TASK_BROKER_URI = "http://n8n:5679"
    N8N_RUNNERS_AUTH_TOKEN = "CHANGE_ME"
    N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT = "15"
    N8N_RUNNERS_MAX_CONCURRENCY = "5"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "task-runners"
to = "n8n"
