name = "Navidrome"
description = "Standalone server, that allows you to browse and listen to your music collection using a web browser or any Subsonic-compatible client."
category = "stack"
logo = "svgs/navidrome.svg"

[[services]]
name = "navidrome"
category = "app"
subtype = "docker"
docker_image = "deluan/navidrome:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    ND_BASEURL = "https://example.com"
    ND_SCANSCHEDULE = "1h"
    ND_LOGLEVEL = "info"
    ND_SESSIONTIMEOUT = "24h"
    ND_ENABLEINSIGHTSCOLLECTOR = "false"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5
