name = "Neon Ws Proxy"
description = "The database you love, on a serverless platform designed to help you build reliable and scalable applications faster."
category = "stack"
logo = "svgs/neon.svg"

[[services]]
name = "neon-proxy"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/neondatabase/wsproxy:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APPEND_PORT = "postgres:5432"
    ALLOW_ADDR_REGEX = ".*"
    LOG_TRAFFIC = "false"
    LOG_CONN_INFO = "true"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 2

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "postgres"
    POSTGRES_HOST_AUTH_METHOD = "password"
    [[services.storage]]
      host = "postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "neon-proxy"
to = "postgres"