name = "Nitropage With Postgresql"
description = "Nitropage is an extensible, visual website builder, offering a growing library of versatile building blocks, focal-point image cropping and sovereign font management."
category = "stack"
logo = "svgs/nitropage.svg"

[[services]]
name = "nitropage"
category = "app"
subtype = "docker"
docker_image = "nitropage/nitropage"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NP_AUTH_SALT = "BASE64_GENERATED"
    NP_AUTH_PASSWORD = "${{ secret() }}"
    DATABASE_URL = "postgresql://user:${{ secret() }}@postgresql:5432/nitropage"
    [[services.storage]]
      host = "nitropage-data"
      container = "/app/.data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "nitropage"
    [[services.storage]]
      host = "nitropage-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "nitropage"
to = "postgresql"