name = "A next-generation discussion platform."
description = "A next-generation discussion platform."
category = "stack"
logo = "svgs/nodebb.svg"
[[services]]
name = "nodebb"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/nodebb/nodebb:latest"
start_command = "/bin/bash -c \" cat > /usr/src/app/setup.json <<EOL {\n    \\"defaults\\": {\n        \\"postgres\\": {\n            \\"host\\": \\"postgres\\",\n            \\"port\\": 5432,\n            \\"database\\": \\"nodebb\\",\n            \\"username\\": \\"${SERVICE_USER_POSTGRES}\\",\n            \\"password\\": \\"${SERVICE_PASSWORD_POSTGRES}\\"\n        }\n    }\n} EOL && tini -- entrypoint.sh \"\n"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_NODEBB_4567 = ""
    [[services.storage]]
      host = "nodebb_build"
      container = "/usr/src/app/build"
    [[services.storage]]
      host = "nodebb_uploads"
      container = "/usr/src/app/public/uploads"
    [[services.storage]]
      host = "nodebb_config"
      container = "/opt/config"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:17.2-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "${SERVICE_USER_POSTGRES}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    POSTGRES_DB = "nodebb"
    [[services.storage]]
      host = "nodebb_postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "nodebb"
to = "postgres"
