name = "Observium"
description = "Observium is a comprehensive network monitoring platform designed to deliver powerful monitoring capabilities, combined with an elegant and intuitive user interface."
category = "stack"
logo = "svgs/observium.webp"

[[services]]
name = "observium"
category = "app"
subtype = "docker"
docker_image = "mbixtech/observium:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_OBSERVIUM = "https://example.com"
    OBSERVIUM_ADMIN_PASS = "CHANGE_ME"
    OBSERVIUM_ADMIN_USER = "user"
    OBSERVIUM_DB_HOST = "mariadb"
    OBSERVIUM_DB_NAME = "observium-db"
    OBSERVIUM_DB_PASS = "CHANGE_ME"
    OBSERVIUM_DB_USER = "user"
    [[services.storage]]
      host = "observium_logs"
      container = "/opt/observium/logs"
    [[services.storage]]
      host = "observium_rrd"
      container = "/opt/observium/rrd"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:lts"
source = { type = "docker"  }
  [services.env]
    MARIADB_ROOT_PASSWORD = "CHANGE_ME"
    MARIADB_USER = "user"
    MARIADB_PASSWORD = "CHANGE_ME"
    MARIADB_DATABASE = "observium-db"
    [[services.storage]]
      host = "observium_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "observium"
to = "mariadb"
