name = "Odoo"
description = "Odoo is a suite of open-source business apps that cover all your company needs."
category = "stack"
logo = "svgs/odoo.svg"

[[services]]
name = "odoo"
category = "app"
subtype = "docker"
docker_image = "odoo:18"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    HOST = "postgresql"
    USER = "${{ linked.postgresql.POSTGRES_USER }}"
    PASSWORD = "${{ linked.postgresql.POSTGRES_PASSWORD }}"
    [[services.storage]]
      host = "odoo-web-data"
      container = "/var/lib/odoo"
    [[services.storage]]
      host = "odoo-extra-addons"
      container = "/mnt/extra-addons"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "postgres"
    [[services.storage]]
      host = "postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "odoo"
to = "postgresql"