name = "Once Campfire"
description = "Super simple group chat, without a subscription."
category = "stack"
logo = "svgs/once-campfire.png"

[[services]]
name = "campfire"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/basecamp/once-campfire:${TAG:-main}"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY_BASE = "BASE64_GENERATED"
    VAPID_PUBLIC_KEY = "${{ secret() }}"
    VAPID_PRIVATE_KEY = "${{ secret() }}"
    DISABLE_SSL = "true"
    SSL_DOMAIN = "false"
    SKIP_TELEMETRY = "true"
    SENTRY_DSN = "SENTRY_DSN_VALUE"
    [[services.storage]]
      host = "campfire-storage"
      container = "/rails/storage"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5
