name = "Onedev"
description = "Git server with CI/CD, kanban, and packages. Seamless integration. Unparalleled experience."
category = "stack"
logo = "svgs/onedev.svg"

[[services]]
name = "onedev"
category = "app"
subtype = "docker"
docker_image = "1dev/server:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    hibernate_dialect = "io.onedev.server.persistence.PostgreSQLDialect"
    hibernate_connection_driver_class = "org.postgresql.Driver"
    hibernate_connection_url = "jdbc:postgresql://postgres:5432/onedev"
    hibernate_connection_username = "user"
    hibernate_connection_password = "${{ secret() }}"
    initial_user = "user"
    initial_password = "${{ secret() }}"
    initial_email = "mail@example.com"
    initial_server_url = "https://example.com"
    initial_ssh_root_url = "ssh://changeme:22"
    [[services.storage]]
      host = "onedev-docker-sock"
      container = "/var/run/docker.sock"
    [[services.storage]]
      host = "onedev-data"
      container = "/opt/onedev"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "onedev"
    [[services.storage]]
      host = "onedev-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "onedev"
to = "postgres"
