name = "Openpanel"
description = "Open source alternative to Mixpanel and Plausible for product analytics"
category = "stack"
logo = "svgs/openpanel.svg"

[[services]]
name = "openpanel-dashboard"
category = "app"
subtype = "docker"
docker_image = "lindesvard/openpanel-dashboard:2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NODE_ENV = "production"
    SELF_HOSTED = "true"
    API_URL = "https://example.com"
    DASHBOARD_URL = "https://example.com"
    DATABASE_URL = "postgres:${{ secret() }}@postgres:5432/openpanel-db?schema=public"
    REDIS_URL = "redis:${{ secret() }}@redis:6379"
    CLICKHOUSE_URL = "http://clickhouse:8123/openpanel"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "openpanel-api"
category = "app"
subtype = "docker"
docker_image = "lindesvard/openpanel-api:2"
start_command = "sh -c \"\n  echo 'Running migrations...'\n  CI=true pnpm -r run migrate:deploy\n\n  pnpm start\n\"\n"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NODE_ENV = "production"
    SELF_HOSTED = "true"
    API_URL = "https://example.com"
    DASHBOARD_URL = "https://example.com"
    DATABASE_URL = "postgres:${{ secret() }}@postgres:5432/openpanel-db?schema=public"
    DATABASE_URL_DIRECT = "postgres:${{ secret() }}@postgres:5432/openpanel-db?schema=public"
    REDIS_URL = "redis:${{ secret() }}@redis:6379"
    CLICKHOUSE_URL = "http://clickhouse:8123/openpanel"
    COOKIE_SECRET = "BASE64_GENERATED"
    ALLOW_REGISTRATION = "false"
    ALLOW_INVITATION = "false"
    EMAIL_SENDER = "admin@example.com"
    RESEND_API_KEY = "${{ secret() }}"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "openpanel-worker"
category = "app"
subtype = "docker"
docker_image = "lindesvard/openpanel-worker:2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DISABLE_BULLBOARD = "1"
    NODE_ENV = "production"
    SELF_HOSTED = "true"
    API_URL = "https://example.com"
    DATABASE_URL = "postgres:${{ secret() }}@postgres:5432/openpanel-db?schema=public"
    DATABASE_URL_DIRECT = "postgres:${{ secret() }}@postgres:5432/openpanel-db?schema=public"
    REDIS_URL = "redis:${{ secret() }}@redis:6379"
    CLICKHOUSE_URL = "http://clickhouse:8123/openpanel"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_DB = "openpanel-db"
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "openpanel_postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7.4-alpine"
start_command = "redis-server --requirepass ${SERVICE_PASSWORD_REDIS} --maxmemory-policy noeviction"
source = { type = "docker"  }
  [services.env]
    REDIS_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "openpanel_redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "clickhouse"
category = "app"
subtype = "docker"
docker_image = "clickhouse/clickhouse-server:25.10.2.65"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CLICKHOUSE_SKIP_USER_SETUP = "1"
    [[services.storage]]
      host = "openpanel_clickhouse_data"
      container = "/var/lib/clickhouse"
    [[services.storage]]
      host = "openpanel_clickhouse_logs"
      container = "/var/log/clickhouse-server"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "openpanel-dashboard"
to = "openpanel-api"

[[links]]
from = "openpanel-dashboard"
to = "openpanel-worker"

[[links]]
from = "openpanel-dashboard"
to = "postgres"

[[links]]
from = "openpanel-dashboard"
to = "redis"

[[links]]
from = "openpanel-dashboard"
to = "clickhouse"

[[links]]
from = "openpanel-api"
to = "postgres"

[[links]]
from = "openpanel-api"
to = "clickhouse"

[[links]]
from = "openpanel-api"
to = "redis"

[[links]]
from = "openpanel-worker"
to = "openpanel-api"

[[links]]
from = "openpanel-worker"
to = "postgres"

[[links]]
from = "openpanel-worker"
to = "redis"

[[links]]
from = "openpanel-worker"
to = "clickhouse"

[[links]]
from = "clickhouse"
to = "postgres"

[[links]]
from = "clickhouse"
to = "redis"
