name = "Opnform"
description = "OpnForm is an open-source form builder that lets you create beautiful forms and share them anywhere. It's super fast, you don't need to know how to code"
category = "stack"
logo = "svg/opnform.svg"

[[services]]
name = "opnform-api"
category = "app"
subtype = "docker"
docker_image = "jhumanj/opnform-api:1.12.1"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_NAME = "OpnForm"
    APP_ENV = "production"
    APP_KEY = "BASE64_GENERATED"
    APP_DEBUG = "false"
    APP_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    LOG_CHANNEL = "errorlog"
    LOG_LEVEL = "debug"
    FILESYSTEM_DRIVER = "local"
    LOCAL_FILESYSTEM_VISIBILITY = "public"
    CACHE_DRIVER = "redis"
    QUEUE_CONNECTION = "redis"
    SESSION_DRIVER = "redis"
    SESSION_LIFETIME = "120"
    MAIL_MAILER = "log"
    MAIL_HOST = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    MAIL_PORT = "3000"
    MAIL_USERNAME = "your@email.com"
    MAIL_PASSWORD = "${{ secret() }}"
    MAIL_ENCRYPTION = "MAIL_ENCRYPTION_VALUE"
    MAIL_FROM_ADDRESS = "your@email.com"
    MAIL_FROM_NAME = "OpnForm"
    AWS_ACCESS_KEY_ID = "${{ secret() }}"
    AWS_SECRET_ACCESS_KEY = "${{ secret() }}"
    AWS_DEFAULT_REGION = "us-east-1"
    AWS_BUCKET = "AWS_BUCKET_VALUE"
    OPEN_AI_API_KEY = "${{ secret() }}"
    TELEGRAM_BOT_ID = "TELEGRAM_BOT_ID_VALUE"
    TELEGRAM_BOT_TOKEN = "${{ secret() }}"
    REDIS_HOST = "redis"
    REDIS_PASSWORD = "${{ secret() }}"
    DB_DATABASE = "opnform"
    DB_USERNAME = "${{ linked.postgresql.POSTGRES_USER }}"
    DB_CONNECTION = "pgsql"
    PHP_MEMORY_LIMIT = "1G"
    PHP_MAX_EXECUTION_TIME = "600"
    PHP_UPLOAD_MAX_FILESIZE = "64M"
    PHP_POST_MAX_SIZE = "64M"
    JWT_TTL = "1440"
    JWT_SECRET = "${{ secret() }}"
    JWT_SKIP_IP_UA_VALIDATION = "true"
    H_CAPTCHA_SITE_KEY = "${{ secret() }}"
    H_CAPTCHA_SECRET_KEY = "${{ secret() }}"
    RE_CAPTCHA_SITE_KEY = "${{ secret() }}"
    RE_CAPTCHA_SECRET_KEY = "${{ secret() }}"
    SHOW_OFFICIAL_TEMPLATES = "true"
    [[services.storage]]
      host = "api-storage"
      container = "/usr/share/nginx/html/storage"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 15

[[services]]
name = "api-worker"
category = "app"
subtype = "docker"
docker_image = "jhumanj/opnform-api:1.12.1"
start_command = "php artisan queue:work"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_NAME = "OpnForm"
    APP_ENV = "production"
    APP_KEY = "BASE64_GENERATED"
    APP_DEBUG = "false"
    APP_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    LOG_CHANNEL = "errorlog"
    LOG_LEVEL = "debug"
    FILESYSTEM_DRIVER = "local"
    LOCAL_FILESYSTEM_VISIBILITY = "public"
    CACHE_DRIVER = "redis"
    QUEUE_CONNECTION = "redis"
    SESSION_DRIVER = "redis"
    SESSION_LIFETIME = "120"
    MAIL_MAILER = "log"
    MAIL_HOST = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    MAIL_PORT = "3000"
    MAIL_USERNAME = "your@email.com"
    MAIL_PASSWORD = "${{ secret() }}"
    MAIL_ENCRYPTION = "MAIL_ENCRYPTION_VALUE"
    MAIL_FROM_ADDRESS = "your@email.com"
    MAIL_FROM_NAME = "OpnForm"
    AWS_ACCESS_KEY_ID = "${{ secret() }}"
    AWS_SECRET_ACCESS_KEY = "${{ secret() }}"
    AWS_DEFAULT_REGION = "us-east-1"
    AWS_BUCKET = "AWS_BUCKET_VALUE"
    OPEN_AI_API_KEY = "${{ secret() }}"
    TELEGRAM_BOT_ID = "TELEGRAM_BOT_ID_VALUE"
    TELEGRAM_BOT_TOKEN = "${{ secret() }}"
    REDIS_HOST = "redis"
    REDIS_PASSWORD = "${{ secret() }}"
    DB_DATABASE = "opnform"
    DB_USERNAME = "${{ linked.postgresql.POSTGRES_USER }}"
    DB_CONNECTION = "pgsql"
    PHP_MEMORY_LIMIT = "1G"
    PHP_MAX_EXECUTION_TIME = "600"
    PHP_UPLOAD_MAX_FILESIZE = "64M"
    PHP_POST_MAX_SIZE = "64M"
    [[services.storage]]
      host = "api-storage"
      container = "/usr/share/nginx/html/storage"
  [services.checks]
    enabled = true
    wait = 60
    timeout = 10

[[services]]
name = "api-scheduler"
category = "app"
subtype = "docker"
docker_image = "jhumanj/opnform-api:1.12.1"
start_command = "php artisan schedule:work"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_NAME = "OpnForm"
    APP_ENV = "production"
    APP_KEY = "BASE64_GENERATED"
    APP_DEBUG = "false"
    APP_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    LOG_CHANNEL = "errorlog"
    LOG_LEVEL = "debug"
    FILESYSTEM_DRIVER = "local"
    LOCAL_FILESYSTEM_VISIBILITY = "public"
    CACHE_DRIVER = "redis"
    QUEUE_CONNECTION = "redis"
    SESSION_DRIVER = "redis"
    SESSION_LIFETIME = "120"
    MAIL_MAILER = "log"
    MAIL_HOST = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    MAIL_PORT = "3000"
    MAIL_USERNAME = "your@email.com"
    MAIL_PASSWORD = "${{ secret() }}"
    MAIL_ENCRYPTION = "MAIL_ENCRYPTION_VALUE"
    MAIL_FROM_ADDRESS = "your@email.com"
    MAIL_FROM_NAME = "OpnForm"
    AWS_ACCESS_KEY_ID = "${{ secret() }}"
    AWS_SECRET_ACCESS_KEY = "${{ secret() }}"
    AWS_DEFAULT_REGION = "us-east-1"
    AWS_BUCKET = "AWS_BUCKET_VALUE"
    OPEN_AI_API_KEY = "${{ secret() }}"
    TELEGRAM_BOT_ID = "TELEGRAM_BOT_ID_VALUE"
    TELEGRAM_BOT_TOKEN = "${{ secret() }}"
    REDIS_HOST = "redis"
    REDIS_PASSWORD = "${{ secret() }}"
    DB_DATABASE = "opnform"
    DB_USERNAME = "${{ linked.postgresql.POSTGRES_USER }}"
    DB_CONNECTION = "pgsql"
    PHP_MEMORY_LIMIT = "1G"
    PHP_MAX_EXECUTION_TIME = "600"
    PHP_UPLOAD_MAX_FILESIZE = "64M"
    PHP_POST_MAX_SIZE = "64M"
    [[services.storage]]
      host = "api-storage"
      container = "/usr/share/nginx/html/storage"
  [services.checks]
    enabled = true
    wait = 60
    timeout = 30

[[services]]
name = "opnform-ui"
category = "app"
subtype = "docker"
docker_image = "jhumanj/opnform-client:1.12.1"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NUXT_PUBLIC_APP_URL = "/"
    NUXT_PUBLIC_API_BASE = "/api"
    NUXT_PRIVATE_API_BASE = "http://nginx/api"
    NUXT_PUBLIC_ENV = "production"
    NUXT_PUBLIC_H_CAPTCHA_SITE_KEY = "${{ secret() }}"
    NUXT_PUBLIC_RE_CAPTCHA_SITE_KEY = "${{ secret() }}"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "opnform"
    [[services.storage]]
      host = "opnform-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7"
start_command = "redis-server --requirepass ${{ secret() }}"
source = { type = "docker"  }
  [services.env]
    REDIS_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 30

[[services]]
name = "nginx"
category = "app"
subtype = "docker"
docker_image = "nginx:1.29.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[links]]
from = "opnform-api"
to = "postgresql"

[[links]]
from = "opnform-api"
to = "redis"

[[links]]
from = "api-worker"
to = "postgresql"

[[links]]
from = "api-worker"
to = "redis"

[[links]]
from = "api-scheduler"
to = "postgresql"

[[links]]
from = "api-scheduler"
to = "redis"

[[links]]
from = "opnform-ui"
to = "opnform-api"

[[links]]
from = "nginx"
to = "opnform-api"

[[links]]
from = "nginx"
to = "opnform-ui"

[[links]]
from = "opnform-ui"
to = "postgresql"

[[links]]
from = "opnform-ui"
to = "redis"

[[links]]
from = "nginx"
to = "postgresql"

[[links]]
from = "nginx"
to = "redis"