name = "OrangeHRM open source HR management software."
description = "OrangeHRM open source HR management software."
category = "stack"
logo = "svgs/orangehrm.svg"
[[services]]
name = "orangehrm"
category = "app"
subtype = "docker"
docker_image = "orangehrm/orangehrm:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_ORANGEHRM_80 = ""
    ORANGEHRM_DATABASE_HOST = "mariadb"
    ORANGEHRM_DATABASE_USER = "${SERVICE_USER_MYSQL}"
    ORANGEHRM_DATABASE_PASSWORD = "${SERVICE_PASSWORD_MYSQL}"
    ORANGEHRM_DATABASE_NAME = "${MYSQL_DATABASE:-orangehrm-db}"
    [[services.storage]]
      host = "orangehrm-data"
      container = "/orangehrm"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:11"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "${SERVICE_PASSWORD_MYSQLROOT}"
    MYSQL_DATABASE = "${MYSQL_DATABASE:-orangehrm-db}"
    MYSQL_USER = "${SERVICE_USER_MYSQL}"
    MYSQL_PASSWORD = "${SERVICE_PASSWORD_MYSQL}"
    [[services.storage]]
      host = "orangehrm_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "orangehrm"
to = "mariadb"
