name = "Orangehrm"
description = "OrangeHRM open source HR management software."
category = "stack"
logo = "svgs/orangehrm.svg"

[[services]]
name = "orangehrm"
category = "app"
subtype = "docker"
docker_image = "orangehrm/orangehrm:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    ORANGEHRM_DATABASE_HOST = "mariadb"
    ORANGEHRM_DATABASE_USER = "user"
    ORANGEHRM_DATABASE_PASSWORD = "${{ secret() }}"
    ORANGEHRM_DATABASE_NAME = "orangehrm-db"
    [[services.storage]]
      host = "orangehrm-data"
      container = "/orangehrm"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "orangehrm-db"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "orangehrm_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "orangehrm"
to = "mariadb"