name = "Osticket"
description = "osTicket is a widely-used open source support ticket system."
category = "stack"
logo = "svgs/osticket.png"

[[services]]
name = "osticket"
category = "app"
subtype = "docker"
docker_image = "tiredofit/osticket:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_URL = "https://example.com"
    CRON_INTERVAL = "10"
    DB_HOST = "mariadb"
    DB_NAME = "osticket-db"
    DB_USER = "user"
    DB_PASS = "CHANGE_ME"
    INSTALL_SECRET = "CHANGE_ME"
    ADMIN_FIRSTNAME = "Admin"
    ADMIN_LASTNAME = "istrator"
    ADMIN_EMAIL = "admin@example.com"
    ADMIN_USER = "user"
    ADMIN_PASS = "CHANGE_ME"
    [[services.storage]]
      host = "osticket-data"
      container = "/www/osticket"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:11"
source = { type = "docker"  }
  [services.env]
    MARIADB_ROOT_PASSWORD = "CHANGE_ME"
    MARIADB_DATABASE = "osticket-db"
    MARIADB_USER = "user"
    MARIADB_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "osticket-mariadb-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "osticket"
to = "mariadb"

[[links]]
from = "mariadb"
to = "osticket"
