name = "Owncloud"
description = "OwnCloud with Open Web UI integrates file management with a powerful, user-friendly interface."
category = "stack"
logo = "svgs/owncloud.svg"

[[services]]
name = "owncloud"
category = "app"
subtype = "docker"
docker_image = "owncloud/server:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    OWNCLOUD_DOMAIN = "https://example.com"
    OWNCLOUD_TRUSTED_DOMAINS = "https://example.com"
    OWNCLOUD_DB_TYPE = "mysql"
    OWNCLOUD_DB_HOST = "mariadb"
    OWNCLOUD_DB_NAME = "owncloud"
    OWNCLOUD_DB_USERNAME = "user"
    OWNCLOUD_DB_PASSWORD = "${{ secret() }}"
    OWNCLOUD_ADMIN_USERNAME = "user"
    OWNCLOUD_ADMIN_PASSWORD = "${{ secret() }}"
    OWNCLOUD_MYSQL_UTF8MB4 = "true"
    OWNCLOUD_REDIS_ENABLED = "true"
    OWNCLOUD_REDIS_HOST = "redis"
    [[services.storage]]
      host = "owncloud-data"
      container = "/mnt/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:latest"
start_command = "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin --max-allowed-packet=128M --innodb-log-file-size=64M"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "owncloud"
    TZ = "auto"
    [[services.storage]]
      host = "owncloud-mysql-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:6"
start_command = "--databases 1"
source = { type = "docker"  }
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "owncloud"
to = "mariadb"

[[links]]
from = "owncloud"
to = "redis"
