name = "Passbolt"
description = "Passbolt Community Edition (CE) API. The JSON API for the open source password manager for teams!"
category = "stack"
logo = "svgs/passbolt.svg"

[[services]]
name = "passbolt"
category = "app"
subtype = "docker"
docker_image = "passbolt/passbolt:latest-ce"
start_command = "/usr/bin/wait-for.sh -t 0 mariadb:3306 -- /docker-entrypoint.sh"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_FULL_BASE_URL = "https://example.com"
    DATASOURCES_DEFAULT_HOST = "mariadb"
    DATASOURCES_DEFAULT_USERNAME = "user"
    DATASOURCES_DEFAULT_PASSWORD = "${{ secret() }}"
    DATASOURCES_DEFAULT_DATABASE = "passbolt-db"
    [[services.storage]]
      host = "gpg_volume"
      container = "/etc/passbolt/gpg"
    [[services.storage]]
      host = "jwt_volume"
      container = "/etc/passbolt/jwt"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
  [services.env]
    MARIADB_ROOT_PASSWORD = "${{ secret() }}"
    MARIADB_DATABASE = "passbolt-db"
    MARIADB_USER = "user"
    MARIADB_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "passbolt_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "passbolt"
to = "mariadb"