name = "Peppermint"
description = "Open source helpdesk solution designed to enhance the user experience for teams currently utilizing costly software alternatives"
category = "stack"
logo = "svgs/peppermint.png"

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "peppermint-db"
    [[services.storage]]
      host = "peppermint-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "peppermint"
category = "app"
subtype = "docker"
docker_image = "pepperlabs/peppermint:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DB_USERNAME = "${{ linked.postgres.POSTGRES_USER }}"
    SECRET = "${{ secret() }}"
    API_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[links]]
from = "peppermint"
to = "postgres"