name = "Pgadmin"
description = "pgAdmin is a web-based database management tool for administering your PostgreSQL databases through a user-friendly interface."
category = "stack"
logo = "svgs/postgresql.svg"

[[services]]
name = "pgadmin"
category = "app"
subtype = "docker"
docker_image = "dpage/pgadmin4:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PGADMIN_DEFAULT_EMAIL = "${PGADMIN_DEFAULT_EMAIL:?}"
    PGADMIN_DEFAULT_PASSWORD = "${PGADMIN_DEFAULT_PASSWORD:?}"
    [[services.storage]]
      host = "pgadmin-data"
      container = "/var/lib/pgadmin"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10
