name = "Pgbackweb"
description = "Effortless PostgreSQL backups with a user-friendly web interface!"
category = "stack"
logo = "svgs/pgbackweb.svg"

[[services]]
name = "pgbackweb"
category = "app"
subtype = "docker"
docker_image = "eduardolat/pgbackweb:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PBW_ENCRYPTION_KEY = "${{ secret() }}"
    PBW_POSTGRES_CONN_STRING = "postgresql://user:${{ secret() }}@postgres:5432/pgbackweb-db?sslmode=disable"
    TZ = "UTC"
    [[services.storage]]
      host = "pgbackweb_backups"
      container = "/backups"

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "pgbackweb-db"
    [[services.storage]]
      host = "pgbackweb_postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "pgbackweb"
to = "postgres"