name = "Plane"
description = "The open source project management tool"
category = "stack"
logo = "svgs/plane.svg"

[[services]]
name = "proxy"
category = "app"
subtype = "docker"
docker_image = "makeplane/plane-proxy:${APP_RELEASE:-v1.3.0}"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_DOMAIN = "https://example.com"
    SITE_ADDRESS = ":80"
    FILE_SIZE_LIMIT = "5242880"
    BUCKET_NAME = "uploads"
    [[services.storage]]
      host = "proxy_config"
      container = "/config"
    [[services.storage]]
      host = "proxy_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "web"
category = "app"
subtype = "docker"
docker_image = "makeplane/plane-frontend:${APP_RELEASE:-v1.3.0}"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "space"
category = "app"
subtype = "docker"
docker_image = "makeplane/plane-space:${APP_RELEASE:-v1.3.0}"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "admin"
category = "app"
subtype = "docker"
docker_image = "makeplane/plane-admin:${APP_RELEASE:-v1.3.0}"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "live"
category = "app"
subtype = "docker"
docker_image = "makeplane/plane-live:${APP_RELEASE:-v1.3.0}"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    REDIS_HOST = "plane-redis"
    REDIS_PORT = "6379"
    REDIS_URL = "redis://plane-redis:6379/"
    API_BASE_URL = "http://api:8000"
    LIVE_SERVER_SECRET_KEY = "$SERVICE_PASSWORD_64_LIVESECRET"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "api"
category = "app"
subtype = "docker"
docker_image = "makeplane/plane-backend:${APP_RELEASE:-v1.3.0}"
start_command = "./bin/docker-entrypoint-api.sh"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_DOMAIN = "https://example.com"
    FILE_SIZE_LIMIT = "5242880"
    BUCKET_NAME = "uploads"
    SITE_ADDRESS = ":80"
    AWS_ACCESS_KEY_ID = "$SERVICE_USER_MINIO"
    AWS_SECRET_ACCESS_KEY = "$SERVICE_PASSWORD_MINIO"
    AWS_S3_ENDPOINT_URL = "http://plane-minio:9000"
    AWS_S3_BUCKET_NAME = "uploads"
    MINIO_ROOT_USER = "$SERVICE_USER_MINIO"
    MINIO_ROOT_PASSWORD = "$SERVICE_PASSWORD_MINIO"
    REDIS_HOST = "plane-redis"
    REDIS_PORT = "6379"
    REDIS_URL = "redis://plane-redis:6379/"
    PGHOST = "plane-db"
    PGDATABASE = "plane"
    POSTGRES_USER = "$SERVICE_USER_POSTGRES"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    POSTGRES_DB = "plane"
    POSTGRES_PORT = "5432"
    PGDATA = "/var/lib/postgresql/data"
    APP_RELEASE = "v1.3.0"
    WEB_URL = "https://example.com"
    DEBUG = "0"
    CORS_ALLOWED_ORIGINS = "http://localhost"
    GUNICORN_WORKERS = "1"
    USE_MINIO = "1"
    DATABASE_URL = "postgresql://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@plane-db/plane"
    SECRET_KEY = "$SERVICE_PASSWORD_64_SECRETKEY"
    AMQP_URL = "amqp://user:CHANGE_ME@plane-mq:5672/plane"
    API_KEY_RATE_LIMIT = "60/minute"
    MINIO_ENDPOINT_SSL = "0"
    LIVE_SERVER_SECRET_KEY = "$SERVICE_PASSWORD_64_LIVESECRET"
    [[services.storage]]
      host = "logs_api"
      container = "/code/plane/logs"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "worker"
category = "app"
subtype = "docker"
docker_image = "makeplane/plane-backend:${APP_RELEASE:-v1.3.0}"
start_command = "./bin/docker-entrypoint-worker.sh"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_DOMAIN = "https://example.com"
    FILE_SIZE_LIMIT = "5242880"
    BUCKET_NAME = "uploads"
    SITE_ADDRESS = ":80"
    AWS_ACCESS_KEY_ID = "$SERVICE_USER_MINIO"
    AWS_SECRET_ACCESS_KEY = "$SERVICE_PASSWORD_MINIO"
    AWS_S3_ENDPOINT_URL = "http://plane-minio:9000"
    AWS_S3_BUCKET_NAME = "uploads"
    MINIO_ROOT_USER = "$SERVICE_USER_MINIO"
    MINIO_ROOT_PASSWORD = "$SERVICE_PASSWORD_MINIO"
    REDIS_HOST = "plane-redis"
    REDIS_PORT = "6379"
    REDIS_URL = "redis://plane-redis:6379/"
    PGHOST = "plane-db"
    PGDATABASE = "plane"
    POSTGRES_USER = "$SERVICE_USER_POSTGRES"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    POSTGRES_DB = "plane"
    POSTGRES_PORT = "5432"
    PGDATA = "/var/lib/postgresql/data"
    APP_RELEASE = "v1.3.0"
    WEB_URL = "https://example.com"
    DEBUG = "0"
    CORS_ALLOWED_ORIGINS = "http://localhost"
    GUNICORN_WORKERS = "1"
    USE_MINIO = "1"
    DATABASE_URL = "postgresql://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@plane-db/plane"
    SECRET_KEY = "$SERVICE_PASSWORD_64_SECRETKEY"
    AMQP_URL = "amqp://user:CHANGE_ME@plane-mq:5672/plane"
    API_KEY_RATE_LIMIT = "60/minute"
    MINIO_ENDPOINT_SSL = "0"
    LIVE_SERVER_SECRET_KEY = "$SERVICE_PASSWORD_64_LIVESECRET"
    [[services.storage]]
      host = "logs_worker"
      container = "/code/plane/logs"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "beat-worker"
category = "app"
subtype = "docker"
docker_image = "makeplane/plane-backend:${APP_RELEASE:-v1.3.0}"
start_command = "./bin/docker-entrypoint-beat.sh"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_DOMAIN = "https://example.com"
    FILE_SIZE_LIMIT = "5242880"
    BUCKET_NAME = "uploads"
    SITE_ADDRESS = ":80"
    AWS_ACCESS_KEY_ID = "$SERVICE_USER_MINIO"
    AWS_SECRET_ACCESS_KEY = "$SERVICE_PASSWORD_MINIO"
    AWS_S3_ENDPOINT_URL = "http://plane-minio:9000"
    AWS_S3_BUCKET_NAME = "uploads"
    MINIO_ROOT_USER = "$SERVICE_USER_MINIO"
    MINIO_ROOT_PASSWORD = "$SERVICE_PASSWORD_MINIO"
    REDIS_HOST = "plane-redis"
    REDIS_PORT = "6379"
    REDIS_URL = "redis://plane-redis:6379/"
    PGHOST = "plane-db"
    PGDATABASE = "plane"
    POSTGRES_USER = "$SERVICE_USER_POSTGRES"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    POSTGRES_DB = "plane"
    POSTGRES_PORT = "5432"
    PGDATA = "/var/lib/postgresql/data"
    APP_RELEASE = "v1.3.0"
    WEB_URL = "https://example.com"
    DEBUG = "0"
    CORS_ALLOWED_ORIGINS = "http://localhost"
    GUNICORN_WORKERS = "1"
    USE_MINIO = "1"
    DATABASE_URL = "postgresql://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@plane-db/plane"
    SECRET_KEY = "$SERVICE_PASSWORD_64_SECRETKEY"
    AMQP_URL = "amqp://user:CHANGE_ME@plane-mq:5672/plane"
    API_KEY_RATE_LIMIT = "60/minute"
    MINIO_ENDPOINT_SSL = "0"
    LIVE_SERVER_SECRET_KEY = "$SERVICE_PASSWORD_64_LIVESECRET"
    [[services.storage]]
      host = "logs_beat-worker"
      container = "/code/plane/logs"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "plane-db"
category = "database"
subtype = "postgres"
docker_image = "postgres:15.7-alpine"
start_command = "postgres -c 'max_connections=1000'"
source = { type = "docker"  }
  [services.env]
    PGHOST = "plane-db"
    PGDATABASE = "plane"
    POSTGRES_USER = "$SERVICE_USER_POSTGRES"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    POSTGRES_DB = "plane"
    POSTGRES_PORT = "5432"
    PGDATA = "/var/lib/postgresql/data"
    [[services.storage]]
      host = "pgdata"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "plane-redis"
category = "app"
subtype = "docker"
docker_image = "valkey/valkey:7.2.11-alpine"
source = { type = "docker"  }
  [services.scaling]
    web = 1
    [[services.storage]]
      host = "redisdata"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "plane-mq"
category = "queue"
subtype = "rabbitmq"
docker_image = "rabbitmq:3.13.6-management-alpine"
source = { type = "docker"  }
  [services.env]
    RABBITMQ_HOST = "plane-mq"
    RABBITMQ_PORT = "5672"
    RABBITMQ_DEFAULT_USER = "user"
    RABBITMQ_DEFAULT_PASS = "CHANGE_ME"
    RABBITMQ_DEFAULT_VHOST = "plane"
    RABBITMQ_VHOST = "plane"
    [[services.storage]]
      host = "rabbitmq_data"
      container = "/var/lib/rabbitmq"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 30

[[services]]
name = "plane-minio"
category = "service"
subtype = "s3"
docker_image = "ghcr.io/coollabsio/minio:RELEASE.2025-10-15T17-29-55Z"
start_command = "server /export --console-address \":9090\""
source = { type = "docker"  }
  [services.env]
    MINIO_ROOT_USER = "$SERVICE_USER_MINIO"
    MINIO_ROOT_PASSWORD = "$SERVICE_PASSWORD_MINIO"
    [[services.storage]]
      host = "uploads"
      container = "/export"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "proxy"
to = "web"

[[links]]
from = "proxy"
to = "api"

[[links]]
from = "proxy"
to = "space"

[[links]]
from = "proxy"
to = "admin"

[[links]]
from = "proxy"
to = "live"

[[links]]
from = "web"
to = "api"

[[links]]
from = "web"
to = "worker"

[[links]]
from = "space"
to = "api"

[[links]]
from = "space"
to = "worker"

[[links]]
from = "space"
to = "web"

[[links]]
from = "admin"
to = "api"

[[links]]
from = "admin"
to = "web"

[[links]]
from = "live"
to = "api"

[[links]]
from = "live"
to = "web"

[[links]]
from = "api"
to = "plane-db"

[[links]]
from = "api"
to = "plane-redis"

[[links]]
from = "api"
to = "plane-mq"

[[links]]
from = "worker"
to = "api"

[[links]]
from = "worker"
to = "plane-db"

[[links]]
from = "worker"
to = "plane-redis"

[[links]]
from = "worker"
to = "plane-mq"

[[links]]
from = "beat-worker"
to = "api"

[[links]]
from = "beat-worker"
to = "plane-db"

[[links]]
from = "beat-worker"
to = "plane-redis"

[[links]]
from = "beat-worker"
to = "plane-mq"

[[links]]
from = "migrator"
to = "plane-db"

[[links]]
from = "migrator"
to = "plane-redis"
