name = "Plunk"
description = "Plunk, The Open-Source Email Platform for AWS"
category = "stack"
logo = "svgs/plunk.svg"

[[services]]
name = "plunk"
category = "app"
subtype = "docker"
docker_image = "driaug/plunk:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    REDIS_URL = "redis://redis:6379"
    DATABASE_URL = "postgresql://user:CHANGE_ME@postgresql/plunk-db?schema=public"
    JWT_SECRET = "${{ secret() }}"
    AWS_REGION = "${AWS_REGION:?}"
    AWS_ACCESS_KEY_ID = "${AWS_ACCESS_KEY_ID:?}"
    AWS_SECRET_ACCESS_KEY = "${AWS_SECRET_ACCESS_KEY:?}"
    AWS_SES_CONFIGURATION_SET = "${AWS_SES_CONFIGURATION_SET:?}"
    NEXT_PUBLIC_API_URI = "https://example.com/api"
    APP_URI = "https://example.com"
    API_URI = "https://example.com/api"
    DISABLE_SIGNUPS = "False"
    NODE_OPTIONS = "--no-network-family-autoselection"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "plunk-db"
    [[services.storage]]
      host = "plunk-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7.4-alpine"
source = { type = "docker"  }
    [[services.storage]]
      host = "plunk-redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "plunk"
to = "postgresql"

[[links]]
from = "plunk"
to = "redis"