name = "A simple and secure OIDC provider with passkey authentication"
description = "A simple and secure OIDC provider with passkey authentication"
category = "stack"
logo = "svgs/pocketid-logo.png"
[[services]]
name = "pocket-id"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/pocket-id/pocket-id:v1.13"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_POCKETID_1411 = ""
    APP_URL = "${SERVICE_URL_POCKETID}"
    TRUST_PROXY = "${TRUST_PROXY:-true}"
    MAXMIND_LICENSE_KEY = "${MAXMIND_LICENSE_KEY}"
    SMTP_HOST = "${SMTP_HOST}"
    SMTP_PORT = "${SMTP_PORT:-587}"
    SMTP_FROM = "${SMTP_FROM}"
    SMTP_USER = "${SMTP_USER}"
    SMTP_PASSWORD = "${SMTP_PASSWORD}"
    SMTP_TLS = "${SMTP_TLS:-starttls}"
    SMTP_SKIP_CERT_VERIFY = "${SMTP_SKIP_CERT_VERIFY:-false}"
    EMAIL_LOGIN_NOTIFICATION_ENABLED = "${EMAIL_LOGIN_NOTIFICATION_ENABLED:-false}"
    EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED = "${EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED:-false}"
    EMAIL_API_KEY_EXPIRATION_ENABLED = "${EMAIL_API_KEY_EXPIRATION_ENABLED:-false}"
    PUID = "${PUID:-1000}"
    PGID = "${PGID:-1000}"
    [[services.storage]]
      host = "pocket-id-data"
      container = "/app/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5
