name = "Pocket Id"
description = "A simple and secure OIDC provider with passkey authentication"
category = "stack"
logo = "svgs/pocketid-logo.png"

[[services]]
name = "pocket-id"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/pocket-id/pocket-id:v1.13"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_URL = "https://example.com"
    TRUST_PROXY = "true"
    MAXMIND_LICENSE_KEY = "CHANGE_ME"
    SMTP_HOST = "https://example.com"
    SMTP_PORT = "587"
    SMTP_FROM = "SMTP_FROM_VALUE"
    SMTP_USER = "SMTP_USER_VALUE"
    SMTP_PASSWORD = "CHANGE_ME"
    SMTP_TLS = "starttls"
    SMTP_SKIP_CERT_VERIFY = "false"
    EMAIL_LOGIN_NOTIFICATION_ENABLED = "false"
    EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED = "false"
    EMAIL_API_KEY_EXPIRATION_ENABLED = "false"
    PUID = "1000"
    PGID = "1000"
    [[services.storage]]
      host = "pocket-id-data"
      container = "/app/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5
