name = "Postiz"
description = "Open source social media scheduling tool."
category = "stack"
logo = "svgs/postiz.svg"

[[services]]
name = "postiz"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/gitroomhq/postiz-app:v2.10.1"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    MAIN_URL = "https://example.com"
    FRONTEND_URL = "https://example.com"
    NEXT_PUBLIC_BACKEND_URL = "https://example.com/api"
    JWT_SECRET = "${{ secret() }}"
    DATABASE_URL = "postgresql://postgres:CHANGE_ME@postgres:5432/postiz-db"
    REDIS_URL = "redis:${{ secret() }}@redis:6379"
    BACKEND_INTERNAL_URL = "http://localhost:3000"
    CLOUDFLARE_ACCOUNT_ID = "CLOUDFLARE_ACCOUNT_ID_VALUE"
    CLOUDFLARE_ACCESS_KEY = "${{ secret() }}"
    CLOUDFLARE_SECRET_ACCESS_KEY = "${{ secret() }}"
    CLOUDFLARE_BUCKETNAME = "CLOUDFLARE_BUCKETNAME_VALUE"
    CLOUDFLARE_BUCKET_URL = "https://example.com"
    CLOUDFLARE_REGION = "CLOUDFLARE_REGION_VALUE"
    STORAGE_PROVIDER = "local"
    UPLOAD_DIRECTORY = "/uploads"
    NEXT_PUBLIC_UPLOAD_DIRECTORY = "/uploads"
    NEXT_PUBLIC_UPLOAD_STATIC_DIRECTORY = "NEXT_PUBLIC_UPLOAD_STATIC_DIRECTORY_VALUE"
    RESEND_API_KEY = "${{ secret() }}"
    EMAIL_FROM_ADDRESS = "admin@example.com"
    EMAIL_FROM_NAME = "admin@example.com"
    EMAIL_PROVIDER = "admin@example.com"
    X_API_KEY = "SERVICE_X_API_VALUE"
    X_API_SECRET = "${{ secret() }}"
    LINKEDIN_CLIENT_ID = "SERVICE_LINKEDIN_ID_VALUE"
    LINKEDIN_CLIENT_SECRET = "${{ secret() }}"
    REDDIT_CLIENT_ID = "SERVICE_REDDIT_API_VALUE"
    REDDIT_CLIENT_SECRET = "${{ secret() }}"
    GITHUB_CLIENT_ID = "SERVICE_GITHUB_ID_VALUE"
    GITHUB_CLIENT_SECRET = "${{ secret() }}"
    THREADS_APP_ID = "SERVICE_THREADS_ID_VALUE"
    THREADS_APP_SECRET = "${{ secret() }}"
    FACEBOOK_APP_ID = "SERVICE_FACEBOOK_ID_VALUE"
    FACEBOOK_APP_SECRET = "${{ secret() }}"
    YOUTUBE_CLIENT_ID = "SERVICE_YOUTUBE_ID_VALUE"
    YOUTUBE_CLIENT_SECRET = "${{ secret() }}"
    TIKTOK_CLIENT_ID = "SERVICE_TIKTOK_ID_VALUE"
    TIKTOK_CLIENT_SECRET = "${{ secret() }}"
    PINTEREST_CLIENT_ID = "SERVICE_PINTEREST_ID_VALUE"
    PINTEREST_CLIENT_SECRET = "${{ secret() }}"
    DRIBBBLE_CLIENT_ID = "SERVICE_DRIBBLE_ID_VALUE"
    DRIBBBLE_CLIENT_SECRET = "${{ secret() }}"
    DISCORD_CLIENT_ID = "SERVICE_DISCORD_ID_VALUE"
    DISCORD_CLIENT_SECRET = "${{ secret() }}"
    DISCORD_BOT_TOKEN_ID = "${{ secret() }}"
    SLACK_ID = "SERVICE_SLACK_ID_VALUE"
    SLACK_SECRET = "${{ secret() }}"
    SLACK_SIGNING_SECRET = "${{ secret() }}"
    MASTODON_CLIENT_ID = "SERVICE_MASTODON_ID_VALUE"
    MASTODON_CLIENT_SECRET = "${{ secret() }}"
    INSTAGRAM_APP_ID = "INSTAGRAM_APP_ID_VALUE"
    INSTAGRAM_APP_SECRET = "${{ secret() }}"
    BEEHIIVE_API_KEY = "${{ secret() }}"
    BEEHIIVE_PUBLICATION_ID = "SERVICE_BEEHIIVE_PUBID_VALUE"
    OPENAI_API_KEY = "${{ secret() }}"
    NEXT_PUBLIC_DISCORD_SUPPORT = "3000"
    NEXT_PUBLIC_POLOTNO = "NEXT_PUBLIC_POLOTNO_VALUE"
    IS_GENERAL = "true"
    NX_ADD_PLUGINS = "false"
    NOT_SECURED = "false"
    FEE_AMOUNT = "0.05"
    STRIPE_PUBLISHABLE_KEY = "${{ secret() }}"
    STRIPE_SECRET_KEY = "${{ secret() }}"
    STRIPE_SIGNING_KEY = "${{ secret() }}"
    STRIPE_SIGNING_KEY_CONNECT = "${{ secret() }}"
    [[services.storage]]
      host = "postiz_config"
      container = "/config/"
    [[services.storage]]
      host = "postiz_uploads"
      container = "/uploads/"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "postgres"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "postiz-db"
    [[services.storage]]
      host = "postiz_postgresql_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7.2"
start_command = "redis-server --requirepass ${SERVICE_PASSWORD_REDIS}"
source = { type = "docker"  }
  [services.env]
    REDIS_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "postiz_redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "postiz"
to = "postgres"

[[links]]
from = "postiz"
to = "redis"