name = "Proxyscotch"
description = "A simple proxy server created for https://hoppscotch.io - CORS proxy"
category = "stack"
logo = "svgs/hoppscotch.png"

[[services]]
name = "proxyscotch"
category = "app"
subtype = "docker"
docker_image = "hoppscotch/proxyscotch:v0.1.4"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PROXYSCOTCH_TOKEN = "CHANGE_ME"
    PROXYSCOTCH_ALLOWED_ORIGINS = "*"
    PROXYSCOTCH_BANNED_OUTPUTS = "BANNED_OUTPUTS_VALUE"
    PROXYSCOTCH_BANNED_DESTS = "BANNED_DESTS_VALUE"
