name = "Pterodactyl Panel"
description = "Pterodactyl is a free, open-source game server management panel"
category = "stack"
logo = "svgs/pterodactyl.png"

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "pterodactyl-db"
    MYSQL_USER = "${{ secret() }}"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "pterodactyl-db"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 1

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:alpine"
source = { type = "docker"  }
  [services.checks]
    enabled = true
    wait = 10
    timeout = 1

[[services]]
name = "pterodactyl"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/pterodactyl/panel:v1.12.0"
start_command = "/entrypoint.sh"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    HASHIDS_SALT = "${{ secret() }}"
    HASHIDS_LENGTH = "8"
    ADMIN_EMAIL = "admin@example.com"
    ADMIN_USERNAME = "user"
    ADMIN_FIRSTNAME = "Admin"
    ADMIN_LASTNAME = "User"
    ADMIN_PASSWORD = "${{ secret() }}"
    PTERODACTYL_HTTPS = "false"
    APP_ENV = "production"
    APP_ENVIRONMENT_ONLY = "false"
    APP_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    APP_TIMEZONE = "UTC"
    APP_SERVICE_AUTHOR = "author@example.com"
    LOG_LEVEL = "debug"
    CACHE_DRIVER = "redis"
    SESSION_DRIVER = "redis"
    QUEUE_DRIVER = "redis"
    REDIS_HOST = "redis"
    DB_DATABASE = "pterodactyl-db"
    DB_USERNAME = "${{ linked.mariadb.MYSQL_USER }}"
    MAIL_FROM = "$MAIL_FROM"
    MAIL_DRIVER = "$MAIL_DRIVER"
    MAIL_HOST = "$MAIL_HOST"
    MAIL_PORT = "$MAIL_PORT"
    MAIL_USERNAME = "$MAIL_USERNAME"
    MAIL_PASSWORD = "$MAIL_PASSWORD"
    MAIL_ENCRYPTION = "$MAIL_ENCRYPTION"
    [[services.storage]]
      host = "panel-var"
      container = "/app/var/"
    [[services.storage]]
      host = "panel-nginx"
      container = "/etc/nginx/http.d/"
    [[services.storage]]
      host = "panel-certs"
      container = "/etc/letsencrypt/"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 1

[[links]]
from = "pterodactyl"
to = "mariadb"

[[links]]
from = "pterodactyl"
to = "redis"