name = "Pydio Cells"
description = "High-performance large file sharing, native no-code automation, and a collaboration-centric architecture that simplifies access control without compromising security or compliance."
category = "stack"
logo = "svgs/cells.svg"

[[services]]
name = "cells"
category = "app"
subtype = "docker"
docker_image = "pydio/cells:4.4"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CELLS_SITE_EXTERNAL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    CELLS_SITE_NO_TLS = "1"
    [[services.storage]]
      host = "cells_data"
      container = "/var/cells"

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "cells"
    MYSQL_USER = "${{ secret() }}"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "mysql_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 20

[[links]]
from = "cells"
to = "mariadb"