name = "Qbittorrent"
description = "The qBittorrent project aims to provide an open-source software alternative to μTorrent."
category = "stack"
logo = "svgs/qbittorrent.svg"

[[services]]
name = "qbit"
category = "app"
subtype = "docker"
docker_image = "lscr.io/linuxserver/qbittorrent:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    WEBUI_PORT = "8080"
    PUID = "1000"
    PGID = "1000"
    [[services.storage]]
      host = "qbittorrent-config"
      container = "/config"
    [[services.storage]]
      host = "qbittorrent-downloads"
      container = "/downloads"
    [[services.storage]]
      host = "qbittorrent-torrents"
      container = "/torrents"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "vuetorrent-backend"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/vuetorrent/vuetorrent-backend:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PORT = "8080"
    QBIT_BASE = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    RELEASE_TYPE = "stable"
    UPDATE_VT_CRON = "\"0 * * * *\""
    [[services.storage]]
      host = "vuetorrent-config"
      container = "/config"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
