name = "Rabbitmq"
description = "With tens of thousands of users, RabbitMQ is one of the most popular open source message brokers."
category = "stack"
logo = "svgs/rabbitmq.svg"

[[services]]
name = "rabbitmq"
category = "queue"
subtype = "rabbitmq"
docker_image = "rabbitmq:3-management"
source = { type = "docker"  }
  [services.env]
    RABBITMQ_DEFAULT_USER = "$SERVICE_USER_RABBITMQ"
    RABBITMQ_DEFAULT_PASS = "$SERVICE_PASSWORD_RABBITMQ"
    PORT = "5672"
  [services.proxy]
    enabled = true
    type = "traefik"
    [[services.proxy.ports]]
      host = 0
      container = 5672
    [[services.storage]]
      host = "rabbitmq-data"
      container = "/var/lib/rabbitmq/"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30
