name = "Rallly"
description = "Rallly is an open-source scheduling and collaboration tool designed to make organizing events and meetings easier."
category = "stack"
logo = "svgs/rallly.svg"

[[services]]
name = "rallly_db"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_DB = "rallly"
    [[services.storage]]
      host = "rallly_db_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "rallly"
category = "app"
subtype = "docker"
docker_image = "lukevella/rallly:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_PASSWORD = "${{ secret() }}"
    NEXT_PUBLIC_BASE_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    ALLOWED_EMAILS = "admin@example.com"
    SUPPORT_EMAIL = "support@example.com"
    SMTP_HOST = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    SMTP_PORT = "3000"
    SMTP_SECURE = "false"
    SMTP_USER = "SMTP_USER_VALUE"
    SMTP_PWD = "SMTP_PWD_VALUE"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "rallly"
to = "rallly_db"