name = "Rallly is an open-source scheduling and collaboration tool designed to make organizing events and meetings easier."
description = "Rallly is an open-source scheduling and collaboration tool designed to make organizing events and meetings easier."
category = "stack"
logo = "svgs/rallly.svg"
[[services]]
name = "rallly_db"
category = "database"
subtype = "postgres"
docker_image = "postgres:14.2"
source = { type = "docker"  }
  [services.env]
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    POSTGRES_USER = "${SERVICE_USER_POSTGRES}"
    POSTGRES_DB = "${POSTGRES_DB:-rallly}"
    [[services.storage]]
      host = "rallly_db_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "rallly"
category = "app"
subtype = "docker"
docker_image = "lukevella/rallly:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_RALLLY_3000 = ""
    DATABASE_URL = "postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@rallly_db:5432/${POSTGRES_DB:-rallly}"
    SECRET_PASSWORD = "${SERVICE_PASSWORD_64_RALLLY}"
    NEXT_PUBLIC_BASE_URL = "${SERVICE_URL_RALLLY}"
    ALLOWED_EMAILS = "${ALLOWED_EMAILS}"
    SUPPORT_EMAIL = "${SUPPORT_EMAIL:-support@example.com}"
    SMTP_HOST = "${SMTP_HOST}"
    SMTP_PORT = "${SMTP_PORT}"
    SMTP_SECURE = "${SMTP_SECURE:-false}"
    SMTP_USER = "${SMTP_USER}"
    SMTP_PWD = "${SMTP_PWD}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "rallly"
to = "rallly_db"
