name = "Reactive Resume"
description = "A one-of-a-kind resume builder that keeps your privacy in mind."
category = "stack"
logo = "svgs/rxresume.svg"

[[services]]
name = "reactive-resume"
category = "app"
subtype = "docker"
docker_image = "amruthpillai/reactive-resume:v4.3.7"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PUBLIC_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    STORAGE_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    ACCESS_TOKEN_SECRET = "${{ secret() }}"
    REFRESH_TOKEN_SECRET = "${{ secret() }}"
    CHROME_TOKEN = "${{ secret() }}"
    CHROME_URL = "ws://chrome:3000/chrome"
    REDIS_URL = "redis://redis:6379"
    STORAGE_ENDPOINT = "minio"
    STORAGE_PORT = "9000"
    STORAGE_REGION = "us-east-1"
    STORAGE_BUCKET = "default"
    STORAGE_ACCESS_KEY = "${{ linked.minio.MINIO_ROOT_USER }}"
    STORAGE_SECRET_KEY = "${{ linked.minio.MINIO_ROOT_PASSWORD }}"
    STORAGE_USE_SSL = "false"
    DISABLE_SIGNUPS = "false"
    DISABLE_EMAIL_AUTH = "false"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 3

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_DB = "postgres"
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "minio"
category = "service"
subtype = "s3"
docker_image = "ghcr.io/coollabsio/minio:RELEASE.2025-10-15T17-29-55Z"
start_command = "server /data --console-address \":9001\""
source = { type = "docker"  }
  [services.env]
    MINIO_SERVER_URL = "$MINIO_SERVER_URL"
    MINIO_BROWSER_REDIRECT_URL = "$MINIO_BROWSER_REDIRECT_URL"
    MINIO_ROOT_USER = "${{ secret() }}"
    MINIO_ROOT_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "minio-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "chrome"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/browserless/chrome:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    HEALTH = "true"
    TIMEOUT = "10000"
    CONCURRENT = "10"
    TOKEN = "${{ secret() }}"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 3

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
start_command = "redis-server"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "reactive-resume"
to = "postgres"

[[links]]
from = "reactive-resume"
to = "minio"

[[links]]
from = "reactive-resume"
to = "chrome"

[[links]]
from = "reactive-resume"
to = "redis"

[[links]]
from = "chrome"
to = "postgres"

[[links]]
from = "chrome"
to = "redis"