name = "Redmine"
description = "Redmine is a flexible project management web application."
category = "stack"
logo = "svgs/redmine.svg"

[[services]]
name = "redmine"
category = "app"
subtype = "docker"
docker_image = "redmine:6-alpine"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY_BASE = "CHANGE_ME"
    REDMINE_DB_POSTGRES = "postgresql"
    REDMINE_DB_PORT = "5432"
    REDMINE_DB_USERNAME = "user"
    REDMINE_DB_PASSWORD = "CHANGE_ME"
    REDMINE_DB_DATABASE = "redmine-db"
    [[services.storage]]
      host = "redmine-config"
      container = "/usr/src/redmine/config"
    [[services.storage]]
      host = "redmine-files"
      container = "/usr/src/redmine/files"
    [[services.storage]]
      host = "redmine-themes"
      container = "/usr/src/redmine/themes"
    [[services.storage]]
      host = "redmine-plugins"
      container = "/usr/src/redmine/plugins"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
docker_image = "postgres:17-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "redmine-db"
    [[services.storage]]
      host = "postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "redmine"
to = "postgresql"
