name = "Build and scale stateful workloads with long-lived processes"
description = "Build and scale stateful workloads with long-lived processes"
category = "stack"
logo = "svgs/rivet.svg"
[[services]]
name = "rivet-engine"
category = "app"
subtype = "docker"
docker_image = "rivetdev/engine:2.2.0"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_RIVET_6420 = ""
    RIVET__FILE_SYSTEM__PATH = "/data"
    RIVET__AUTH__ADMIN_TOKEN = "${SERVICE_BASE64_TOKEN}"
    [[services.storage]]
      host = "rivet-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
