name = "Rybbit"
description = "Open-source, privacy-first web analytics."
category = "stack"
logo = "svgs/rybbit.svg"

[[services]]
name = "rybbit"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/rybbit-io/rybbit-client:v2.2.3"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NODE_ENV = "production"
    NEXT_PUBLIC_BACKEND_URL = "https://example.com"
    NEXT_PUBLIC_DISABLE_SIGNUP = "false"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "rybbit_backend"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/rybbit-io/rybbit-backend:v2.2.3"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NODE_ENV = "production"
    TRUST_PROXY = "true"
    BASE_URL = "https://example.com"
    CLICKHOUSE_PASSWORD = "CHANGE_ME"
    POSTGRES_PASSWORD = "CHANGE_ME"
    BETTER_AUTH_SECRET = "BASE64_GENERATED"
    DISABLE_SIGNUP = "false"
    DISABLE_TELEMETRY = "true"
    CLICKHOUSE_HOST = "http://rybbit_clickhouse:8123"
    CLICKHOUSE_USER = "default"
    CLICKHOUSE_DB = "analytics"
    POSTGRES_HOST = "rybbit_postgres"
    POSTGRES_PORT = "5432"
    POSTGRES_DB = "analytics"
    POSTGRES_USER = "frog"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "rybbit_postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:17.4"
source = { type = "docker"  }
  [services.env]
    POSTGRES_DB = "analytics"
    POSTGRES_USER = "frog"
    POSTGRES_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "rybbit_clickhouse"
category = "app"
subtype = "docker"
docker_image = "clickhouse/clickhouse-server:25.4.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CLICKHOUSE_DB = "analytics"
    CLICKHOUSE_USER = "default"
    CLICKHOUSE_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "clickhouse_data"
      container = "/var/lib/clickhouse"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[links]]
from = "rybbit"
to = "rybbit_backend"

[[links]]
from = "rybbit_backend"
to = "rybbit_clickhouse"

[[links]]
from = "rybbit_backend"
to = "rybbit_postgres"

[[links]]
from = "rybbit"
to = "rybbit_postgres"

[[links]]
from = "rybbit_clickhouse"
to = "rybbit_postgres"
