name = "Ryot"
description = "Roll your own tracker! Ryot is a self-hosted platform for tracking various aspects of life such as media consumption, fitness activities, and more."
category = "stack"
logo = "svgs/ryot.svg"

[[services]]
name = "ryot"
category = "app"
subtype = "docker"
docker_image = "ignisda/ryot:v8"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVER_ADMIN_ACCESS_TOKEN = "${{ secret() }}"
    TZ = "Europe/Amsterdam"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "ryot-db"
    TZ = "Europe/Amsterdam"
    [[services.storage]]
      host = "ryot_postgresql_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "ryot"
to = "postgresql"