name = "Satisfactory"
description = "Satisfactory Dedicated Server for hosting your own Satisfactory game sessions."
category = "stack"
logo = "svgs/satisfactory.jpg"

[[services]]
name = "satisfactory-server"
category = "app"
subtype = "docker"
docker_image = "wolveix/satisfactory-server:v1.9.10"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    AUTOSAVENUM = "5"
    DEBUG = "false"
    DISABLESEASONALEVENTS = "false"
    LOG = "false"
    MAXOBJECTS = "${MAX_OBJECTS:?2162688}"
    MAXPLAYERS = "${MAX_PLAYERS:?4}"
    MAXTICKRATE = "30"
    MULTIHOME = "::"
    PGID = "${PGID:?1000}"
    PUID = "${PUID:?1000}"
    SERVERGAMEPORT = "7777"
    SERVERMESSAGINGPORT = "8888"
    SERVERSTREAMING = "true"
    SKIPUPDATE = "false"
    STEAMBETA = "false"
    TIMEOUT = "30"
  [services.proxy]
    enabled = true
    type = "traefik"
    [[services.proxy.ports]]
      host = 0
      container = 7777
    [[services.proxy.ports]]
      host = 0
      container = 7777
    [[services.proxy.ports]]
      host = 0
      container = 8888
    [[services.storage]]
      host = "satisfactory-server"
      container = "/config"
