name = "Satisfactory Dedicated Server for hosting your own Satisfactory game sessions."
description = "Satisfactory Dedicated Server for hosting your own Satisfactory game sessions."
category = "stack"
logo = "svgs/satisfactory.jpg"
[[services]]
name = "satisfactory-server"
category = "app"
subtype = "docker"
docker_image = "wolveix/satisfactory-server:v1.9.10"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    AUTOSAVENUM = "${AUTOSAVE_NUM:-5}"
    DEBUG = "${DEBUG:-false}"
    DISABLESEASONALEVENTS = "${DISABLE_SEASONAL_EVENTS:-false}"
    LOG = "${LOG:-false}"
    MAXOBJECTS = "${MAX_OBJECTS:?2162688}"
    MAXPLAYERS = "${MAX_PLAYERS:?4}"
    MAXTICKRATE = "${MAX_TICK_RATE:-30}"
    MULTIHOME = "${MULTI_HOME:-::}"
    PGID = "${PGID:?1000}"
    PUID = "${PUID:?1000}"
    SERVERGAMEPORT = "${SERVER_GAME_PORT:-7777}"
    SERVERMESSAGINGPORT = "${SERVER_MESSAGING_PORT:-8888}"
    SERVERSTREAMING = "${SERVER_STREAMING:-true}"
    SKIPUPDATE = "${SKIP_UPDATE:-false}"
    STEAMBETA = "${STEAM_BETA:-false}"
    TIMEOUT = "${TIMEOUT:-30}"
  [services.proxy]
    enabled = true
    type = "traefik"
    [[services.proxy.ports]]
      host = 0
      container = 7777
    [[services.proxy.ports]]
      host = 0
      container = 7777
    [[services.proxy.ports]]
      host = 0
      container = 8888
    [[services.storage]]
      host = "satisfactory-server"
      container = "/config"
