name = "Open source cloud storage system for file sync, share and document collaboration"
description = "Open source cloud storage system for file sync, share and document collaboration"
category = "stack"
logo = "svgs/seafile.svg"
[[services]]
name = "seafile"
category = "app"
subtype = "docker"
docker_image = "seafileltd/seafile-mc:12.0-latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_SEAFILE_80 = ""
    SEAFILE_SERVER_HOSTNAME = "${SERVICE_FQDN_SEAFILE}"
    DB_HOST = "mariadb"
    DB_PORT = "3306"
    DB_ROOT_PASSWD = "${SERVICE_PASSWORD_MYSQLROOT}"
    DB_USER = "${SERVICE_USER_MYSQL}"
    DB_PASSWORD = "${SERVICE_PASSWORD_MYSQL}"
    SEAFILE_MYSQL_DB_CCNET_DB_NAME = "${SEAFILE_MYSQL_DB_CCNET_DB_NAME:-ccnet_db}"
    SEAFILE_MYSQL_DB_SEAFILE_DB_NAME = "${SEAFILE_MYSQL_DB_SEAFILE_DB_NAME:-seafile_db}"
    SEAFILE_MYSQL_DB_SEAHUB_DB_NAME = "${SEAFILE_MYSQL_DB_SEAHUB_DB_NAME:-seahub_db}"
    TIME_ZONE = "${TIME_ZONE:-UTC}"
    INIT_SEAFILE_ADMIN_EMAIL = "${INIT_SEAFILE_ADMIN_EMAIL:-test@example.com}"
    INIT_SEAFILE_ADMIN_PASSWORD = "${SERVICE_PASSWORD_ADMIN}"
    SEAFILE_SERVER_PROTOCOL = "https"
    SITE_ROOT = "${SITE_ROOT:-/}"
    NON_ROOT = "${NON_ROOT:-false}"
    JWT_PRIVATE_KEY = "${SERVICE_PASSWORD_64_JWT}"
    SEAFILE_LOG_TO_STDOUT = "${SEAFILE_LOG_TO_STDOUT:-true}"
    FILE_SERVER_ROOT = "${SERVICE_URL_SEAFILE}/seafhttp"
    [[services.storage]]
      host = "seafile-data"
      container = "/shared"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 20

[[services]]
name = "mariadb"
category = "database"
subtype = "mariadb"
docker_image = "mariadb:11"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "${SERVICE_PASSWORD_MYSQLROOT}"
    MYSQL_USER = "${SERVICE_USER_MYSQL}"
    MYSQL_PASSWORD = "${SERVICE_PASSWORD_MYSQL}"
    MYSQL_DATABASE = "${MYSQL_DATABASE:-seafile-db}"
    [[services.storage]]
      host = "seafile_mariadb_data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 20

[[services]]
name = "memcached"
category = "cache"
subtype = "memcached"
docker_image = "memcached:latest"
source = { type = "docker"  }
  [services.checks]
    enabled = true
    wait = 10
    timeout = 20

[[links]]
from = "seafile"
to = "mariadb"

[[links]]
from = "seafile"
to = "memcached"
