name = "Searxng"
description = "SearXNG is a free internet metasearch engine which aggregates results from more than 70 search services."
category = "stack"
logo = "svgs/searxng.svg"

[[services]]
name = "searxng"
category = "app"
subtype = "docker"
docker_image = "searxng/searxng"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    INSTANCE_NAME = "coolify"
    BASE_URL = "https://example.com"
    SEARXNG_URL = "https://example.com"
    SEARXNG_BIND_ADDRESS = "0.0.0.0"
    SEARXNG_SECRET = "${{ secret() }}"
    SEARXNG_REDIS_URL = "redis://redis:6379/0"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[links]]
from = "searxng"
to = "redis"
