name = "SeaweedFS is a simple and highly scalable distributed file system. Compatible with S3, with an admin web interface."
description = "SeaweedFS is a simple and highly scalable distributed file system. Compatible with S3, with an admin web interface."
category = "stack"
logo = "svgs/seaweedfs.svg"
[[services]]
name = "seaweedfs-master"
category = "app"
subtype = "docker"
docker_image = "chrislusf/seaweedfs:4.13"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_S3_8333 = ""
    AWS_ACCESS_KEY_ID = "${SERVICE_USER_S3}"
    AWS_SECRET_ACCESS_KEY = "${SERVICE_PASSWORD_S3}"
    [[services.storage]]
      host = "seaweedfs-s3-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "seaweedfs-admin"
category = "app"
subtype = "docker"
docker_image = "chrislusf/seaweedfs:4.13"
start_command = "admin -master=seaweedfs-master:9333 -adminUser=${SEAWEED_USER_ADMIN} -adminPassword=${SEAWEED_PASSWORD_ADMIN} -port=23646 -dataDir=/data"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_ADMIN_23646 = ""
    SEAWEED_USER_ADMIN = "${SERVICE_USER_ADMIN}"
    SEAWEED_PASSWORD_ADMIN = "${SERVICE_PASSWORD_ADMIN}"
    [[services.storage]]
      host = "seaweedfs-admin-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "seaweedfs-admin"
to = "seaweedfs-master"
