name = "Seaweedfs"
description = "SeaweedFS is a simple and highly scalable distributed file system. Compatible with S3, with an admin web interface."
category = "stack"
logo = "svgs/seaweedfs.svg"

[[services]]
name = "seaweedfs-master"
category = "app"
subtype = "docker"
docker_image = "chrislusf/seaweedfs:4.13"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    AWS_ACCESS_KEY_ID = "user"
    AWS_SECRET_ACCESS_KEY = "${{ secret() }}"
    [[services.storage]]
      host = "seaweedfs-s3-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "seaweedfs-admin"
category = "app"
subtype = "docker"
docker_image = "chrislusf/seaweedfs:4.13"
start_command = "admin -master=seaweedfs-master:9333 -adminUser=${SEAWEED_USER_ADMIN} -adminPassword=${SEAWEED_PASSWORD_ADMIN} -port=23646 -dataDir=/data"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SEAWEED_USER_ADMIN = "user"
    SEAWEED_PASSWORD_ADMIN = "${{ secret() }}"
    [[services.storage]]
      host = "seaweedfs-admin-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "seaweedfs-admin"
to = "seaweedfs-master"
