name = "The fastest Postgres change data capture"
description = "The fastest Postgres change data capture"
category = "stack"
logo = "svgs/sequin.svg"
[[services]]
name = "sequin"
category = "app"
subtype = "docker"
docker_image = "sequin/sequin:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_SEQUIN_7376 = ""
    SERVER_HOST = "${SERVICE_FQDN_SEQUIN}"
    PG_HOSTNAME = "postgres"
    PG_DATABASE = "${POSTGRES_DB:-sequin-db}"
    PG_PORT = "5432"
    PG_USERNAME = "${SERVICE_USER_POSTGRES}"
    PG_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    PG_POOL_SIZE = "20"
    SECRET_KEY_BASE = "${SERVICE_REALBASE64_64_SECRETKEY}"
    VAULT_KEY = "${SERVICE_REALBASE64_VAULTKEY}"
    REDIS_URL = "redis://redis:6379"
    CONFIG_FILE_PATH = "/config/playground.yml"
    FEATURE_ACCOUNT_SELF_SIGNUP = "${FEATURE_ACCOUNT_SELF_SIGNUP:-false}"
    SEQUIN_TELEMETRY_DISABLED = "${SEQUIN_TELEMETRY_DISABLED:-false}"
    CRASH_REPORTING_DISABLED = "${CRASH_REPORTING_DISABLED:-false}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16"
start_command = "postgres -c wal_level=logical"
source = { type = "docker"  }
  [services.env]
    POSTGRES_DB = "${POSTGRES_DB:-sequin-db}"
    POSTGRES_USER = "${SERVICE_USER_POSTGRES}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    [[services.storage]]
      host = "postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 2

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7"
start_command = "redis-server --port 6379"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "sequin"
to = "redis"

[[links]]
from = "sequin"
to = "postgres"
