name = "Sequin"
description = "The fastest Postgres change data capture"
category = "stack"
logo = "svgs/sequin.svg"

[[services]]
name = "sequin"
category = "app"
subtype = "docker"
docker_image = "sequin/sequin:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVER_HOST = "app.example.com"
    PG_HOSTNAME = "postgres"
    PG_DATABASE = "sequin-db"
    PG_PORT = "5432"
    PG_USERNAME = "user"
    PG_PASSWORD = "${{ secret() }}"
    PG_POOL_SIZE = "20"
    SECRET_KEY_BASE = "${{ secret() }}"
    VAULT_KEY = "${{ secret() }}"
    REDIS_URL = "redis://redis:6379"
    CONFIG_FILE_PATH = "/config/playground.yml"
    FEATURE_ACCOUNT_SELF_SIGNUP = "false"
    SEQUIN_TELEMETRY_DISABLED = "false"
    CRASH_REPORTING_DISABLED = "false"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
start_command = "postgres -c wal_level=logical"
source = { type = "docker"  }
  [services.env]
    POSTGRES_DB = "sequin-db"
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "postgres_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 2

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7"
start_command = "redis-server --port 6379"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "sequin"
to = "redis"

[[links]]
from = "sequin"
to = "postgres"