name = "Sessy"
description = "Email observability platform for monitoring and analyzing email systems."
category = "stack"
logo = "svgs/sessy.svg"

[[services]]
name = "sessy"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/marckohlbrugge/sessy:main"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY_BASE = "${{ secret() }}"
    HTTP_AUTH_USERNAME = "${{ secret() }}"
    HTTP_AUTH_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "sessy-data"
      container = "/rails/storage"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10
