name = "Sftpgo"
description = "SFTPGo is an event-driven SFTP, FTP/S, HTTP/S and WebDAV server."
category = "stack"
logo = "svgs/sftpgo.png"

[[services]]
name = "sftpgo"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/drakkan/sftpgo:v2.7-alpine"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SFTPGO_DATA_PROVIDER__DRIVER = "postgresql"
    SFTPGO_DATA_PROVIDER__CONNECTION_STRING = "postgresql://user:CHANGE_ME@postgresql:5432/sftpgo-db"
    SFTPGO_SFTPD__BINDINGS__0__PORT = "2222"
    SFTPGO_LOG_LEVEL = "info"
  [services.proxy]
    enabled = true
    type = "traefik"
    [[services.proxy.ports]]
      host = 2222
      container = 2222
    [[services.storage]]
      host = "sftpgo-data"
      container = "/srv/sftpgo/data"
    [[services.storage]]
      host = "sftpgo-keys"
      container = "/var/lib/sftpgo"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
docker_image = "postgres:17-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "sftpgo-db"
    [[services.storage]]
      host = "postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "sftpgo"
to = "postgresql"
