name = "Shlink"
description = "The definitive self-hosted URL shortener"
category = "stack"

[[services]]
name = "shlink"
category = "app"
subtype = "docker"
docker_image = "shlinkio/shlink:stable"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DEFAULT_DOMAIN = "app.example.com"
    IS_HTTPS_ENABLED = "false"
    INITIAL_API_KEY = "BASE64_GENERATED"
    [[services.storage]]
      host = "shlink-data"
      container = "/etc/shlink/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "shlink-web"
category = "app"
subtype = "docker"
docker_image = "shlinkio/shlink-web-client"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SHLINK_SERVER_API_KEY = "BASE64_GENERATED"
    SHLINK_SERVER_URL = "https://example.com"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
