name = "Soketi is your simple, fast, and resilient open-source WebSockets server."
description = "Soketi is your simple, fast, and resilient open-source WebSockets server."
category = "stack"
logo = "svgs/soketi.jpeg"
[[services]]
name = "soketi"
category = "app"
subtype = "docker"
docker_image = "quay.io/soketi/soketi:1.6-16-debian"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_SOKETI_6001 = ""
    SOKETI_DEBUG = "${DEBUG:-0}"
    SOKETI_DEFAULT_APP_ID = "${SERVICE_USER_SOKETI}"
    SOKETI_DEFAULT_APP_KEY = "${SERVICE_REALBASE64_64_SOKETIKEY}"
    SOKETI_DEFAULT_APP_SECRET = "${SERVICE_REALBASE64_64_SOKETISECRET}"
    SOKETI_PUSHER_SCHEME = "${SOKETI_PUSHER_SCHEME:-https}"
    SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES = "${DEFAULT_APP_ENABLE_CLIENT_MESSAGES}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
