name = "Soketi"
description = "Soketi is your simple, fast, and resilient open-source WebSockets server."
category = "stack"
logo = "svgs/soketi.jpeg"

[[services]]
name = "soketi"
category = "app"
subtype = "docker"
docker_image = "quay.io/soketi/soketi:1.6-16-debian"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SOKETI_DEBUG = "0"
    SOKETI_DEFAULT_APP_ID = "user"
    SOKETI_DEFAULT_APP_KEY = "${{ secret() }}"
    SOKETI_DEFAULT_APP_SECRET = "${{ secret() }}"
    SOKETI_PUSHER_SCHEME = "https"
    SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES = "DEFAULT_APP_ENABLE_CLIENT_MESSAGES_VALUE"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
