name = "Sonarqube"
description = "SonarQube is a self-managed, automatic code review tool that systematically helps you deliver Clean Code"
category = "stack"

[[services]]
name = "sonarqube"
category = "app"
subtype = "docker"
docker_image = "sonarqube:community"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SONAR_JDBC_URL = "jdbc:postgresql://postgresql:5432/sonar"
    SONAR_JDBC_USERNAME = "${{ linked.postgresql.POSTGRES_USER }}"
    SONAR_JDBC_PASSWORD = "${{ linked.postgresql.POSTGRES_PASSWORD }}"
    SONAR_ES_BOOTSTRAP_CHECKS_DISABLE = "true"
    [[services.storage]]
      host = "sonarqube-data"
      container = "/opt/sonarqube"
    [[services.storage]]
      host = "sonarqube-conf"
      container = "/opt/sonarqube/conf"
    [[services.storage]]
      host = "sonarqube-extensions"
      container = "/opt/sonarqube/extensions"
    [[services.storage]]
      host = "sonarqube-logs"
      container = "/opt/sonarqube/logs"
    [[services.storage]]
      host = "sonarqube-bundled-plugins"
      container = "/opt/sonarqube/lib/bundled-plugins"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "sonar"
    [[services.storage]]
      host = "postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "sonarqube"
to = "postgresql"