name = "Sparkyfitness"
description = "SparkyFitness is a comprehensive fitness tracking and management application designed to help users monitor their nutrition, exercise, and body measurements. It provides tools for daily progress tracking, goal setting, and insightful reports to support a healthy lifestyle."
category = "stack"
logo = "svgs/sparkyfitness.svg"

[[services]]
name = "sparkyfitness-frontend"
category = "app"
subtype = "docker"
docker_image = "codewithcj/sparkyfitness:v0.15.7.3"
source = { type = "docker"  }
  [services.scaling]
    web = 1

[[services]]
name = "sparkyfitness-server"
category = "app"
subtype = "docker"
docker_image = "codewithcj/sparkyfitness_server:v0.15.7.3"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SPARKY_FITNESS_LOG_LEVEL = "info"
    SPARKY_FITNESS_DB_USER = "user"
    SPARKY_FITNESS_DB_HOST = "sparkyfitness-db"
    SPARKY_FITNESS_DB_NAME = "sparkyfitness"
    SPARKY_FITNESS_DB_PASSWORD = "CHANGE_ME"
    SPARKY_FITNESS_DB_PORT = "5432"
    SPARKY_FITNESS_API_ENCRYPTION_KEY = "CHANGE_ME"
    JWT_SECRET = "CHANGE_ME"
    SPARKY_FITNESS_FRONTEND_URL = "https://example.com"
    SPARKY_FITNESS_DISABLE_SIGNUP = "false"
    SPARKY_FITNESS_ADMIN_EMAIL = "admin@example.com"
    SPARKY_FITNESS_EMAIL_HOST = "smtp.gmail.com"
    SPARKY_FITNESS_EMAIL_PORT = "587"
    SPARKY_FITNESS_EMAIL_SECURE = "false"
    SPARKY_FITNESS_EMAIL_USER = "admin@example.com"
    SPARKY_FITNESS_EMAIL_PASS = "admin@example.com"
    SPARKY_FITNESS_EMAIL_FROM = "\"Sparky Fitness <noreply@sparkyfitness.com>\""
    [[services.storage]]
      host = "sparkyfitness-server-backup"
      container = "/app/SparkyFitnessServer/backup"
    [[services.storage]]
      host = "sparkyfitness-server-uploads"
      container = "/app/SparkyFitnessServer/uploads"

[[services]]
name = "sparkyfitness-db"
category = "database"
subtype = "postgres"
docker_image = "postgres:15-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_DB = "sparkyfitness"
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_PORT = "5432"
    [[services.storage]]
      host = "sparkyfitness-db-postgresql"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "sparkyfitness-frontend"
to = "sparkyfitness-server"

[[links]]
from = "sparkyfitness-server"
to = "sparkyfitness-db"

[[links]]
from = "sparkyfitness-frontend"
to = "sparkyfitness-db"
