name = "Strapi"
description = "Open-source headless CMS to build powerful APIs with built-in content management."
category = "stack"
logo = "svgs/strapi.svg"

[[services]]
name = "strapi"
category = "app"
subtype = "docker"
docker_image = "elestio/strapi-production:v5.33.4"
start_command = "-c cat > /opt/app/src/admin/vite.config.js << 'EOFVITE'\nconst { mergeConfig } = require('vite');\nmodule.exports = (config) => {\n  return mergeConfig(config, {\n    resolve: {\n      alias: {\n        '@': '/src',\n      },\n    },\n    server: {\n      allowedHosts: ['\${{ RAILDOCK_PUBLIC_DOMAIN }}']\n    }\n  });\n};\nEOFVITE\nexec npm run develop\n"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_CLIENT = "postgres"
    DATABASE_HOST = "postgresql"
    DATABASE_PORT = "5432"
    DATABASE_NAME = "strapi"
    DATABASE_USERNAME = "${{ linked.postgresql.POSTGRES_USER }}"
    DATABASE_PASSWORD = "${{ linked.postgresql.POSTGRES_PASSWORD }}"
    JWT_SECRET = "${{ secret() }}"
    ADMIN_JWT_SECRET = "${{ secret() }}"
    APP_KEYS = "${{ secret() }}"
    STRAPI_TELEMETRY_DISABLED = "true"
    STRAPI_LICENSE = "STRAPI_LICENSE_VALUE"
    NODE_ENV = "development"
    BROWSER = "true"
    STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE = "en"
    STRAPI_ENFORCE_SOURCEMAPS = "false"
    FAST_REFRESH = "true"
    [[services.storage]]
      host = "strapi-config"
      container = "/opt/app/config"
    [[services.storage]]
      host = "strapi-src"
      container = "/opt/app/src"
    [[services.storage]]
      host = "strapi-uploads"
      container = "/opt/app/public/uploads"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_DB = "strapi"
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    PGDATA = "/var/lib/postgresql/data"
    [[services.storage]]
      host = "strapi-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "strapi"
to = "postgresql"