name = "Supertokens With Mysql"
description = "An open-source authentication solution that simplifies the implementation of secure user authentication and session management for web and mobile applications."
category = "stack"
logo = "svgs/supertokens.svg"

[[services]]
name = "supertokens"
category = "database"
subtype = "mysql"
  [services.env]
    MYSQL_CONNECTION_URI = "mysql://${{ linked.mysql.MYSQL_USER }}:${{ linked.mysql.MYSQL_PASSWORD }}@mysql:3306/supertokens"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "mysql"
category = "database"
subtype = "mysql"
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_USER = "${{ secret() }}"
    MYSQL_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "supertokens"
    [[services.storage]]
      host = "supertokens-mysql-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "supertokens"
to = "mysql"