name = "Superset With Postgresql"
description = "Modern data exploration and visualization platform (unofficial community docker image)"
category = "stack"
logo = "svgs/superset.svg"

[[services]]
name = "superset"
category = "app"
subtype = "docker"
docker_image = "amancevice/superset:6.0.0"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SECRET_KEY = "BASE64_GENERATED"
    MAPBOX_API_KEY = "${{ secret() }}"
    REDIS_PASSWORD = "${{ secret() }}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "superset-db"
    [[services.storage]]
      host = "superset_postgres_data"
      container = "/var/lib/postgresql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:8"
start_command = "redis-server"
source = { type = "docker"  }
    [[services.storage]]
      host = "superset_redis_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "superset"
to = "postgres"

[[links]]
from = "superset"
to = "redis"