name = "Tailscale securely connects your devices over the internet using WireGuard."
description = "Tailscale securely connects your devices over the internet using WireGuard."
category = "stack"
logo = "svgs/tailscale.svg"
[[services]]
name = "tailscale-client"
category = "app"
subtype = "docker"
docker_image = "tailscale/tailscale:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    TS_HOSTNAME = "${TS_HOSTNAME:-coolify-ts}"
    TS_AUTHKEY = "${TS_AUTHKEY:?}"
    TS_STATE_DIR = "${TS_STATE_DIR:-/var/lib/tailscale}"
    TS_USERSPACE = "${TS_USERSPACE:-false}"
    [[services.storage]]
      host = "tailscale-client"
      container = "/var/lib/tailscale"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "nginx"
category = "app"
subtype = "docker"
docker_image = "nginx:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.checks]
    enabled = true
    wait = 20
    timeout = 5

[[links]]
from = "nginx"
to = "tailscale-client"
