name = "Teable is a powerful visual interface built on relational databases (PostgreSQL)."
description = "Teable is a powerful visual interface built on relational databases (PostgreSQL)."
category = "stack"
logo = "svgs/teable.png"
[[services]]
name = "teable"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/teableio/teable:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_TEABLE_3000 = ""
    PUBLIC_ORIGIN = "${SERVICE_URL_TEABLE}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    SECRET_KEY = "${SERVICE_PASSWORD_64_SECRET}"
    TZ = "${TIMEZONE}"
    PRISMA_DATABASE_URL = "postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@teable-db:${POSTGRES_PORT}/${POSTGRES_DB}"
    NEXT_ENV_IMAGES_ALL_REMOTE = "true"
    PORT = "3000"
    REDIS_PASSWORD = "${SERVICE_PASSWORD_REDIS}"
    BACKEND_CACHE_PROVIDER = "redis"
    BACKEND_CACHE_REDIS_URI = "redis://default:${SERVICE_PASSWORD_REDIS}@teable-cache:6379/0"
    BACKEND_MAIL_HOST = "${BACKEND_MAIL_HOST}"
    BACKEND_MAIL_PORT = "${BACKEND_MAIL_PORT}"
    BACKEND_MAIL_SECURE = "${BACKEND_MAIL_SECURE}"
    BACKEND_MAIL_SENDER = "${BACKEND_MAIL_SENDER}"
    BACKEND_MAIL_SENDER_NAME = "${BACKEND_MAIL_SENDER_NAME}"
    BACKEND_MAIL_AUTH_USER = "${BACKEND_MAIL_AUTH_USER}"
    BACKEND_MAIL_AUTH_PASS = "${BACKEND_MAIL_AUTH_PASS}"
    [[services.storage]]
      host = "teable_data"
      container = "/app/.assets"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "teable-db"
category = "database"
subtype = "postgres"
docker_image = "postgres:15.4"
source = { type = "docker"  }
  [services.env]
    TZ = "${TIMEZONE}"
    POSTGRES_DB = "${POSTGRES_DB:-teable}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_POSTGRES}"
    POSTGRES_USER = "${SERVICE_USER_POSTGRES}"
    POSTGRES_PORT = "${POSTGRES_PORT:-5432}"
    [[services.storage]]
      host = "teable_db_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "teable-db-migrate"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/teableio/teable-db-migrate:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    TZ = "${TIMEZONE}"
    PRISMA_DATABASE_URL = "postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@teable-db:${POSTGRES_PORT}/${POSTGRES_DB}"

[[services]]
name = "teable-cache"
category = "cache"
subtype = "redis"
docker_image = "redis:7.2.4"
start_command = "redis-server --appendonly yes --requirepass ${SERVICE_PASSWORD_REDIS}"
source = { type = "docker"  }
  [services.env]
    REDIS_PORT = "6379"
    REDIS_DB = "0"
    REDIS_PASSWORD = "${SERVICE_PASSWORD_REDIS}"
    [[services.storage]]
      host = "teable_cache_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 3

[[links]]
from = "teable"
to = "teable-cache"

[[links]]
from = "teable-db-migrate"
to = "teable-db"
