name = "Teable"
description = "Teable is a powerful visual interface built on relational databases (PostgreSQL)."
category = "stack"
logo = "svgs/teable.png"

[[services]]
name = "teable"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/teableio/teable:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    PUBLIC_ORIGIN = "https://example.com"
    POSTGRES_PASSWORD = "CHANGE_ME"
    SECRET_KEY = "CHANGE_ME"
    TZ = "TIMEZONE_VALUE"
    PRISMA_DATABASE_URL = "postgresql://user:CHANGE_ME@teable-db:3000/POSTGRES_DB_VALUE"
    NEXT_ENV_IMAGES_ALL_REMOTE = "true"
    PORT = "3000"
    REDIS_PASSWORD = "CHANGE_ME"
    BACKEND_CACHE_PROVIDER = "redis"
    BACKEND_CACHE_REDIS_URI = "redis://default:CHANGE_ME@teable-cache:6379/0"
    BACKEND_MAIL_HOST = "https://example.com"
    BACKEND_MAIL_PORT = "3000"
    BACKEND_MAIL_SECURE = "BACKEND_MAIL_SECURE_VALUE"
    BACKEND_MAIL_SENDER = "BACKEND_MAIL_SENDER_VALUE"
    BACKEND_MAIL_SENDER_NAME = "BACKEND_MAIL_SENDER_NAME_VALUE"
    BACKEND_MAIL_AUTH_USER = "BACKEND_MAIL_AUTH_USER_VALUE"
    BACKEND_MAIL_AUTH_PASS = "BACKEND_MAIL_AUTH_PASS_VALUE"
    [[services.storage]]
      host = "teable_data"
      container = "/app/.assets"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "teable-db"
category = "database"
subtype = "postgres"
docker_image = "postgres:15.4"
source = { type = "docker"  }
  [services.env]
    TZ = "TIMEZONE_VALUE"
    POSTGRES_DB = "teable"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_USER = "user"
    POSTGRES_PORT = "5432"
    [[services.storage]]
      host = "teable_db_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "teable-db-migrate"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/teableio/teable-db-migrate:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    TZ = "TIMEZONE_VALUE"
    PRISMA_DATABASE_URL = "postgresql://user:CHANGE_ME@teable-db:3000/POSTGRES_DB_VALUE"

[[services]]
name = "teable-cache"
category = "cache"
subtype = "redis"
docker_image = "redis:7.2.4"
start_command = "redis-server --appendonly yes --requirepass ${SERVICE_PASSWORD_REDIS}"
source = { type = "docker"  }
  [services.env]
    REDIS_PORT = "6379"
    REDIS_DB = "0"
    REDIS_PASSWORD = "CHANGE_ME"
    [[services.storage]]
      host = "teable_cache_data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 3

[[links]]
from = "teable"
to = "teable-cache"

[[links]]
from = "teable-db-migrate"
to = "teable-db"

[[links]]
from = "teable"
to = "teable-db"

[[links]]
from = "teable-db-migrate"
to = "teable-cache"
