name = "Trigger"
description = "The open source background jobs platform for developers"
category = "stack"
logo = "svgs/trigger.png"

[[services]]
name = "trigger"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/triggerdotdev/trigger.dev:v4.3.0"
start_command = "sh -c \"chown -R node:node /home/node/shared && exec ./scripts/entrypoint.sh\"\n"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    APP_ORIGIN = "https://example.com"
    LOGIN_ORIGIN = "https://example.com"
    API_ORIGIN = "https://example.com"
    SESSION_SECRET = "${{ secret() }}"
    MAGIC_LINK_SECRET = "${{ secret() }}"
    ENCRYPTION_KEY = "${{ secret() }}"
    MANAGED_WORKER_SECRET = "${{ secret() }}"
    TRIGGER_WORKER_TOKEN = "${{ secret() }}"
    NODE_ENV = "production"
    APP_LOG_LEVEL = "info"
    DATABASE_URL = "postgresql://user:CHANGE_ME@postgresql:5432/trigger-db?schema=public&sslmode=disable"
    DIRECT_URL = "postgresql://user:CHANGE_ME@postgresql:5432/trigger-db?schema=public&sslmode=disable"
    REDIS_HOST = "redis"
    REDIS_PORT = "6379"
    REDIS_TLS_DISABLED = "true"
    ELECTRIC_ORIGIN = "http://electric:3000"
    DEPLOY_REGISTRY_HOST = "ghcr.io"
    DEPLOY_REGISTRY_PROTOCOL = "https"
    DEPLOY_REGISTRY_NAMESPACE = "trigger"
    V4_DEPLOY_REGISTRY_NAMESPACE = "trigger"
    OBJECT_STORE_BASE_URL = "https://example.com"
    OBJECT_STORE_ACCESS_KEY_ID = "${{ secret() }}"
    OBJECT_STORE_SECRET_ACCESS_KEY = "${{ secret() }}"
    CLICKHOUSE_URL = "http://user:CHANGE_ME@clickhouse:8123?secure=false"
    CLICKHOUSE_LOG_LEVEL = "info"
    RUN_REPLICATION_ENABLED = "1"
    RUN_REPLICATION_CLICKHOUSE_URL = "http://user:CHANGE_ME@clickhouse:8123"
    RUN_REPLICATION_LOG_LEVEL = "info"
    TRIGGER_BOOTSTRAP_ENABLED = "1"
    TRIGGER_BOOTSTRAP_WORKER_GROUP_NAME = "bootstrap"
    TRIGGER_BOOTSTRAP_WORKER_TOKEN_PATH = "/home/node/shared/worker_token"
    DEFAULT_ORG_EXECUTION_CONCURRENCY_LIMIT = "300"
    DEFAULT_ENV_EXECUTION_CONCURRENCY_LIMIT = "100"
    EMAIL_TRANSPORT = "smtp"
    RESEND_API_KEY = "${{ secret() }}"
    SMTP_HOST = "https://example.com"
    SMTP_PORT = "3000"
    SMTP_USER = "SMTP_USER_VALUE"
    SMTP_PASSWORD = "${{ secret() }}"
    SMTP_SECURE = "SMTP_SECURE_VALUE"
    FROM_EMAIL = "admin@example.com"
    REPLY_TO_EMAIL = "admin@example.com"
    WHITELISTED_EMAILS = "admin@example.com"
    ADMIN_EMAILS = "admin@example.com"
    GRACEFUL_SHUTDOWN_TIMEOUT = "1000"
    INTERNAL_OTEL_TRACE_LOGGING_ENABLED = "0"
    TRIGGER_TELEMETRY_DISABLED = "true"
    [[services.storage]]
      host = "shared-data"
      container = "/home/node/shared"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "supervisor"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/triggerdotdev/supervisor:v4.3.0"
start_command = "sh -c \"chown -R node:node /home/node/shared && exec /usr/bin/dumb-init -- pnpm run --filter supervisor start\"\n"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    TRIGGER_API_URL = "http://trigger:3000"
    OTEL_EXPORTER_OTLP_ENDPOINT = "http://trigger:3000/otel"
    TRIGGER_WORKER_TOKEN = "file:///home/node/shared/worker_token"
    MANAGED_WORKER_SECRET = "${{ secret() }}"
    TRIGGER_WORKLOAD_API_DOMAIN = "TRIGGER_WORKLOAD_API_DOMAIN_VALUE"
    TRIGGER_WORKLOAD_API_PORT_EXTERNAL = "8020"
    DOCKER_HOST = "tcp://docker-proxy:2375"
    DOCKER_RUNNER_NETWORKS = "DOCKER_RUNNER_NETWORKS_VALUE"
    DOCKER_AUTOREMOVE_EXITED_CONTAINERS = "1"
    DOCKER_REGISTRY_URL = "https://ghcr.io"
    DOCKER_REGISTRY_USERNAME = "DEPLOY_REGISTRY_USERNAME_VALUE"
    DOCKER_REGISTRY_PASSWORD = "${{ secret() }}"
    ENFORCE_MACHINE_PRESETS = "1"
    TRIGGER_DEQUEUE_INTERVAL_MS = "1000"
    DEBUG = "0"
    [[services.storage]]
      host = "shared-data"
      container = "/home/node/shared"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "docker-proxy"
category = "app"
subtype = "docker"
docker_image = "tecnativa/docker-socket-proxy:v0.4.2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    LOG_LEVEL = "info"
    POST = "1"
    CONTAINERS = "1"
    IMAGES = "1"
    INFO = "1"
    NETWORKS = "1"
    AUTH = "1"
    DISTRIBUTION = "1"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
start_command = "-c wal_level=logical"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "trigger-db"
    [[services.storage]]
      host = "postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "electric"
category = "app"
subtype = "docker"
docker_image = "electricsql/electric:1.2.9"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "postgresql://user:CHANGE_ME@postgresql:5432/trigger-db?sslmode=disable"
    ELECTRIC_SECRET = "${{ secret() }}"
    ELECTRIC_USAGE_REPORTING = "false"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "clickhouse"
category = "app"
subtype = "docker"
docker_image = "clickhouse/clickhouse-server:25.8"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CLICKHOUSE_USER = "user"
    CLICKHOUSE_PASSWORD = "${{ secret() }}"
    CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT = "1"
    [[services.storage]]
      host = "clickhouse-data"
      container = "/var/lib/clickhouse"
    [[services.storage]]
      host = "clickhouse-logs"
      container = "/var/log/clickhouse-server"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[links]]
from = "trigger"
to = "postgresql"

[[links]]
from = "trigger"
to = "redis"

[[links]]
from = "trigger"
to = "electric"

[[links]]
from = "trigger"
to = "clickhouse"

[[links]]
from = "supervisor"
to = "trigger"

[[links]]
from = "supervisor"
to = "docker-proxy"

[[links]]
from = "electric"
to = "postgresql"

[[links]]
from = "supervisor"
to = "postgresql"

[[links]]
from = "supervisor"
to = "redis"

[[links]]
from = "docker-proxy"
to = "postgresql"

[[links]]
from = "docker-proxy"
to = "redis"

[[links]]
from = "electric"
to = "redis"

[[links]]
from = "clickhouse"
to = "postgresql"

[[links]]
from = "clickhouse"
to = "redis"