name = "Twenty"
description = "Twenty is a CRM designed to fit your unique business needs."
category = "stack"
logo = "svgs/twenty.svg"

[[services]]
name = "twenty"
category = "app"
subtype = "docker"
docker_image = "twentycrm/twenty:v1.15"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVER_URL = "https://example.com"
    FRONT_BASE_URL = "https://example.com"
    APP_SECRET = "BASE64_GENERATED"
    ENABLE_DB_MIGRATIONS = "true"
    CACHE_STORAGE_TYPE = "redis"
    REDIS_URL = "redis://redis:6379"
    API_RATE_LIMITING_TTL = "100"
    API_RATE_LIMITING_LIMIT = "100"
    POSTGRES_ADMIN_PASSWORD = "${{ secret() }}"
    PG_DATABASE_URL = "postgres:${{ secret() }}@postgres:5432/twenty-db"
    IS_SIGN_UP_DISABLED = "false"
    PASSWORD_RESET_TOKEN_EXPIRES_IN = "5m"
    WORKSPACE_INACTIVE_DAYS_BEFORE_NOTIFICATION = "7"
    WORKSPACE_INACTIVE_DAYS_BEFORE_DELETION = "21"
    STORAGE_TYPE = "local"
    STORAGE_S3_REGION = "$STORAGE_S3_REGION"
    STORAGE_S3_NAME = "$STORAGE_S3_NAME"
    STORAGE_S3_ENDPOINT = "$STORAGE_S3_ENDPOINT"
    STORAGE_S3_ACCESS_KEY_ID = "$STORAGE_S3_ACCESS_KEY_ID"
    STORAGE_S3_SECRET_ACCESS_KEY = "$STORAGE_S3_SECRET_ACCESS_KEY"
    MESSAGE_QUEUE_TYPE = "pg-boss"
    EMAIL_FROM_ADDRESS = "$EMAIL_FROM_ADDRESS"
    EMAIL_FROM_NAME = "$EMAIL_FROM_NAME"
    EMAIL_SYSTEM_ADDRESS = "$EMAIL_SYSTEM_ADDRESS"
    EMAIL_DRIVER = "logger"
    EMAIL_SMTP_HOST = "$EMAIL_SMTP_HOST"
    EMAIL_SMTP_PORT = "$EMAIL_SMTP_PORT"
    EMAIL_SMTP_USER = "$EMAIL_SMTP_USER"
    EMAIL_SMTP_PASSWORD = "$EMAIL_SMTP_PASSWORD"
    SIGN_IN_PREFILLED = "false"
    DEBUG_MODE = "false"
    TELEMETRY_ENABLED = "false"
    [[services.storage]]
      host = "twenty-local-storage"
      container = "/app/packages/twenty-server/.local-storage"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 5

[[services]]
name = "worker"
category = "app"
subtype = "docker"
docker_image = "twentycrm/twenty:v1.15"
start_command = "yarn worker:prod"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVER_URL = "https://example.com"
    FRONT_BASE_URL = "https://example.com"
    APP_SECRET = "BASE64_GENERATED"
    ENABLE_DB_MIGRATIONS = "true"
    CACHE_STORAGE_TYPE = "redis"
    REDIS_URL = "redis://redis:6379"
    API_RATE_LIMITING_TTL = "100"
    API_RATE_LIMITING_LIMIT = "100"
    POSTGRES_ADMIN_PASSWORD = "${{ secret() }}"
    PG_DATABASE_URL = "postgres:${{ secret() }}@postgres:5432/twenty-db"
    IS_SIGN_UP_DISABLED = "false"
    PASSWORD_RESET_TOKEN_EXPIRES_IN = "5m"
    WORKSPACE_INACTIVE_DAYS_BEFORE_NOTIFICATION = "7"
    WORKSPACE_INACTIVE_DAYS_BEFORE_DELETION = "21"
    STORAGE_TYPE = "local"
    STORAGE_S3_REGION = "$STORAGE_S3_REGION"
    STORAGE_S3_NAME = "$STORAGE_S3_NAME"
    STORAGE_S3_ENDPOINT = "$STORAGE_S3_ENDPOINT"
    STORAGE_S3_ACCESS_KEY_ID = "$STORAGE_S3_ACCESS_KEY_ID"
    STORAGE_S3_SECRET_ACCESS_KEY = "$STORAGE_S3_SECRET_ACCESS_KEY"
    MESSAGE_QUEUE_TYPE = "pg-boss"
    EMAIL_FROM_ADDRESS = "$EMAIL_FROM_ADDRESS"
    EMAIL_FROM_NAME = "$EMAIL_FROM_NAME"
    EMAIL_SYSTEM_ADDRESS = "$EMAIL_SYSTEM_ADDRESS"
    EMAIL_DRIVER = "logger"
    EMAIL_SMTP_HOST = "$EMAIL_SMTP_HOST"
    EMAIL_SMTP_PORT = "$EMAIL_SMTP_PORT"
    EMAIL_SMTP_USER = "$EMAIL_SMTP_USER"
    EMAIL_SMTP_PASSWORD = "$EMAIL_SMTP_PASSWORD"
    SIGN_IN_PREFILLED = "false"
    DEBUG_MODE = "false"
    TELEMETRY_ENABLED = "false"
    DISABLE_DB_MIGRATIONS = "true"
    DISABLE_CRON_JOBS_REGISTRATION = "true"
    [[services.storage]]
      host = "twenty-local-storage"
      container = "/app/packages/twenty-server/.local-storage"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 5

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "twenty-db"
    [[services.storage]]
      host = "postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7-alpine"
source = { type = "docker"  }
    [[services.storage]]
      host = "redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "twenty"
to = "postgres"

[[links]]
from = "worker"
to = "twenty"

[[links]]
from = "twenty"
to = "redis"

[[links]]
from = "worker"
to = "postgres"

[[links]]
from = "worker"
to = "redis"