name = "Umami"
description = "Umami is web analytics platform which provides insights into visitor behavior without compromising user privacy."
category = "stack"
logo = "svgs/umami.svg"

[[services]]
name = "umami"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/umami-software/umami:3.0.3"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgresql:5432/$POSTGRES_DB"
    DATABASE_TYPE = "postgres"
    APP_SECRET = "$SERVICE_PASSWORD_64_UMAMI"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgresql"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "$SERVICE_USER_POSTGRES"
    POSTGRES_PASSWORD = "$SERVICE_PASSWORD_POSTGRES"
    POSTGRES_DB = "umami"
    [[services.storage]]
      host = "postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "umami"
to = "postgresql"
