name = "Unstructured"
description = "Unstructured provides a platform and tools to ingest and process unstructured documents for Retrieval Augmented Generation (RAG) and model fine-tuning."
category = "stack"
logo = "svgs/unstructured.png"

[[services]]
name = "unstructured"
category = "app"
subtype = "docker"
docker_image = "downloads.unstructured.io/unstructured-io/unstructured-api:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    UNSTRUCTURED_API_KEY = "${{ secret() }}"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30
