name = "Usesend"
description = "Usesend is an open-source alternative to Resend, Sendgrid, Mailgun and Postmark etc."
category = "stack"
logo = "svgs/usesend.svg"

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "usesend"
    [[services.storage]]
      host = "usesend-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "redis"
category = "cache"
subtype = "redis"
docker_image = "redis:7"
start_command = "redis-server --maxmemory-policy noeviction"
source = { type = "docker"  }
    [[services.storage]]
      host = "usesend-redis-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[services]]
name = "usesend"
category = "app"
subtype = "docker"
docker_image = "usesend/usesend:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    NEXTAUTH_URL = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    NEXTAUTH_SECRET = "BASE64_GENERATED"
    AWS_ACCESS_KEY = "${AWS_ACCESS_KEY:?}"
    AWS_SECRET_KEY = "${AWS_SECRET_KEY:?}"
    AWS_DEFAULT_REGION = "${AWS_DEFAULT_REGION:?}"
    GITHUB_ID = "${GITHUB_ID:?}"
    GITHUB_SECRET = "${GITHUB_SECRET:?}"
    REDIS_URL = "redis://redis:6379"
    NEXT_PUBLIC_IS_CLOUD = "false"
    API_RATE_LIMIT = "1"
    HOSTNAME = "0.0.0.0"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 2

[[links]]
from = "usesend"
to = "postgres"

[[links]]
from = "usesend"
to = "redis"