name = "Vaultwarden"
description = "Vaultwarden is a password manager that allows you to securely store and manage your passwords."
category = "stack"
logo = "svgs/bitwarden.svg"

[[services]]
name = "vaultwarden"
category = "app"
subtype = "docker"
docker_image = "vaultwarden/server:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DOMAIN = "https://${{ RAILDOCK_PUBLIC_DOMAIN }}"
    DATABASE_URL = "data/db.sqlite3"
    SIGNUPS_ALLOWED = "true"
    ADMIN_TOKEN = "${{ secret() }}"
    IP_HEADER = "X-Forwarded-For"
    PUSH_ENABLED = "false"
    PUSH_INSTALLATION_ID = "PUSH_SERVICE_ID_VALUE"
    PUSH_INSTALLATION_KEY = "${{ secret() }}"
    [[services.storage]]
      host = "vaultwarden-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
