name = "Vaultwarden is a password manager that allows you to securely store and manage your passwords."
description = "Vaultwarden is a password manager that allows you to securely store and manage your passwords."
category = "stack"
logo = "svgs/bitwarden.svg"
[[services]]
name = "vaultwarden"
category = "app"
subtype = "docker"
docker_image = "vaultwarden/server:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_VAULTWARDEN = ""
    DOMAIN = "${SERVICE_URL_VAULTWARDEN}"
    DATABASE_URL = "${VAULTWARDEN_DB_URL:-data/db.sqlite3}"
    SIGNUPS_ALLOWED = "${SIGNUP_ALLOWED:-true}"
    ADMIN_TOKEN = "${SERVICE_PASSWORD_64_ADMIN}"
    IP_HEADER = "X-Forwarded-For"
    PUSH_ENABLED = "${PUSH_ENABLED:-false}"
    PUSH_INSTALLATION_ID = "${PUSH_SERVICE_ID}"
    PUSH_INSTALLATION_KEY = "${PUSH_SERVICE_KEY}"
    [[services.storage]]
      host = "vaultwarden-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
