name = "The next-generation file converter. Open source, fully local and free forever."
description = "The next-generation file converter. Open source, fully local and free forever."
category = "stack"
logo = "svgs/vert.png"
[[services]]
name = "vert"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/vert-sh/vert:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_VERT_80 = ""
    PUB_VERT_URL = "${SERVICE_URL_VERT_80}"
    PUB_HOSTNAME = "${SERVICE_URL_VERT_80}"
    PUB_PORT = "80"
    PUB_ENV = "production"
