name = "Powerful and easy to use cms to build websites, blogs or ecommerce stores."
description = "Powerful and easy to use cms to build websites, blogs or ecommerce stores."
category = "stack"
logo = "svgs/vvveb.svg"
[[services]]
name = "vvveb"
category = "app"
subtype = "docker"
docker_image = "vvveb/vvvebcms:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_VVVEB_80 = ""
    [[services.storage]]
      host = "vvveb-data"
      container = "/var/www/html"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10
