name = "Vvveb With Mysql"
description = "Powerful and easy to use cms to build websites, blogs or ecommerce stores."
category = "stack"
logo = "svgs/vvveb.svg"

[[services]]
name = "vvveb"
category = "app"
subtype = "docker"
docker_image = "vvveb/vvvebcms:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DB_ENGINE = "mysqli"
    DB_HOST = "mysql"
    DB_USER = "user"
    DB_PASSWORD = "${{ secret() }}"
    DB_NAME = "vvveb"
    [[services.storage]]
      host = "vvveb-data"
      container = "/var/www/html"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "mysql"
category = "database"
subtype = "mysql"
docker_image = "mysql:8.4.2"
source = { type = "docker"  }
  [services.env]
    MYSQL_ROOT_PASSWORD = "${{ secret() }}"
    MYSQL_DATABASE = "vvveb"
    MYSQL_USER = "user"
    MYSQL_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "vvveb-mysql-data"
      container = "/var/lib/mysql"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "vvveb"
to = "mysql"
