name = "Wakapi"
description = "A minimalist, self-hosted WakaTime-compatible backend for coding statistics"
category = "stack"
logo = "svgs/wakapi.svg"

[[services]]
name = "wakapi"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/muety/wakapi:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    TZ = "Europe/Berlin"
    WAKAPI_SERVER_LISTEN_IPV6 = "\"-\""
    WAKAPI_ENV = "production"
    WAKAPI_SECURITY_PASSWORD_SALT = "BASE64_GENERATED"
    WAKAPI_SECURITY_EXPOSE_METRICS = "false"
    WAKAPI_DB_TYPE = "postgres"
    WAKAPI_DB_NAME = "wakapi"
    WAKAPI_DB_USER = "user"
    WAKAPI_DB_PASSWORD = "CHANGE_ME"
    WAKAPI_DB_HOST = "postgres"
    WAKAPI_DB_PORT = "5432"
    WAKAPI_MAIL_ENABLED = "false"
    WAKAPI_MAIL_PROVIDER = "smtp"
    WAKAPI_MAIL_SENDER = "WAKAPI_MAIL_SENDER_VALUE"
    WAKAPI_MAIL_SMTP_HOST = "https://example.com"
    WAKAPI_MAIL_SMTP_PORT = "587"
    WAKAPI_MAIL_SMTP_USER = "WAKAPI_MAIL_SMTP_USERNAME_VALUE"
    WAKAPI_MAIL_SMTP_PASS = "CHANGE_ME"
    WAKAPI_MAIL_SMTP_TLS = "true"
    WAKAPI_ALLOW_SIGNUP = "true"
    WAKAPI_LEADERBOARD_ENABLED = "true"
    WAKAPI_DISABLE_FRONTPAGE = "true"
    WAKAPI_PUBLIC_URL = "https://example.com"
    [[services.storage]]
      host = "wakapi-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "user"
    POSTGRES_PASSWORD = "CHANGE_ME"
    POSTGRES_DB = "wakapi"
    POSTGRES_PORT = "5432"
    [[services.storage]]
      host = "wakapi-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "wakapi"
to = "postgres"
