name = "A minimalist, self-hosted WakaTime-compatible backend for coding statistics"
description = "A minimalist, self-hosted WakaTime-compatible backend for coding statistics"
category = "stack"
logo = "svgs/wakapi.svg"
[[services]]
name = "wakapi"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/muety/wakapi:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_WAKAPI_3000 = ""
    TZ = "${TIMEZONE:-Europe/Berlin}"
    WAKAPI_SERVER_LISTEN_IPV6 = "\"-\""
    WAKAPI_ENV = "${WAKAPI_ENVIRONMENT:-production}"
    WAKAPI_SECURITY_PASSWORD_SALT = "${SERVICE_BASE64_64_PASSWORDSALT}"
    WAKAPI_SECURITY_EXPOSE_METRICS = "${WAKAPI_SECURITY_EXPOSE_METRICS:-false}"
    WAKAPI_DB_TYPE = "postgres"
    WAKAPI_DB_NAME = "${WAKAPI_DB_NAME:-wakapi}"
    WAKAPI_DB_USER = "${SERVICE_USER_DATABASE}"
    WAKAPI_DB_PASSWORD = "${SERVICE_PASSWORD_DATABASE}"
    WAKAPI_DB_HOST = "${WAKAPI_DB_HOST:-postgres}"
    WAKAPI_DB_PORT = "${WAKAPI_DB_PORT:-5432}"
    WAKAPI_MAIL_ENABLED = "${WAKAPI_MAIL_ENABLED:-false}"
    WAKAPI_MAIL_PROVIDER = "smtp"
    WAKAPI_MAIL_SENDER = "${WAKAPI_MAIL_SENDER}"
    WAKAPI_MAIL_SMTP_HOST = "${WAKAPI_MAIL_SMTP_HOST}"
    WAKAPI_MAIL_SMTP_PORT = "${WAKAPI_MAIL_SMTP_PORT:-587}"
    WAKAPI_MAIL_SMTP_USER = "${WAKAPI_MAIL_SMTP_USERNAME}"
    WAKAPI_MAIL_SMTP_PASS = "${WAKAPI_MAIL_SMTP_PASSWORD}"
    WAKAPI_MAIL_SMTP_TLS = "${WAKAPI_MAIL_SMTP_TLS:-true}"
    WAKAPI_ALLOW_SIGNUP = "${WAKAPI_ALLOW_SIGNUP:-true}"
    WAKAPI_LEADERBOARD_ENABLED = "${WAKAPI_LEADERBOARD_ENABLED:-true}"
    WAKAPI_DISABLE_FRONTPAGE = "${WAKAPI_DISABLE_FRONTPAGE:-true}"
    WAKAPI_PUBLIC_URL = "${WAKAPI_PUBLIC_URL}"
    [[services.storage]]
      host = "wakapi-data"
      container = "/data"
  [services.checks]
    enabled = true
    wait = 2
    timeout = 10

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_USER = "${SERVICE_USER_DATABASE}"
    POSTGRES_PASSWORD = "${SERVICE_PASSWORD_DATABASE}"
    POSTGRES_DB = "${WAKAPI_DB_NAME:-wakapi}"
    POSTGRES_PORT = "${WAKAPI_DB_PORT:-5432}"
    [[services.storage]]
      host = "wakapi-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "wakapi"
to = "postgres"
