name = "Weaviate"
description = "Weaviate is an open-source vector database that stores both objects and vectors, allowing for combining vector search with structured filtering."
category = "stack"
logo = "svgs/weaviate.png"

[[services]]
name = "weaviate"
category = "app"
subtype = "docker"
docker_image = "cr.weaviate.io/semitechnologies/weaviate:1.26.4"
start_command = "--host 0.0.0.0 --port 8080 --scheme http"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DISABLE_TELEMETRY = "true"
    QUERY_DEFAULTS_LIMIT = "1000"
    LOG_LEVEL = "info"
    GOMEMLIMIT = "1024MiB"
    GOMAXPROCS = "2"
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED = "false"
    AUTHORIZATION_ADMINLIST_USERS = "admin@example.com"
    AUTHENTICATION_APIKEY_USERS = "admin@example.com"
    AUTHENTICATION_APIKEY_ENABLED = "true"
    AUTHENTICATION_APIKEY_ALLOWED_KEYS = "${{ secret() }}"
    PERSISTENCE_DATA_PATH = "/var/lib/weaviate"
    DEFAULT_VECTORIZER_MODULE = "none"
    ENABLE_MODULES = "text2vec-openai,generative-openai,qna-openai"
    CLUSTER_HOSTNAME = "node1"
    [[services.storage]]
      host = "weaviate-data"
      container = "/var/lib/weaviate"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30
