name = "All-in-one OSINT tool for analysing any website"
description = "All-in-one OSINT tool for analysing any website"
category = "stack"
logo = "svgs/web-check.png"
[[services]]
name = "web-check"
category = "app"
subtype = "docker"
docker_image = "lissy93/web-check"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    SERVICE_URL_WEBCHECK_3000 = ""
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20
