name = "Wikijs"
description = "The most powerful and extensible open source Wiki software."
category = "stack"
logo = "svgs/wikijs.svg"

[[services]]
name = "wikijs"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/requarks/wiki:2"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DB_TYPE = "postgres"
    DB_HOST = "postgres"
    DB_PORT = "5432"
    DB_USER = "user"
    DB_PASS = "${{ secret() }}"
    DB_NAME = "wiki-db"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 30

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
docker_image = "postgres:16-alpine"
source = { type = "docker"  }
  [services.env]
    POSTGRES_DB = "wiki-db"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_USER = "user"
    [[services.storage]]
      host = "wikijs-postgresql-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "wikijs"
to = "postgres"
