name = "Windmill"
description = "Windmill is a developer platform to build production-grade multi-steps automations and internal apps."
category = "stack"
logo = "svgs/windmill.svg"

[[services]]
name = "db"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_USER = "user"
    POSTGRES_DB = "windmill-db"
    [[services.storage]]
      host = "db-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "windmill-server"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/windmill-labs/windmill:main"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "postgres:${{ secret() }}@db/windmill-db"
    MODE = "server"
    BASE_URL = "https://example.com"
    [[services.storage]]
      host = "worker-logs"
      container = "/tmp/windmill/logs"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "windmill-worker-1"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/windmill-labs/windmill:main"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "postgres:${{ secret() }}@db/windmill-db"
    MODE = "worker"
    WORKER_GROUP = "default"
    [[services.storage]]
      host = "worker-dependency-cache"
      container = "/tmp/windmill/cache"
    [[services.storage]]
      host = "worker-logs"
      container = "/tmp/windmill/logs"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "windmill-worker-2"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/windmill-labs/windmill:main"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "postgres:${{ secret() }}@db/windmill-db"
    MODE = "worker"
    WORKER_GROUP = "default"
    [[services.storage]]
      host = "worker-dependency-cache"
      container = "/tmp/windmill/cache"
    [[services.storage]]
      host = "worker-logs"
      container = "/tmp/windmill/logs"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "windmill-worker-3"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/windmill-labs/windmill:main"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "postgres:${{ secret() }}@db/windmill-db"
    MODE = "worker"
    WORKER_GROUP = "default"
    [[services.storage]]
      host = "worker-dependency-cache"
      container = "/tmp/windmill/cache"
    [[services.storage]]
      host = "worker-logs"
      container = "/tmp/windmill/logs"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "windmill-worker-native"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/windmill-labs/windmill:main"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    DATABASE_URL = "postgres:${{ secret() }}@db/windmill-db"
    MODE = "worker"
    WORKER_GROUP = "native"
    NUM_WORKERS = "8"
    SLEEP_QUEUE = "200"
    [[services.storage]]
      host = "worker-logs"
      container = "/tmp/windmill/logs"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[services]]
name = "lsp"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/windmill-labs/windmill-lsp:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
    [[services.storage]]
      host = "lsp-cache"
      container = "/root/.cache"
  [services.checks]
    enabled = true
    wait = 30
    timeout = 10

[[links]]
from = "windmill-server"
to = "db"

[[links]]
from = "windmill-worker-1"
to = "db"

[[links]]
from = "windmill-worker-2"
to = "db"

[[links]]
from = "windmill-worker-3"
to = "db"

[[links]]
from = "windmill-worker-native"
to = "db"

[[links]]
from = "lsp"
to = "db"