name = "Zep"
description = "Zep enhances your AI agent's knowledge through continuous learning from user interactions, enabling personalized experiences and improved accuracy."
category = "stack"
logo = "svgs/zep.png"

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    [[services.storage]]
      host = "pg_data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 5

[[services]]
name = "nlp"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/getzep/zep-nlp-server:0.4"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    ZEP_OPENAI_API_KEY = "${{ secret() }}"
    ZEP_AUTH_SECRET = "${{ secret() }}"
    ZEP_SERVER_WEB_ENABLED = "false"
  [services.checks]
    enabled = true
    wait = 10
    timeout = 5

[[services]]
name = "zep"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/getzep/zep:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    ZEP_STORE_POSTGRES_DSN = "postgres:${{ secret() }}@postgres:5432/postgres?sslmode=disable"
    ZEP_NLP_SERVER_URL = "http://nlp:5557"
    ZEP_EXTRACTORS_DOCUMENTS_EMBEDDINGS_SERVICE = "openai"
    ZEP_EXTRACTORS_DOCUMENTS_EMBEDDINGS_DIMENSIONS = "1536"
    ZEP_EXTRACTORS_MESSAGES_EMBEDDINGS_SERVICE = "openai"
    ZEP_EXTRACTORS_MESSAGES_EMBEDDINGS_DIMENSIONS = "1536"
    ZEP_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_SERVICE = "openai"
    ZEP_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_DIMENSIONS = "1536"
    ZEP_OPENAI_API_KEY = "${{ secret() }}"
    ZEP_AUTH_SECRET = "${{ secret() }}"
    ZEP_SERVER_WEB_ENABLED = "false"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 10

[[links]]
from = "zep"
to = "postgres"

[[links]]
from = "zep"
to = "nlp"

[[links]]
from = "nlp"
to = "postgres"