name = "Zipline"
description = "A ShareX/file upload server that is easy to use, packed with features, and with an easy setup!"
category = "stack"
logo = "svgs/zipline.png"

[[services]]
name = "zipline"
category = "app"
subtype = "docker"
docker_image = "ghcr.io/diced/zipline:latest"
source = { type = "docker"  }
  [services.scaling]
    web = 1
  [services.env]
    CORE_RETURN_HTTPS = "false"
    CORE_SECRET = "${{ secret() }}"
    CORE_LOGGER = "true"
    [[services.storage]]
      host = "zipline-uploads"
      container = "/zipline/uploads"
    [[services.storage]]
      host = "zipline-public"
      container = "/zipline/public"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[services]]
name = "postgres"
category = "database"
subtype = "postgres"
  [services.env]
    POSTGRES_USER = "${{ secret() }}"
    POSTGRES_PASSWORD = "${{ secret() }}"
    POSTGRES_DB = "zipline-db"
    [[services.storage]]
      host = "zipline-postgres-data"
      container = "/var/lib/postgresql/data"
  [services.checks]
    enabled = true
    wait = 5
    timeout = 20

[[links]]
from = "zipline"
to = "postgres"