#!/bin/bash
# RailDock Dev Environment Setup
# One-click setup for local development (macOS + Colima or Linux + Docker)
# Usage: make setup-dev   or   bash scripts/setup-dev.sh

set -e

# ── Config ────────────────────────────────────
RAILDOCK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE="docker compose -f $RAILDOCK_DIR/docker-compose.yml -f $RAILDOCK_DIR/docker-compose.dev.yml"
SSH_KEY_DIR="$RAILDOCK_DIR/data/dokku-ssh"
ENV_FILE="$RAILDOCK_DIR/.env"
BACKEND_CONTAINER="raildock-backend-1"

# ── Colors ────────────────────────────────────
B="\033[0;34m"
G="\033[0;32m"
Y="\033[1;33m"
R="\033[0;31m"
C="\033[0;36m"
N="\033[0m"

# ── Helpers ───────────────────────────────────
log_info()  { printf "${B}●${N} %s\n" "$1"; }
log_ok()    { printf "${G}✓${N} %s\n" "$1"; }
log_warn()  { printf "${Y}⚠${N} %s\n" "$1"; }
log_error() { printf "${R}✗${N} %s\n" "$1"; }
log_step()  { printf "\n${C}▶${N} %s\n" "$1"; }

print_banner() {
  printf "\n${B}╔══════════════════════════════════════════════════════════════╗${N}\n"
  printf "${B}║${N}                                                              ${B}║${N}\n"
  printf "${B}║${N}          ${G}⚡ RailDock Dev Setup${N}                                ${B}║${N}\n"
  printf "${B}║${N}                                                              ${B}║${N}\n"
  printf "${B}╚══════════════════════════════════════════════════════════════╝${N}\n\n"
}

print_success() {
  printf "\n${G}╔══════════════════════════════════════════════════════════════╗${N}\n"
  printf "${G}║${N}                                                              ${G}║${N}\n"
  printf "${G}║${N}          ${G}🎉 RailDock dev is ready!${N}                            ${G}║${N}\n"
  printf "${G}║${N}                                                              ${G}║${N}\n"
  printf "${G}╚══════════════════════════════════════════════════════════════╝${N}\n\n"
  printf "  ${B}Dashboard:${N}     http://localhost:8090\n"
  printf "  ${B}Dokku SSH:${N}     ssh -p 3022 dokku@localhost\n"
  printf "  ${B}Setup:${N}         Open dashboard → Create admin account → Create project → Deploy\n"
  printf "  ${B}Logs:${N}          make logs\n"
  printf "  ${B}Console:${N}       make console\n\n"
}

generate_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
  elif [ -r /dev/urandom ]; then
    tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
  else
    date +%s%N | sha256sum | base64 | head -c 32
  fi
}

generate_master_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    tr -dc 'a-f0-9' < /dev/urandom | head -c 32
  fi
}

create_env() {
  if [ -f "$ENV_FILE" ] && [ -s "$ENV_FILE" ]; then
    log_warn ".env already exists — keeping existing credentials"
    return 0
  fi

  local pg_pass master_key
  pg_pass=$(generate_password)
  master_key=$(generate_master_key)

  cat > "$ENV_FILE" <<EOF
# RailDock Dev Environment — generated by setup-dev.sh on $(date)
RAILDOCK_DOMAIN=localhost
POSTGRES_PASSWORD=${pg_pass}
RAILS_MASTER_KEY=${master_key}
EOF

  chmod 600 "$ENV_FILE"
  log_ok "Created .env with secure credentials"
}

generate_ssh_key() {
  mkdir -p "$SSH_KEY_DIR"
  chmod 700 "$SSH_KEY_DIR"
  if [ ! -f "$SSH_KEY_DIR/id_ed25519" ]; then
    ssh-keygen -t ed25519 -f "$SSH_KEY_DIR/id_ed25519" -N "" -C "raildock-dev" >/dev/null 2>&1
    log_ok "Generated Ed25519 SSH key pair for Dokku"
  fi
}

inject_dokku_ssh_key() {
  local pub_key="$SSH_KEY_DIR/id_ed25519.pub"
  local dokku_container="raildock-dokku-1"

  if [ ! -f "$pub_key" ]; then
    log_error "SSH public key not found at $pub_key"
    exit 1
  fi

  # Check if key is already added
  if docker exec "$dokku_container" dokku ssh-keys:list 2>/dev/null | grep -q "raildock"; then
    log_ok "SSH key already registered with Dokku"
    return 0
  fi

  # Copy pubkey into container and add it
  docker cp "$pub_key" "$dokku_container:/tmp/raildock.pub"
  docker exec "$dokku_container" dokku ssh-keys:add raildock /tmp/raildock.pub
  docker exec "$dokku_container" rm -f /tmp/raildock.pub

  log_ok "Injected SSH key into Dokku"
}

check_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    log_error "Docker is not installed"
    log_info "macOS:    brew install docker colima"
    log_info "Linux:    https://docs.docker.com/get-docker/"
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    log_error "Docker daemon is not running"
    if [ "$(uname)" = "Darwin" ]; then
      log_info "Start Colima:  colima start --cpu 4 --memory 8 --disk 60"
      log_info "Or start Docker Desktop"
    else
      log_info "Start Docker:  sudo systemctl start docker"
    fi
    exit 1
  fi

  log_ok "Docker is ready ($(docker version --format '{{.Server.Version}}'))"
}

is_stack_running() {
  docker ps --format '{{.Names}}' | grep -q "^${BACKEND_CONTAINER}$"
}

start_stack() {
  if is_stack_running; then
    log_ok "RailDock stack is already running"
    return 0
  fi

  log_step "Starting RailDock dev stack..."
  $COMPOSE up -d --build

  log_step "Waiting for backend to be healthy..."
  for i in $(seq 1 30); do
    if docker exec "$BACKEND_CONTAINER" curl -sf http://localhost:3000/api/health >/dev/null 2>&1; then
      log_ok "Backend is healthy"
      return 0
    fi
    sleep 2
  done

  log_error "Backend failed to become healthy"
  log_info "Check logs: $COMPOSE logs backend"
  exit 1
}

run_migrations() {
  log_step "Running database migrations..."
  docker exec "$BACKEND_CONTAINER" bin/rails db:prepare >/dev/null 2>&1 || {
    log_warn "Migration may have already run"
  }
  log_ok "Database is ready"
}

configure_dokku_proxy() {
  local dokku_container="raildock-dokku-1"

  log_step "Configuring Dokku proxy and network..."

  # Patch Dokku's traefik-vhosts plugin to prevent it from starting its own Traefik
  # RailDock manages a single Traefik instance that routes to both UI and app containers
  docker exec "$dokku_container" bash -c '
    PLUGIN_DIR="/var/lib/dokku/plugins/enabled/traefik-vhosts/subcommands"
    if [ -d "$PLUGIN_DIR" ]; then
      cat > "$PLUGIN_DIR/start" <<"EOF"
#!/usr/bin/env bash
echo "RailDock manages Traefik. Use docker compose restart traefik instead."
exit 0
EOF
      chmod +x "$PLUGIN_DIR/start"

      cat > "$PLUGIN_DIR/stop" <<"EOF"
#!/usr/bin/env bash
echo "RailDock manages Traefik. Use docker compose restart traefik instead."
exit 0
EOF
      chmod +x "$PLUGIN_DIR/stop"
    fi
  '

  # Set global proxy to traefik so Dokku adds traefik labels to app containers
  docker exec "$dokku_container" dokku proxy:set --global traefik 2>/dev/null || true

  # Configure Dokku apps to join the RailDock network so our Traefik can route to them
  docker exec "$dokku_container" dokku network:set --global initial-network raildock 2>/dev/null || true
  docker exec "$dokku_container" dokku network:set --global attach-post-deploy raildock 2>/dev/null || true

  log_ok "Dokku proxy and network configured"
}

inject_server() {
  log_step "Configuring local Dokku server..."

  if [ ! -f "$SSH_KEY_DIR/id_ed25519" ]; then
    log_error "SSH key not found at $SSH_KEY_DIR/id_ed25519"
    exit 1
  fi

  # Copy SSH key into container
  docker cp "$SSH_KEY_DIR/id_ed25519" "$BACKEND_CONTAINER:/tmp/id_ed25519"
  docker exec --user root "$BACKEND_CONTAINER" chmod 644 /tmp/id_ed25519

  # Inline Ruby to create/update server and assign to projects
  docker exec "$BACKEND_CONTAINER" bin/rails runner "
    privkey = File.read('/tmp/id_ed25519')
    server = Server.first

    if server
      server.update!(
        name: 'Local Dokku',
        host: 'dokku',
        ssh_key: privkey,
        status: :connected,
        dokku_version: '0.38.1',
        docker_version: '26.1.0',
        os: 'Alpine Linux',
        default_proxy: 'traefik'
      )
      puts \"Updated server: #{server.name}\"
    else
      server = Server.create!(
        name: 'Local Dokku',
        host: 'dokku',
        ssh_key: privkey,
        status: :connected,
        dokku_version: '0.38.1',
        docker_version: '26.1.0',
        os: 'Alpine Linux',
        default_proxy: 'traefik'
      )
      puts \"Created server: #{server.name}\"
    end

    Project.where(server_id: nil).find_each do |project|
      project.update!(server: server)
      puts \"Assigned server to project: #{project.name}\"
    end
  "

  log_ok "Local Dokku server configured"
}

# ── Main ──────────────────────────────────────
main() {
  print_banner

  log_step "Checking prerequisites..."
  check_docker

  log_step "Generating credentials..."
  create_env
  generate_ssh_key

  start_stack
  inject_dokku_ssh_key
  configure_dokku_proxy
  run_migrations
  inject_server

  print_success
}

main "$@"
