#!/bin/bash
# RailDock Dev Environment Setup
# One-click setup for local development (macOS + Colima or Linux + Docker)
# Usage: make setup-dev   or   bash scripts/setup-dev.sh

set -e

# ── Config ────────────────────────────────────
RAILDOCK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE="docker compose -f $RAILDOCK_DIR/docker-compose.dev.yml"
ENV_FILE="$RAILDOCK_DIR/.env"
BACKEND_CONTAINER="raildock-backend-1"
BASE_IMAGE="ghcr.io/mona-chen/raildock/raildock:latest"

# ── Colors ────────────────────────────────────
B="\033[0;34m"
G="\033[0;32m"
Y="\033[1;33m"
R="\033[0;31m"
C="\033[0;36m"
N="\033[0m"

# ── Helpers ───────────────────────────────────
log_info()  { printf "${B}●${N} %s\n" "$1"; }
log_ok()    { printf "${G}✓${N} %s\n" "$1"; }
log_warn()  { printf "${Y}⚠${N} %s\n" "$1"; }
log_error() { printf "${R}✗${N} %s\n" "$1"; }
log_step()  { printf "\n${C}▶${N} %s\n" "$1"; }

print_banner() {
  printf "\n${B}╔══════════════════════════════════════════════════════════════╗${N}\n"
  printf "${B}║${N}                                                              ${B}║${N}\n"
  printf "${B}║${N}          ${G}⚡ RailDock Dev Setup${N}                                ${B}║${N}\n"
  printf "${B}║${N}                                                              ${B}║${N}\n"
  printf "${B}╚══════════════════════════════════════════════════════════════╝${N}\n\n"
}

print_success() {
  printf "\n${G}╔══════════════════════════════════════════════════════════════╗${N}\n"
  printf "${G}║${N}                                                              ${G}║${N}\n"
  printf "${G}║${N}          ${G}🎉 RailDock dev is ready!${N}                            ${G}║${N}\n"
  printf "${G}║${N}                                                              ${G}║${N}\n"
  printf "${G}╚══════════════════════════════════════════════════════════════╝${N}\n\n"
  printf "  ${B}Dashboard:${N}     http://localhost:5173\n"
  printf "  ${B}API:${N}          http://localhost:3001\n"
  printf "  ${B}Setup:${N}         Open the dashboard → Create admin account → Add a server → Deploy\n"
  printf "  ${B}Logs:${N}          make logs-backend   (Rails)   ·   make logs-frontend (Vite)\n"
  printf "  ${B}Console:${N}       make console\n"
  printf "  ${B}DB:${N}            make db\n\n"
}

generate_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
  elif [ -r /dev/urandom ]; then
    tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
  else
    date +%s%N | sha256sum | base64 | head -c 32
  fi
}

generate_master_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    tr -dc 'a-f0-9' < /dev/urandom | head -c 32
  fi
}

create_env() {
  if [ -f "$ENV_FILE" ] && [ -s "$ENV_FILE" ]; then
    log_warn ".env already exists — keeping existing credentials"
    return 0
  fi

  local pg_pass master_key
  pg_pass=$(generate_password)
  master_key=$(generate_master_key)

  cat > "$ENV_FILE" <<EOF
# RailDock Dev Environment — generated by setup-dev.sh on $(date)
RAILDOCK_DOMAIN=localhost
POSTGRES_PASSWORD=${pg_pass}
RAILS_MASTER_KEY=${master_key}
EOF

  chmod 600 "$ENV_FILE"
  log_ok "Created .env with secure credentials"
}

check_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    log_error "Docker is not installed"
    log_info "macOS:    brew install docker colima"
    log_info "Linux:    https://docs.docker.com/get-docker/"
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    log_error "Docker daemon is not running"
    if [ "$(uname)" = "Darwin" ]; then
      log_info "Start Colima:  colima start --cpu 4 --memory 8 --disk 60"
      log_info "Or start Docker Desktop"
    else
      log_info "Start Docker:  sudo systemctl start docker"
    fi
    exit 1
  fi

  log_ok "Docker is ready ($(docker version --format '{{.Server.Version}}'))"
}

is_stack_running() {
  docker ps --format '{{.Names}}' | grep -q "^${BACKEND_CONTAINER}$"
}

wait_for_backend() {
  log_step "Waiting for backend to be healthy..."
  for i in $(seq 1 45); do
    if curl -sf http://localhost:3001/api/health >/dev/null 2>&1; then
      log_ok "Backend is healthy"
      return 0
    fi
    sleep 2
  done

  log_error "Backend failed to become healthy"
  log_info "Check logs: $COMPOSE logs backend"
  exit 1
}

build_base_image() {
  # The published GHCR image is amd64-only, so the dev image (Dockerfile.dev)
  # builds on top of a production image built locally for this machine.
  if docker image inspect "$BASE_IMAGE" >/dev/null 2>&1; then
    log_ok "Base production image already built locally"
    return 0
  fi
  log_step "Building base production image locally (first time only, takes a few minutes)..."
  docker build -t "$BASE_IMAGE" "$RAILDOCK_DIR"
  log_ok "Base production image built"
}

start_stack() {
  if is_stack_running; then
    log_ok "RailDock stack is already running"
    return 0
  fi

  log_step "Starting RailDock dev stack (first run compiles the dev/test gems — a few minutes)..."
  $COMPOSE up -d --build

  wait_for_backend
}

ensure_credentials() {
  # The dev entrypoint does not require credentials, but generate them so the
  # production compose file (which mounts them read-only) works too.
  local master_key_file="$RAILDOCK_DIR/backend/config/master.key"
  local creds_file="$RAILDOCK_DIR/backend/config/credentials.yml.enc"

  if [ -f "$creds_file" ]; then
    log_ok "Credentials already present"
  else
    log_step "Generating Rails credentials..."
    if docker exec "$BACKEND_CONTAINER" sh -c 'cd /rails && EDITOR=true bin/rails credentials:edit' >/dev/null 2>&1; then
      log_ok "Generated credentials.yml.enc"
    else
      log_warn "Could not generate credentials — the dev server works without them (app falls back to RAILS_MASTER_KEY)"
    fi
  fi

  # `rails credentials:edit` skips writing master.key when RAILS_MASTER_KEY is
  # set, but docker-compose.yml mounts it read-only — write it for parity.
  if [ -f "$creds_file" ] && [ ! -f "$master_key_file" ] && [ -n "$(grep '^RAILS_MASTER_KEY=' "$ENV_FILE" | cut -d= -f2-)" ]; then
    grep '^RAILS_MASTER_KEY=' "$ENV_FILE" | cut -d= -f2- > "$master_key_file"
    chmod 600 "$master_key_file"
    log_ok "Wrote backend/config/master.key"
  fi
}

# ── Main ──────────────────────────────────────
main() {
  print_banner

  log_step "Checking prerequisites..."
  check_docker

  log_step "Generating credentials..."
  create_env

  build_base_image
  start_stack
  ensure_credentials

  print_success
}

main "$@"
